### ISSUE TITLE
Min attribute works only on the first digit

### ISSUE THREAD

**Issue by Palafont** [guillaumepotier/Parsley.js#1001]
I have an input number with a min value, 5:

```html
<form action="myPage" method="post" novalidate data-parsley-validate>
    <input name="frequency" value="5" type="number" min="5" required />
</form>
```

When I set the value 10, I have the error "This value should be greater than or equal to 5.". When I set the value between 5 and 9, or a value greater than 50, it works fine.
It seems that the check is only on the first digit.
Is it a bug?

**Comment by guillaumepotier** [comment]
Could be yes. Could you please provide a quick jsfiddle to show the bug in action?

Th

**Comment by Palafont** [comment]
I don't reach to reproduce the problem on a jsfiddle.
Never mind, I will use my js code.
Thanks!
