### ISSUE TITLE
Disable keyup.ParsleyFailedOnce event after first failure

### ISSUE THREAD

**Issue by MicahBrown** [guillaumepotier/Parsley.js#1003]
I'm using the remote validator, but I don't want to make a request on every keypress after the initial failure. Please tell me how to do this. I've tried:

```
$form = $('form.parsley_enabled')
$form.parsley
  trigger: 'blur'
  successClass: 'valid'
  errorClass: 'invalid'
  excluded: "input[type=button], input[type=submit], input[type=reset], input[type=hidden], [disabled], :hidden"

$form.off 'keyup.ParsleyFailedOnce'
```

**Comment by marcandre** [comment]
This is currently not possible. What is the reason for your request?

**Comment by marcandre** [comment]
Actually, the latest release allows you to customize this.

**Comment by guilhermeocosta** [comment]
> Actually, the latest release allows you to customize this.

@marcandre How? I can't find this option on docs :(

**Comment by marcandre** [comment]
I was referring to the [`trigger-after-failure` option](http://parsleyjs.org/doc/index.html#ui-for-field) introduced by 061755fec69498. HTH

**Comment by guilhermeocosta** [comment]
There is a way to set it as `submit` for every single field without apply the attribute on each one?

**Comment by marcandre** [comment]
IIUC your question: Options are inherited, so you can set it on the form. Otherwise please use StackOverflow, thanks.

**Comment by MicahBrown** [comment]
@guilhermeocosta Look at the `data-parsley-debounce` option.
