### ISSUE TITLE
equalto - password confirm message

### ISSUE THREAD

**Issue by m-menon** [guillaumepotier/Parsley.js#1012]
I have 2 inputs in my form: Password and Confirm Password

When I set Confirm Password to
```
data-parsley-equalto="#form-password"
data-parsley-error-message="Password does not match the confirm password"
```

And hit the submit button when both the password and confirm password boxes are empty, I get the message "Password does not match the confirm password"

So I changed the above code to 
```
data-parsley-equalto="#form-password"
data-parsley-equalto-message="Password does not match the confirm password"
```

And it seems to work. Is this the correct way to do it? Or is there another way? I haven't seen "data-parsley-equalto-message" in the documentation though

**Comment by marcandre** [comment]
Check the last item of http://parsleyjs.org/doc/index.html#psly-ui-for-field

Improvements on documentation always welcome.
