### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by acrollet** [guillaumepotier/Parsley.js#1013]
Hi there,

it looks like the build is broken, I'm not seeing the files available for download: https://github.com/guillaumepotier/Parsley.js/tree/gh-pages/dist

If this is intentional let us know so we can change our build scripts :)

thanks!

**Comment by marcandre** [comment]
Which files are not available?

If you are looking for `parsley.remote`, it has been merged with `parsley`, there is only one version now.

**Comment by acrollet** [comment]
Ah ok, thanks for letting me know - FYI the link for parsley.remote is still shown on http://parsleyjs.org/doc/download.html

**Comment by marcandre** [comment]
Oups, indeed! Fixed, thanks for reporting this.

I also had written the wrong version number, so issued. Current is 2.2.0-rc4.

**Comment by acrollet** [comment]
sure thing, thanks for the quick response!
