### ISSUE TITLE
Submit event not preventing on complex validations (2.2.0-rc4)

### ISSUE THREAD

**Issue by ezhkov** [guillaumepotier/Parsley.js#1015]
Example
http://parsleyjs.org/doc/examples/events.html
not working. And my validation, based on this example, too. :(
Form just submits

**Comment by marcandre** [comment]
Oh, this example is out of date. Just return `false`...

I'll try to support it and deprecate that.

**Comment by marcandre** [comment]
Actually, `return false` works only on `form:submit`. Better set `validationResult` to `false`.

The example has been fixed, sorry for that.

**Comment by marcandre** [comment]
Thanks for opening this issue. Next version will allow the old way of interrupting things, and issue a deprecation warning.
