### ISSUE TITLE
FR: allow closures for i18n messages or custom global message formatter

### ISSUE THREAD

**Issue by hypeJunction** [guillaumepotier/Parsley.js#1016]
I am integrating parsley with a PHP app that has it's own i18n logic (with a client-side i18n lib). It's a plugin based app, where plugins can overwrite i18n values. Currently, we are tied to parsley's own formatMessage implementation. It would be great if there were a way to avoid maintaining messages objects for all the locales, and instead use a custom global message formatter, or set `messages` as closure that receives string, parameters and locale as arguments.

**Comment by marcandre** [comment]
IIC, you'd like us to officialize the fact that you could override `Parsley.getErrorMessage` ?

That's the function that is responsible for computing an error message, for cases where there isn't a custom one defined for a field.

Or do you actually need that `ParsleyValidatorRegistry.prototype.formatMessage` be made global and overridable?

**Comment by hypeJunction** [comment]
Yes, looks like overriding Parsley.getErrorMessage would do the trick. I would then be able to add a custom catalog with raw language keys, and use custom a formatter that is agnostic to Parsley's locale.

**Comment by hypeJunction** [comment]
Re-reading your comment, it seems that `officialize` means that it's already possible. I am looking at the code, and not sure I see how to make that work. If you could point me in the right direction, I would appreciate it.

**Comment by marcandre** [comment]
Yes, just load `parsley`, and then override it (`Parsley.getErrorMessage = function(constraint) { .... };`).

Currently, `Parsley.getErrorMessage` calls `ParsleyValidatorRegistry.prototype.getErrorMessage`, so check how it's done there for inspiration

**Comment by hypeJunction** [comment]
Thanks. That works. The only problem is instance binding. `this` is not a validator registry. 

The following works:

```js
    window.Parsley.getErrorMessage = function (constraint) {
      // format message
    }.bind(window.Parsley._validatorRegistry);
```

**Comment by marcandre** [comment]
So it's really just the formatter that you wanted to override (i.e. `ParsleyValidatorRegistry.prototype.formatMessage`)? That could be made global and overridable.

**Comment by hypeJunction** [comment]
Hm, not entirely true, because `getErrorMessage` doesn't apply `formatMessage` to all messages. What I need is for all messages to go through the formatter. I have strings in format `foo:bar`, which all need to be mapped to their translation strings and sprintf'ed if there are parameters.
