### ISSUE TITLE
Field value callback option problem

### ISSUE THREAD

**Issue by clemencov** [guillaumepotier/Parsley.js#1021]
Hi,

I have a problem with Parsley `value` option as function callback.

I have a form with text inputs, values of them should be pre-parsed via `value` callback.
But if form has at least one required checkbox I receive "You must validate an object or a string" exception.

See example: http://jsfiddle.net/clemencov/3nk43aaj/2/

Thank you

**Comment by marcandre** [comment]
Thanks for the fiddle, sorry I didn't have time to reply earlier.

For checkboxes, the result of your `value` function should be an array of values....

**Comment by marcandre** [comment]
Oh, and there was an issue with multiple anyways, fixed in `master` but yet to be released...

**Comment by marcandre** [comment]
Released `2.2.0`. Closing this, can be reopened if still an issue. Thanks!
