### ISSUE TITLE
Update Custom Validators section on the docs

### ISSUE THREAD

**Issue by alvipeo** [guillaumepotier/Parsley.js#1024]
Creating custom validators are very different from what you see in Docs. It's CONFUSING!

**Comment by marcandre** [comment]
How so? Are you using the correct version?

**Comment by alvipeo** [comment]
I'm using 2.1.3.

You have window.Parsley
  .addValidator('multipleof', {

in Custom Validators topic. But there's no such thing. window.Parsley.addValidator is undefined. Also, this is correct code to add a custom validator:

```
	window.ParsleyValidator.addValidator('datestart', function (value, minDate) {
		var dt = moment(value, "DD/MM/YYYY");
		var minDt = moment(minDate);
		if (minDt.isValid()) {
			return dt.isValid() && dt >= minDt;
		} else {
			return dt.isValid();
		}
	})
	.addMessage("ru", "datestart", "Дата не может быть раньше %s")
```
and not what one might find here - http://parsleyjs.org/doc/index.html#custom.

**Comment by marcandre** [comment]
Please use `2.2.0rc4`
