### ISSUE TITLE
Request for controlling synthetic submit button insert mode

### ISSUE THREAD

**Issue by mauricesnip** [guillaumepotier/Parsley.js#1026]
Rationale: when bottom margin resets rely on `:last-child { margin-bottom: 0; }`, the synthetic submit button causes a margin to appear on form submission.

It could be as easy as:

```javascript
// Control the synthetic submit button's insert mode, either appendTo or prependTo
submitButtonInsertMode: 'appendTo',
```

```javascript
// Add submit button's data
if (this._$submitSource) {
  $('<input class="parsley_synthetic_submit_button" type="hidden">').attr('name', this._$submitSource.attr('name')).attr('value', this._$submitSource.attr('value'))[this.options.submitButtonInsertMode](this.$element);
}
```

**Comment by marcandre** [comment]
Maybe a decent solution would be to have a new setting for the class of `parsley_synthetic_submit_button` (I should have used hyphens, btw) and change the default behavior this way:
- find existing `input` using that class.
- if it doesn't exist and we need one, create it. 
- set the `disabled` attribute, `name` and `value`  correctly.

This way, you could pre-populate your forms with that `input` and place it wherever you want, or wrap it in a `display:none` div, etc...

Does that sound ok?
If so, care to provide a PR for this?

**Comment by marcandre** [comment]
PS: Sorry for the delay...

**Comment by marcandre** [comment]
Pushed those changes to `master`.
Moreover, no longer using `synthetic-submit` thingy unless it's needed (i.e. unless using remote/promise validations).
Hope that this is good enough for you purposes.
