### ISSUE TITLE
dist/i18n/en.js contains import statement

### ISSUE THREAD

**Issue by lucash** [guillaumepotier/Parsley.js#1027]
The file for english internationalization contains an import statement in the built version.
This leads to an javascript error when it is loaded. The exact error is different depending on the browser, in Chrome (version 47.0.2526.80) it says:
> Uncaught SyntaxError: Unexpected token import

After a quick look into the build process this seems to be caused by the fact that the import statement in en.js differs from that of other language files and the function copyI18n in gulpfile.babel.js just replaces the import statement as used in the other files.

You can find an example here:
http://jsfiddle.net/58vnaqur/8/
Some javascript error occurs for me in Firefox v44.0a2, Safari 9.0.1 and Chrome 47.0.2526.80.

**Comment by marcandre** [comment]
Indeed, thanks. Fixed.
There is no need to include that file, though, it is already included in the library...
