### ISSUE TITLE
Initial valid field does not become invalid?

### ISSUE THREAD

**Issue by sabob** [guillaumepotier/Parsley.js#1029]
Hi all,

Using this example:
http://parsleyjs.org/doc/examples/simple.html

If you fill in a value for fullname, hit "validate" button and then remove all fullname characters, eg. the field is now invalid since it is required, it still shows as valid, background is green.

If you validate the form before filling in a value for firstname, it validates and shows error. When adding text it becomes valid, removing text shows error.

Is this by design?

Tested in chrome.

Kind regards

Bob

**Comment by marcandre** [comment]
Looks like a bug to me. Once you've attempted to validate a field once, I think policy is to validate it all the time after that.

**Comment by sabob** [comment]
[This] (https://github.com/guillaumepotier/Parsley.js/blob/6dd76a03b89b25ea33f423b64232120bcd8cf2b8/src/parsley/ui.js#l45-l48) code seems to be the issue.

If a field is valid initially, it isn't tracked for keyboard changes.

**Comment by sabob** [comment]
If it turns out this is not a bug, here is a workaround to track all fields once the form is validated:

```javascript
parsley.on('form:validated', function (form) {
        setFieldsInvalid(form);
});

function setFieldsInvalid(form) {
    for (var n = 0; n < form.fields.length; n++) {
        var field = form.fields[n];
        ParsleyUI.manageFailingFieldTrigger(field);
    }
}
```

Kind regards

Bob

**Comment by marcandre** [comment]
The latest release will refresh the error messages before the events are fired, which resolves the issue.

Related: #1030 and #1052 

Thanks!

**Comment by sabob** [comment]
@marcandre this still seems like an issue in the online demo here:

http://parsleyjs.org/doc/examples/simple.html

Fill in a value for fullname, hit "validate", background for fullname is green. Next, remove all fullname characters so that the field becomes invalid (fullname is a required field so background should be red), however background is still green?

**Comment by marcandre** [comment]
Actually I was wrong. Once a field has generated an error once, then it get revalidated rapidly to signify rapidly when the error disappears.

**Comment by sabob** [comment]
@marcandre thanks for clarifying.

In the latest version I notice my workaround for manually registering fields to the form doesn't work anymore since the method, ui.manageFailingFieldTrigger has been removed.

Is there any other way to manually register the field to be tracked for validations?

Kind regards

Bob

**Comment by marcandre** [comment]
If I'm not mistaken, setting the `trigger` option to `"input"` will have basically the same effect, no?

**Comment by sabob** [comment]
Thanks, the following seems to work:

*Before* I do the first validation I change the trigger option to input:
Parsley.options.trigger = 'input';
var valid = parsleyForm.validate();

It doesn't work if I first validate and then change the options:
var valid = parsleyForm.validate();
Parsley.options.trigger = 'input';

But this is in line with the documentation, in that once parsley options are set they cannot easily be changed.

**Comment by marcandre** [comment]
You may want to set only the field's or the form's options (e.g. `parsleyForm.options.trigger = 'input'`), or if you set the data attribute (of the fields, or of the form if for all fields) then you don't even have to worry about it.
