### ISSUE TITLE
field:validated fired before error added?

### ISSUE THREAD

**Issue by sabob** [guillaumepotier/Parsley.js#1030]
With this code:

parsley.on('field:validated', function (field) {
    var ok = field.$element.hasClass('parsley-error');
    // ok is false if field has error
 });

Seems field:validated is trigger before the parsley-error class is added.

One can also view this in the online example:
http://parsleyjs.org/doc/examples/simple.html

Fill in the form correctly, hit validate, then remove fullname so it show error (background is red). Notice that the callout still says "Oh snap".  Hit backspace again and the callout correctly updates to "Yay!".

**Comment by sabob** [comment]
Not sure why the online example checks for errors against the presence of the parsley-error class, but using field.isValid() returns the correct result.

Perhaps the simple example:
http://parsleyjs.org/doc/examples/simple.html
could be changed to:

```javascript
 $('#demo-form').parsley().on('field:validated', function(field) {
    var form = field.parent;
    var ok = form.isValid();
    $('.bs-callout-info').toggleClass('hidden', !ok);
    $('.bs-callout-warning').toggleClass('hidden', ok);
});
```
On the other hand, it could still be considered a bug that the 'parsley-error' class has not been added by the time the field:validated is triggered. Or perhaps this is by design.

Kind regards

Bob

**Comment by marcandre** [comment]
Completely agree with your assessment Bob.

I changed things so that error messages are added before the events are fired, as you suggested.

See also #1052 

Thanks for raising this issue.
