### ISSUE TITLE
Example should bind on form:submit instead of form:success

### ISSUE THREAD

**Issue by sabob** [guillaumepotier/Parsley.js#1031]
The example:
http://parsleyjs.org/doc/examples/simple.html

should not submit the form if valid:

.on('form:success', function() {
    return false; // Don't submit form for this demo
  });

However the form is still submitted even if false is returned.

I think the event should be 'form:submit' instead of 'form:success'. Returning false then works and cancels the submission.

Kind regards

Bob

**Comment by marcandre** [comment]
Indeed! Fixed. Thanks :+1:
