### ISSUE TITLE
TabIndex1 Select Does Not Focus After Validated..

### ISSUE THREAD

**Issue by masterpowers** [guillaumepotier/Parsley.js#1033]
Hi How can i Focus On a Select Box that is Empty at the Start after the Form is Validated
I do Have  an Default Option though like this set up...

It is Just Showing the validation Error but is not focusing...
How can i Direct the Focus Of this in JS or Jquery?
```
<select id="powerselect" name="sponsor_link" tabindex="1" required="" 
data-parsley-required-message="Sponsor Required!" data-parsley-trigger="change focusout">
    	<option value="" disabled selected datab-parsley-focus="">Choose Link</option>
</select>
```
All Input are Getting Focus Except this Select Box That I Have...

**Comment by marcandre** [comment]
As I told you before, and as written in the Read Me, and in the Contributing guidelines, please ask you questions on StackOverflow.
Please also learn how to capitalize properly.
