### ISSUE TITLE
factory(require('jquery')) is not processed by browserify-shim correctly

### ISSUE THREAD

**Issue by mfursov** [guillaumepotier/Parsley.js#1035]
Starting from v2.1.2 ParsleyJS has this line: module.exports = factory(require('jquery')

This line is not processed by browserify-shim for some reason. 

As the result any project that uses ParsleyJS will include jquery package inlined (+100Kb minified)  regardless of browserify-shim settings.

I believe there should be a way to fix this issue in Parsley.

**Comment by marcandre** [comment]
You'll have to excuse my ignorance of `browserify-shim`... but I'm not sure what the issue is, and that line is generated by `babel`...
Is `parsley` doing anything special, or is this some issue with `browserify-shim` and `babel`?

**Comment by mfursov** [comment]
Looks like it's pure browserify-shim issue. It must be compatible with babel's output.

I created the issue here https://github.com/thlorenz/browserify-shim/issues/202
and closing this one.
