### ISSUE TITLE
Circular references makes it impossible to serialize ParsleyForm

### ISSUE THREAD

**Issue by kevin-brown** [guillaumepotier/Parsley.js#1036]
Someone is going to look at the title of this and think: _Why on earth would anyone want to serialize Parsley objects?_

And that's where [Select2](https://select2.github.io/) comes in. Specifically, the following ticket: https://github.com/select2/select2/issues/4014#issuecomment-168523548

Select2 uses [`jQuery.extend`](https://api.jquery.com/jquery.extend/) to clone the [`.data()`](https://api.jquery.com/data/) attached to an element. Because it recursively copies the data, this causes recursion issues when trying to clone the `ParsleyField` attached to the element. You can see this at the following jsfiddle: http://jsfiddle.net/jew1mg89/8/

This is because [`ParsleyField.parent`](https://github.com/guillaumepotier/Parsley.js/blob/e66ef4a5932e9e51c04eb4b5e9b77525a271dd46/src/parsley/field.js#L13-L15) points to [`ParsleyForm`](https://github.com/guillaumepotier/Parsley.js/blob/e66ef4a5932e9e51c04eb4b5e9b77525a271dd46/src/parsley/form.js). And [`ParsleyForm.fields`](https://github.com/guillaumepotier/Parsley.js/blob/e66ef4a5932e9e51c04eb4b5e9b77525a271dd46/src/parsley/form.js#L14) points to instances of [`ParsleyField`](https://github.com/guillaumepotier/Parsley.js/blob/e66ef4a5932e9e51c04eb4b5e9b77525a271dd46/src/parsley/field.js). I can't figure out why, because `ParsleyField.parent` is never actually used within `ParsleyField`, and it even appears to be an optional attribute that won't always be present. It looks like it was introduced in https://github.com/guillaumepotier/Parsley.js/commit/740ed31f2b8987664ecfbae1366af54efcb9703, and it might just be that the functionality that used it has since been removed.

**Comment by marcandre** [comment]
Actually, `parent` is used. If you call `$('some-input').parsley().validate()`, that input must be able to actualize the options of the parent form. See the code in `ParsleyAbstract`'s `actualizeOptions`.

I'm not sure if there's anything simple we can do to simplify things for `select2`. My first opinion is that we should be free to store whatever we please in our own `data`, and that it's a pity that `jquery` doesn't have a safe deep clone.

I'll comment further on `select2`'s issue.

**Comment by kevin-brown** [comment]
_I'm going to take a shot at avoiding cross-repository references, to centralize discussion._

I see that `ParsleyAbstract` uses `parent` to get access to the form which the field is holding, which makes sense.

Is there any time when the `ParsleyForm` for the input _won't_ be attached to the `<form>` holding it? Because it looks like `$('#input').closest('form').data('Parsley')` is the same as `$('#form').data('Parsley')`.

http://jsfiddle.net/jew1mg89/10/

I'm definitely not familiar enough with the Parsley internals to make a recommendation on how to avoid the circular references. But it does look like [`ParsleyForm.fieldsMappedById`](https://github.com/guillaumepotier/Parsley.js/blob/e66ef4a5932e9e51c04eb4b5e9b77525a271dd46/src/parsley/form.js#L164) might be a solid way to get the `ParsleyField` for a specific form field (which should be storing the `parsleyId` internally already.

**Comment by marcandre** [comment]
Parsley supports `<input>`s that are not in a form, so `parent` could also be the global `Parsley` object.

There's some other complications in that the options need to be restructured if an input is first initialized without a form and later bound via a form (see `factory.js` and call to `_resetOptions`).

No offense intended, but I feel you are trying to fix the wrong problem. Using circular references is not an issue that needs resolving. Doing a naive deep clone on **third party data** is the issue.

**Comment by crissan** [comment]
+1
