### ISSUE TITLE
Parsley remote always works like API returns 404

### ISSUE THREAD

**Issue by amaurydixx** [guillaumepotier/Parsley.js#1039]
Hello;

The parsley remote doesn't work correctly.

<form class="form account-form" method="POST" action="../admin/index.html" data-parsley-validate id="formulaire">
<div class="form-group">
                <label for="signup-username" class="placeholder-hidden"></label>
                <input type="text" class="form-control" id="signup-username" placeholder="Identifiant" tabindex="2" data-parsley-required="true" data-parsley-remote="http://www.xxx.fr/test.php" data-parsley-remote-message="Ce compte existe déjà!">
              </div> 
</form>

In the Apache server logs, I can see that test.php script returns correct HTTP RESPONSES:
404 when it is NOK and 200 when it is OK.

XX.XX.XX.XX - - [07/Jan/2016:16:35:39 +0100] "GET /test.php?signup-username=o HTTP/1.1" 404 163 "-" "Mozilla/5.0 (Window$
XX.XX.XX.XX - - [07/Jan/2016:16:36:08 +0100] "GET /test.php?signup-username=ok HTTP/1.1" 200 156 "-" "Mozilla/5.0 (Windo$

Parsley always thinks it is not Ok.
It I put the data-parsley-remote-reverse="true", it always thinks thant it is ok.

It is like Parsley always receives 404 errors.

Any idea?

**Comment by marcandre** [comment]
Which version are you using? If you are returning an empty JSON response (which is not valid JSON), that used to cause that problem, see #956

**Comment by amaurydixx** [comment]
Thank you for your answer...
The lastest version available on the Parsley website.

**Comment by marcandre** [comment]
Then I'd double check the 'network' tab in Chrome's dev tools, just to be sure it is receiving the 200 status code...

Provide me with a link / codepen if you want

**Comment by amaurydixx** [comment]
you can test it with the link www.adixo.fr/test.php 
If www.adixo.fr/test.php?signup-username=ok it normally returns 200
404 for everything else...

**Comment by marcandre** [comment]
> XMLHttpRequest cannot load http://www.adixo.fr/test.php?signup-username=ok. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.

Are you testing your requests from another domain than `www.adixo.fr`? If so, [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) is your issue.

**Comment by amaurydixx** [comment]
Yes!!!

When I put test.php in the same Apache directory it works perfectly!

Thank you.

**Comment by marcandre** [comment]
BTW, this would have been apparent had you checked the outputs in the console...
