### ISSUE TITLE
Some Parsley's given examples are not working in Codepen

### ISSUE THREAD

**Issue by or3lie** [guillaumepotier/Parsley.js#1045]
Hello,
I'm working with multisteps form and I tried this example http://parsleyjs.org/doc/examples/multisteps.html.
On Parsley's website it works but when I click on the link "Try it in codepen" on top of page, the codepen example doesn't work and I don't understand why !
I tested other examples and the example "Using events to make complex validation" here http://parsleyjs.org/doc/examples/events.html has a problem too.

Thank you

**Comment by marcandre** [comment]
Thanks for reporting this!
Codepen was loading the wrong version of Parsley. Fixed now :smile:
