### ISSUE TITLE
Can't use multisteps form with Parsley 2.0.7

### ISSUE THREAD

**Issue by or3lie** [guillaumepotier/Parsley.js#1046]
Hello,
I'm working on a multisteps form and I'm using Parsley 2.0.7, I can't easily update my version but I saw that group support was added in 2.0.4 so I think I can use it but even with the parsley's given example I can't.
With Parsley 2.2.0 no problem the example works : https://jsfiddle.net/or3lie/z5f0zy2m/ but with Parsley 2.0.7 it doesn't work : https://jsfiddle.net/or3lie/d5tpue9t/ it always validate steps even if fields are empty. Parsley only shows error messages at the last step = the submit.
Of course I have the same problem on my dev website :(

Thanks a lot if you can help me !

**Comment by marcandre** [comment]
I'm very sorry, but I am the only active maintainer and I will not support older versions of Parsley.

Please update or ask for help on StackOverflow...

**Comment by or3lie** [comment]
Ok thanks for the information ;)
