### ISSUE TITLE
Configuration override and initialisation order after 2.1.0

### ISSUE THREAD

**Issue by StevenVerbiest** [guillaumepotier/Parsley.js#1050]
After an upgrade to 2.1.0 I'm unable to override some default settings, unless I set them before I load Parsley. 

In 2.0.0 I was able to load Parsley, set some defaults and initialise:

```
<script type="text/javascript" src="parsley.min.js"></script>
<script>
window.ParsleyConfig = {
  classHandler: function () {
    // do stuff
  },
  errorsContainer: function () {
    // do stuff
  }
};
</script>
```
After 2.1.0, window.ParsleyConfig must be set **before** including Parsley, which is cumbersome in my current setup.

**Comment by marcandre** [comment]
The preferred way to set options is to do, **after** Parsley has loaded:

    window.Parsley.options.classHandler = function() { };

Or if you have multiple overrides to do:

    $.extend(window.Parsley.options, {
      classHandler: function() { },
      errorsContainer: function() { }
    });

Also, you should upgrade to v2.2 :smile:

**Comment by StevenVerbiest** [comment]
I'm currently updating our internal framework to the latest version of Parsley. That's how I stumbled upon this issue.

Extending the parsley options object works like a charm by the way. Thanks for the help!
