### ISSUE TITLE
Wrong error message for input type number with pattern

### ISSUE THREAD

**Issue by jcubic** [guillaumepotier/Parsley.js#1051]
I have code like this:

```html
<form>
<input type="number" required="true" pattern="^\d{1,3}$"/>
<input type="submit" value="ok"/>
</form>
```

and when I type `eeee` and click ok I got error `This value is required.` and when I remove required attribute I don't have any error message.

Here is [jsFiddle](https://jsfiddle.net/Lsd39zxu/1/) with the problem.

**Comment by jcubic** [comment]
Same happen if you type `+` or `.` or any number and those characters.

**Comment by marcandre** [comment]
Yup. See http://parsleyjs.org/doc/index.html#psly-validators-list 
Also #874, #751.
PR welcome for better documentation.
