### ISSUE TITLE
Drop jquery dependency

### ISSUE THREAD

**Issue by Flaburgan** [guillaumepotier/Parsley.js#1053]
This is just an interrogation. I use parsley for months and find it really cool. However, I target IE11+ and last Firefox and Chrome browsers, so I don't need JQuery and would love to not use it. Is there a plan to create a separate version of parsley for modern browsers which doesn't depend of JQuery? ES6 is here we almost all we need :)

**Comment by marcandre** [comment]
Glad you can target IE11+, that's not everyone's case though.
Removing jQuery is not in the foreseeable future, sorry.

**Comment by Flaburgan** [comment]
I guess there is too much code to rewrite and to maintain two separate versions is too much code for a too small goal. ES6 is the future though, we will come there one day. Thanks for your work anyway. :)

**Comment by marcandre** [comment]
Yeah, if there's ever a transition out, it would be one way I think (i.e. remove jQuery completely except for a thin wrapper).
BTW, we have moved to ES6, although the codebase can still use a bunch of features we haven't used.

**Comment by marcandre** [comment]
More details in #1100

**Comment by marcandre** [comment]
FYI, there's a possibility that we will go forward at some point with this, subscribe to 1100 if interested...
