### ISSUE TITLE
No parsley.remote.js in npm 2.2.0

### ISSUE THREAD

**Issue by jessemorton** [guillaumepotier/Parsley.js#1054]
There's no parsley.remote.js available in the 2.2.0 npm release, and including the parsley.js alone in my Browserify setup didn't allow me to take advantage of the `addAsyncValidator` method, erroring out instead. I reverted back to 2.1.2 in the meantime to continue use of Parsley.

**Comment by marcandre** [comment]
I wonder how you were calling `addAsyncValidator`.

The `remote` version has been merged. Use `window.Parsley. addAsyncValidator` and let me know how you used to call it though, it should still be compatible.
