### ISSUE TITLE
max validator does not work with date input

### ISSUE THREAD

**Issue by Chapell** [guillaumepotier/Parsley.js#1055]
If I put a max validator (e.g. max="2099-12-31") to a date input, parsley throws an exception because it's not a number. However, for a date input the max above is perfectly valid and is also required so that Chrome's (and maybe other browsers') renderer will handle the input correctly and will allow only 4 year characters and not 6 (which is the default for date input).

**Comment by marcandre** [comment]
Indeed :-(

Closing this, as it duplicates #814 

PR welcome!
