### ISSUE TITLE
type="number" not always working with step="X"

### ISSUE THREAD

**Issue by 719media** [guillaumepotier/Parsley.js#1056]
I'm trying to use parsley to validate currency types. I understand I can write a custom validator, but I was hopeful that just using <input type="number" step="0.01" value="" /> would work, but it does not.

This seems to be because of the line

```
if ((nb * mul - base * mul) % (step * mul) != 0)
```

in validator_registry.js

that doesn't correctly multiply for comparison as expected (floating point rounding). For example, in javascript on mac in firefox browser, 1.11 * 100 comes back as 111.00000000000001

Unfortunately, I don't know how best to fix the issue. I think it is an issue because it seems like it should work.

Thanks for any input.

**Comment by marcandre** [comment]
Thanks for the report :smile_cat: 
I should know better :bomb:
Fixed in `master`, should release pretty soon.
