### ISSUE TITLE
Form doesn't submit if submit buttons name is "submit"

### ISSUE THREAD

**Issue by roopemerikukka** [guillaumepotier/Parsley.js#1057]
I just updated old projects Parsley from 1.x to 2.2.0 and after a while of debugging I noticed that if there is an input submit field that has name="submit" it doesn't get submitted after successful validation.

Doesn't work:
```html
<input type="submit" name="submit" value="submit">
```

Works:
```html
<input type="submit" name="send" value="submit">
```

I also made a quick codepen to demonstrate the issue: http://codepen.io/roopemerikukka/pen/vLzaGN

This worked in old version and I don't know if this is a bug or by design but I didn't notice any documentation pointing out this new behaviour.

**Comment by marcandre** [comment]
Please check: http://stackoverflow.com/questions/3571328/form-submit-button-will-not-submit-when-name-of-button-is-submit

The next version will not have this issue *if you don't use any asynch validations*. As soon as you use asynch validators, you will have the same issue.

I recommend not naming your button this way...

**Comment by roopemerikukka** [comment]
Thanks for the answer. Towards a better naming conventions it is then!
