### ISSUE TITLE
issue with 2.3.1?

### ISSUE THREAD

**Issue by brewster1134** [guillaumepotier/Parsley.js#1061]
just for my own clarification... there was a moment when I was running v2.3.1 and received a variety of errors.  while troubleshooting it, v2.3.2 was relelased and resolved things.  was v2.3.1 known to be a flawed release?

i can roll back to it and provide specific errors if needed

**Comment by marcandre** [comment]
Yeah, you're probably using `classHandler` or `errorsContainer` as functions, those broke in 2.3.1, sorry for that. See #1060.

**Comment by brewster1134** [comment]
yup i was using both. thanks for the confirmation! :)
