### ISSUE TITLE
Field is not defined errors in 2.3.2

### ISSUE THREAD

**Issue by navied** [guillaumepotier/Parsley.js#1063]
With the new update, my old parsley code seems to be having "field not defined" errors occur on the keyup event. You can see an example of this here:

http://jsfiddle.net/sbahg48q/2/

The errors occur after typing in 4 characters, and keep occurring once they start. I tried to look into what might be causing it and it seems to be related to the to the triggerAfterFailure changes.

**Comment by marcandre** [comment]
Ouch, major bug. Sorry, expect a release asap

**Comment by marcandre** [comment]
Fixed and released. Thanks for reporting this :smile:

**Comment by navied** [comment]
No worries! Thanks for the quick fix  :+1:
