### ISSUE TITLE
Error when going to 2.3.3 from 2.2.0

### ISSUE THREAD

**Issue by KrunchMuffin** [guillaumepotier/Parsley.js#1065]
I am getting this error which I was not before
`TypeError: Cannot read property '$errorsWrapper' of undefined`

errorsWrapper is defined

        elEventForm.parsley({
        successClass: "",
        errorClass: "has-error",
        classHandler: function(el) {
            return el.$element.closest(".form-group");
        },
        errorsWrapper: "<span class=\"help-inline\"></span>",
        errorTemplate: "<span></span>"
    });

**Comment by marcandre** [comment]
Sorry about that...
Could you tell me what the code that causes the error?

**Comment by marcandre** [comment]
It's quite difficult to address this without at least knowing which code line causes the issue. Best would be a codepen.

**Comment by KrunchMuffin** [comment]
sorry. just been busy. From what I remember I don't even have validation where it was occurring.

**Comment by marcandre** [comment]
Just to be clear: best case scenario is if you can provide a codepen where the error occurs. Otherwise there's no way for me to tell what is going on.

**Comment by KrunchMuffin** [comment]
Think I found the issue.
getting `Accessing ParsleyUI is deprecated. Call 'removeError' on the instance directly.`
when I using

    window.ParsleyUI.removeError(actCountParsley, 'min');
    elActivityCount.parent().removeClass("has-error")

what is the new way cause the docs still say to use that.

**Comment by irongaze** [comment]
Yeah, the docs for addError/removeError/etc are very wrong, and the deprecation code itself blew up for me ("instance is undefined") when using addError when upgrading from 2.0.0.  Would be great to expand/fix the docs for this use case for those of us integrating Parsely with existing code/frameworks.

**Comment by marcandre** [comment]
@KrunchMuffin The new way is to use `actCountParsley.removeError('min')`.

@irongaze If `instance` is undefined, I think that means that the first argument you're passing is `undefined`, which would be an error on your end, no?

I anyways, I think this is fixed in the last release, let me know otherwise.

I would like to understand better the need for `removeError` and al, please comment in #1073.
