### ISSUE TITLE
IE8 isArray with Parsley Version 2.3.3

### ISSUE THREAD

**Issue by sGendt** [guillaumepotier/Parsley.js#1066]
Hello,
Just to point out that the isArray function is not supported by Internet Explorer 8: http://caniuse.com/#search=isArray()
I have temporarily fixed the problem on my project with this script:

`Array.isArray = function (obj) {
    return Object.prototype.toString.call(obj) === "[object Array]";
};`

I Tried Parsley JS in the Windows 7 environment and Internet Explorer 8 with Virtual Machine:
https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/

Bb

**Comment by marcandre** [comment]
Indeed, that's why we have the https://github.com/guillaumepotier/Parsley.js#requirements section...

**Comment by sGendt** [comment]
Thx, may be you can write this information on http://parsleyjs.org/, because this is the way i come.

**Comment by marcandre** [comment]
Good point, done!
Thanks

**Comment by sGendt** [comment]
You're fast, ti's nice!
See you
