### ISSUE TITLE
remote validation breaks when `data` is `FormData()`

### ISSUE THREAD

**Issue by papiro** [guillaumepotier/Parsley.js#1067]
I've got an `$.ajax` options object which looks as such:

    {
            contentType: false,
            headers: {
                "Authorization": "Bearer " + WAMSession.get("token")
            },
            method: "PUT",
            processData: false,
            url: ENVCONFIG.serviceRoot + "/images?" + $.param(serialData),
            data: imgFormData
    }

`imgFormData` is a `new FormData()` instance with an image binary appended.

What happens is it gets run through `$.param` (in remote.js source) when trying to build a key for the remote caching.

I alleviated the issue locally by removing the 5 or so lines of code which implement the remote caching, and I wondered, what was the original intent of the remote caching?  Is it a fix to a bug or a feature?

If it's a feature, I thought about making a pull request which allows for a parameter like `{ remoteCache: false }` or something like that.

Thanks,
-Pierre

**Comment by marcandre** [comment]
The caching is definitely a feature, to avoid hits on the server for values that have already been tried. Ideally `parsley` would be `FormData` aware and build the cache key from the form data. Would that work for you?

**Comment by papiro** [comment]
That would work, for sure.  Just not sure how I would implement that.  Any ideas?  Also, what if the UI wanted to try the same exact call more than once?  Like what if the validation depended on some variable on the server?  Does that sound weird?

**Comment by marcandre** [comment]
Yeah, it does sound weird :smile:  We clear the cache after a successful validation, btw.
So for example if there's a check for a duplicate email on account creation, then that will still work.
So it's basic cache management, but I've yet to see a valid example where it doesn't do the job...

Haven't tried it, but if `$.param` chokes on `FormData`, you could find a way to serialize it yourself and then call `$.param` on a copy of `ajaxOptions` where the `data` field has your serialized version.

Are you feeling like creating a PR for this?

**Comment by papiro** [comment]
Well, I definitely don't mind doing a PR for the fix.  I'm just wondering - in my case I'm appending binary data.  Can that be serialized?  Should it be base64-encoded before serialization?  How about being able to "turn off" remote caching on a case-by-case basis?

**Comment by marcandre** [comment]
Wow, sending binary for validations? That's using the FileAPI, right?
Just curious: are you validating whole files?
For binary files best thing would be to serialize using a hash (a simple one, like [this one](http://werxltd.com/wp/2010/05/13/javascript-implementation-of-javas-string-hashcode-method/))?

**Comment by papiro** [comment]
Yep, you are correct.  Currently we're validating image dimensions, file size, and file extension.  I suppose somebody could also do validation on bit-depth/contrast/things like that, which sounds cool.  Hmmm, I'll have to play around with this serialization thing.  I don't suppose I could coerce the binary data into a string?  Sorry if that sounds like a dumb question, I haven't dealt with this situation before!

**Comment by marcandre** [comment]
Just my opinion, but if you want to do things right, you should do all that client side...
I don't know if there's something like https://github.com/sdsykes/fastimage in Javascript, but that's what you should be writing IMO. It's not very hard to get the image size from an image, it doesn't require much parsing.
Or else actually presend the image (like gmail does, for example), you can validate it server side if you want, but if you use parsley & ajax to do the validation, it would feel *very slow* and wasteful to send a full image just to validate it, and to send it again once validation succeeds.
BTW, we have an example of how to validate the byte size of a file [here](http://parsleyjs.org/doc/examples/customvalidator.html), so it should be similar just a bit more involved as it requires parsing.
If you end up coding generic `image-size`, `file-type`, etc. custom validators, I'd be glad to include them in our `extra` folder.

**Comment by papiro** [comment]
You're totally right.  Thank you for thinking this through with me.  I'm not sure what we'll decide to do (it's not entirely up to me).  It doesn't necessarily provide a bad user experience for our implementation because the image uploads are happening on a form with many images which need uploading, and there's other things on the form the user will have to address while the images are being validated and uploaded.  Client-side validation is definitely a sound idea at this point....  Again, thank you so much for putting your mind together with mine on this.

**Comment by papiro** [comment]
Hi Marc, I have a question pertaining to this.  How does Parsley send a validation request, but without the server taking it as the actual POST/PUT request?

I ask because in doing the remote validation on binary image files, how does our server know that what it's receiving is just a "test"?

**Comment by papiro** [comment]
Discovered that the image gets uploaded via our implementation just on the validation so I went ahead and implemented the remote validation as the actual uploading itself and it works like a charm!

**Comment by marcandre** [comment]
So you are using a custom validation but would have used the builtin `remote` one if it supported `FormData`, right?

**Comment by papiro** [comment]
Hmmmm.  I'm using Parsley's remote validation, but augmenting the request greatly via `.on("ajax:options")`, and then handling the response in a custom remote validator.  I excitedly did all the development and pushed to our dev environment, only to realize that I had still had to construct a pull request to fix the `FormData` issue, which I had skated around by just removing the remote caching.

I am currently working on the pull request and was unable to find any way to serialize the `FormData` as I was not able to `get` any of the data I had `appended` into it, due to lack of browser support for anything other than `FormData.prototype.append`.  I tried to use the java hashcode method you provided a link to but there's no way I can get any sort of `string` representation for `FormData`.  

Currently, the pull request is formed in a way I am happy with, basically `try`ing to serialize the `ajaxOptions` and if failing, setting `options.useCache` to `false` therefore bypassing the remote caching just for this instance.  This also supports passing `{useCache: false}` as an option if for some reason the validation depends on server-side variables of which client-side caching would defeat.  But now I'm battling with the test for it....

**Comment by marcandre** [comment]
Is there a valid reason for not simply creating a custom validator that will do the ajax request?

**Comment by papiro** [comment]
Not really, but then what's the difference between doing that and the remote-validator?  Is it just to bypass the remote-caching?  

If I were to create a "normal" custom validator, what would that look like?  Would I use the `validateString` method?  If so, would it return a `promise`?
