### ISSUE TITLE
Error of select element doesn't hide automatically on firefox

### ISSUE THREAD

**Issue by mAmged** [guillaumepotier/Parsley.js#1068]
Error of select element doesn't hide automatically on firefox.
I've to submit the form to hide the error.

**Comment by marcandre** [comment]
Argh. :sob: 
Looks like a very basic bug in Firefox. Couldn't file an existing one so filed [a new bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1250521). It seems incredibly basic, but I don't see what I could be missing.
At this point I'll simply add an ugly patch to alleviate this bug...

**Comment by marcandre** [comment]
Fixed and released.
Thanks for reporting this!
