### ISSUE TITLE
this._ui undefined when adding an error manually

### ISSUE THREAD

**Issue by irongaze** [guillaumepotier/Parsley.js#1071]
See codepen here: http://codepen.io/anon/pen/GZKpvj

It's like 2 lines of code.  Blows up in _insertErrorWrapper().  

Would re-iterate that more/better documentation on manual error management would be hugely appreciated.  There's no real guidance given on how to integrate non-parsley use cases into the system, which makes real-world integrations tough for not-from-scratch projects.

**Comment by marcandre** [comment]
Sorry about this, I'll fix it.

TBH, I don't know of any good use of `addError`, etc..., I've never used them in practice. My guess is that integration with non-parsley should always go through custom validators, but maybe I'm missing something?

**Comment by irongaze** [comment]
Here are two use cases I'm running into:

1. Validation that requires more than one field ("whole form" validation)
2. Integration with existing code that does not work per-field, or has a different event model (async validations that are not covered by the model used in Parsley, for example)
3. Multi-step validation, i.e. where one step must be completed (generating a token, hitting an API) before other validations can run

I'm sure some of these can be handled using Parsley (I'm still learning) but it is much simpler to validate using Parsley's built-ins in one pass, then do the other stuff before submit.  This requires a working addError/reset feature.

Cheers!

**Comment by papiro** [comment]
I've had to use `addError` when setting a custom message via a remote validator (otherwise it uses the `defaultMessage`), in which case I also noticed this exact issue so I had to do `this._buildUI()` before proceeding to `addError`

**Comment by marcandre** [comment]
Indeed @papiro, not calling `_buildUI` was the issue. I've released a version that fixes it, sorry for that.

I've opened a different issue to help me understand (and eventually get rid of) the need for `addError` & al. I'd be very grateful if you added some info there as to your uses of them.

Thanks!

**Comment by papiro** [comment]
Thanks for the fix!

**Comment by marcandre** [comment]
@papiro You can return a custom error message, please see my edited text in #1073
