### ISSUE TITLE
documentation clarity isValid vs validate

### ISSUE THREAD

**Issue by comatory** [guillaumepotier/Parsley.js#1072]
hello.

maybe i've missed something but I couldn't find this in documentation... is function `isValid` also triggering validation like `validate`? i have custom and remote validator on one field plus javascript object calling `isValid` to check whether field is valid/invalid. this is causing me some grief because my `field:success` listener gets hit twice with everything,

see my problem here: http://stackoverflow.com/questions/35676142/parsley-js-prevent-isvalid-from-firing-events-just-check-true-or-false

**Comment by marcandre** [comment]
`isValid` should run the validations but not fire events.

**Comment by comatory** [comment]
it makes sense that it runs the validations, however the async validator specified in `addAsyncValidator` gets triggered with `isValid` as well, even if the remote validator has not been triggered.

**Comment by marcandre** [comment]
Sorry, not sure I understand...

It's possible that the remote validator is not triggered because the result has been cached, i.e. it has already been requested with the same data. Is that causing you a problem?

**Comment by comatory** [comment]
Hi sorry for not being clear. I'm just under a lot of stress trying to finish this. I really like parsley but I had to circumvent it for one field because it just wouldn't do what I wanted to do.
I'd like to show the code but it's a part of company app. I'm probably not doing something right here. I have this strange behaviour.
I had one input field with `data-parsley-trigger` set to `input`. The input has one custom validator attached to it and one remote validator attached to it. For some strange reason, the validations are firing twice for custom (local) validator but only when used with input trigger. It's behaving normally with change trigger.

What's even stranger is when i put `console.log` on top of custom validator, I could see the log being printed twice, but when i put debugger in there, it would only stop twice.
I really have no idea because of this behaviour, I'm pretty sure I checked if I'm not attaching the same input to the same event twice or if I'm not initializing stuff twice but I couldn't really figure it out. It could be much broader problem caused by different part of javascript (it's a modestly sized Rails app).

Well anyways I know you can't probably help me if I'm not so specific but I am wondering if you have any idea what this behaviour can mean? Thanks.

**Comment by marcandre** [comment]
What you're describing is very odd indeed. Using `trigger=input` vs `trigger=change` should simply validate on every keystroke (after the `validationThreshold`) instead of when focusing out. Is that what you are seeing? Your input is `type="text"`?

You can always email me code if you don't want it to be public

**Comment by comatory** [comment]
Maybe I will email you the code. Well actually the field is type=number, not text. Would that make difference?

**Comment by marcandre** [comment]
`number` should be the same. Be careful of the way it behaves, be sure to read `http://parsleyjs.org/doc/index.html#validators`

**Comment by marcandre** [comment]
No feedback, no code, closing for now
