### ISSUE TITLE
Problem when validating masked fields

### ISSUE THREAD

**Issue by marcelgsantos** [guillaumepotier/Parsley.js#1076]
Hello!

There is a problem when we try to validate some masked fields like **date** or **phone numbers** that uses [jQuery Masked Input plugin](http://digitalbush.com/projects/masked-input-plugin/).

When you enter an invalid value in any masked field, it is validated correctly and an error message is triggered. But when we try to provide a valid value to this field, it seems that the validation doesn't work anymore and the previous error message doesn't disappear.

I created an example that you can see the problem with both built-in and customized validators.
http://codepen.io/marcelgsantos/pen/BKygxo

I used Parsley.js 2.3.5 and jQuery Masked Input 1.4.1.

Thanks,

Marcel dos Santos

**Comment by marcandre** [comment]
**Thanks** for the Codepen :-)
Indeed, it looks like validation doesn't happen when it should. I'll try to check this more closely tomorrow or thursday to understand what's going on.

**Comment by marcandre** [comment]
I think I got it. The plugin intercepts the keypress event (which `parsley` no longer relies on) but by doing so, the browser doesn't trigger the `input` event that `parsley` needs.
I will propose a PR for masked input that triggers the `input` event when they do that...

**Comment by jamesdbruner** [comment]
I'm running into this right now as well.  Keep us posted on an update!

**Comment by marcandre** [comment]
I created https://github.com/digitalBush/jquery.maskedinput/pull/364
I'm not holding my breath, the last commit for that library is about a year old! Looks like it's not maintained anymore.

A quick fix if you want to use it nevertheless (not tested):
```
$(document).on('keypress', function(evt) {
  if(evt.isDefaultPrevented()) {
    // Assume that's because of maskedInput
    // See https://github.com/guillaumepotier/Parsley.js/issues/1076
    $(evt.target).trigger('input');
  }
});
```

**Comment by marcandre** [comment]
I'd recommend people switch to `https://github.com/RobinHerbots/jquery.inputmask` which is maintained and seems even more capable. It also takes care of the `input` even and so should be working fine with Parsley.

**Comment by chandru1822** [comment]
How i can do the parsley validation if all fields are entered properly, I want to change the state of button from disable to enable without using any event.
 Please suggest me a idea to solve this.
