### ISSUE TITLE
Localization load order

### ISSUE THREAD

**Issue by steveshaddick** [guillaumepotier/Parsley.js#1077]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by steveshaddick** [comment]
The documentation mentions that it is possible to load the localization files before loading the parsley library file (http://parsleyjs.org/doc/index.html#psly-installation-localization). However, this results in "Reference Error: Parsley is not defined".

Localization files must be loaded after the library, since they reference the Parsley object. Either the documentation is simply out of date, or this is a bug.

**Comment by marcandre** [comment]
Thanks for bringing this up. Documentation is out of date, sorry...

**Comment by marcandre** [comment]
Fixed. Thanks again
