### ISSUE TITLE
validation on key trigger slow down performance

### ISSUE THREAD

**Issue by ecentinela** [guillaumepotier/Parsley.js#108]
I'm using a keyup trigger on a a parsley remote validated field.

If I type some characters quickly, some of these characters are never written because the keyup trigger validation slows down the process.

Maybe you should call the triggered function after a setTimeout.

I mean something like:

```
var validate = function() {
...
}

clearTimeout(timeout);

setTimeout(function() {
    validate();
}, 300)

```

**Comment by iwasherefirst2** [comment]
Having the same issue. How did you fix it in 2013 :D?

**Comment by marcandre** [comment]
You could try with a very low `data-parsley-debounce`

**Comment by iwasherefirst2** [comment]
@marcandre perfect that was what I was looking for.  I am using a remote validation and I did not want to send an ajax every keystroke. Thanks!!
