### ISSUE TITLE
Parsley UI not updated when check box is valid.

### ISSUE THREAD

**Issue by jpoiri** [guillaumepotier/Parsley.js#1080]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hi,

When I put data-parsley-required="true" and data-parsley-trigger="click" on a single check box and uncheck the check box it will display an error, however when click the check box again the message will not disappear. However when I submit the form the message is removed.

Here's the example:

http://codepen.io/jpoiri/pen/BKQavJ?editors=1010

**Comment by marcandre** [comment]
Urgh, sorry for that. I'm working on this, this is actually a browser bug that doesn't always fire an `'input` event when needed.

**Comment by marcandre** [comment]
Ok, should be good now, on all browsers... 2.3.9 released.

Thanks for reporting this, and sorry for the trouble.

**Comment by kganesan0108** [comment]
Hi, 
I get an error saying 'Symbol' is undefined after I upgraded to the latest version of parsley, also my issue is for input element with Jquery datepicker, will this upgrade fix that?

![parsley_error](https://cloud.githubusercontent.com/assets/18427032/14542977/7d7240fc-0257-11e6-84a9-07d180eb37a1.png)

**Comment by marcandre** [comment]
Oh, I'm sorry about this. Just released a fix (2.3.10), thanks for reporting this.

**Comment by kganesan0108** [comment]
Thank you.. Appreciate it
