### ISSUE TITLE
404 in parsley remote documentation

### ISSUE THREAD

**Issue by Flaburgan** [guillaumepotier/Parsley.js#1081]
The [parsley remote documentation](http://parsleyjs.org/doc/index.html#remote) starts with a link to http://parsleyjs.org/doc/annotated-source/main.remote.html which is a 404.

Is remote now included in parsley? If I remember correctly, it was an external JS to include after parsley. How do I use it now?

**Comment by marcandre** [comment]
Indeed. Fixed. `remote` is now builtin.

**Comment by marcandre** [comment]
Thanks for the report
