### ISSUE TITLE
Error of select element doesn't hide automatically on all IE versions

### ISSUE THREAD

**Issue by mAmged** [guillaumepotier/Parsley.js#1082]
Error of select element doesn't hide automatically on IE when I select a valid option.
I've to submit the form to hide the error.
PS. this is a cloned issue from [this](https://github.com/guillaumepotier/Parsley.js/issues/1068) on firefox
So apparently this is a common issue on several browsers, so you need to test it on most browser or write a generic solution for all.

**Comment by mAmged** [comment]
Fixed

**Comment by marcandre** [comment]
Mmm, indeed. Fixed & released, thanks.
