### ISSUE TITLE
[REQUEST] Pass ParsleyField into validator functions

### ISSUE THREAD

**Issue by cerlestes** [guillaumepotier/Parsley.js#1083]
Please pass the ParsleyField instance into the validator function, instead of only passing the plain value object. This would break the current API, but currently there's no way to write extensive validators without a lot of event-foo just to work around this. You could even do it non-breaking by passing the field instance as third argument into the validator function, along the plain value and the "requirements".

Example: We've wanted to implement a 'requiregroup' validator, that validates whether at least one out of a defined group of inputs is filled. This currently simply isn't possible, without so much more code than should be needed and a lot of handling events. If the validator could access the field instance, and thus the form instance, it would be very easy to write this validator, and many others.

Edit: Thinking about it once again, adding a validator function 'validateParsleyField' that receives the field instance would probably be the best way to do it.

**Comment by marcandre** [comment]
Sorry about the fact that the documentation isn't clear about that (PR welcome), but the instance is passed as the last parameter :smile:

See for example the third validator in the [custom validator demo](http://parsleyjs.org/doc/examples/customvalidator.html)

**Comment by cerlestes** [comment]
Ugh, my bad. We're still running 2.0.x and I didn't check for updates. Thanks for the heads up!
