### ISSUE TITLE
Validation does not occur until after 3 characters

### ISSUE THREAD

**Issue by navied** [guillaumepotier/Parsley.js#1084]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

This is something that seems to be have been introduced in the 2.3.x versions of the js. 

As you can see here: 

http://jsfiddle.net/sbahg48q/2/

The validation does not start working until you type in at least 3 characters, but after that it works perfectly well with no character limit.

**Comment by marcandre** [comment]
IIC, this is desired and customizable. Please check the `validation-threshold` option.

**Comment by navied** [comment]
Ah thanks for pointing that out!
