### ISSUE TITLE
validationResult change ignored at the field level

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#1087]

**Comment by marcandre** [comment]
Fixed in master, releasing tonight. cc @JeroenReumkens

**Comment by JeroenReumkens** [comment]
Awesome! Will check it on wednesday! Thanks for fixing it that quick!

**Comment by JeroenReumkens** [comment]
Hi @marcandre,
Just wanted to let you know that I've just upgraded Parsley, and that your change is working as expected! 
Thanks for fixing this so quickly, really appreciate it! 

Jeroen.
