### ISSUE TITLE
Can't seem to prevent default on `form:submit` event

### ISSUE THREAD

**Issue by Chris-May** [guillaumepotier/Parsley.js#1088]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I'm following [the documentation](http://parsleyjs.org/doc/index.html#psly-events-list) as best I can tell, but I can't prevent the form submission. The docs say `form:submit` is:

> Triggered when after a form validation succeeds and before the form is actually submitted.
Prevent the default to interrupt submission.

But the passed in event has no `preventDefault` property. Calling `e.submitEvent.preventDefault()` throws a deprecation warning and suggests `e.validationResult = false`. Neither seem to work, as evidenced in [this codepen](http://codepen.io/chrismay/pen/WwdRyK).

Am I doing something wrong?

**Comment by marcandre** [comment]
Sorry about this, the doc is out of date. Simply return `false`. Doc updated.
Thanks for reporting this!

**Comment by Chris-May** [comment]
Wow! Thanks for the quick response!
