### ISSUE TITLE
Disable keyup validation after ParsleyFailedOnce

### ISSUE THREAD

**Issue by hanxue** [guillaumepotier/Parsley.js#1090]
I have a custom validation function that will fill up numbers to a length of 10. With `ParsleyFailedOnce`, the code that runs the prefix does not work. I want the validation to work only when there is `focusout` instead of `keyup`. 

http://codepen.io/hanxue/pen/XdZRoE?editors=1011

To reproduce:

1. Type in alphabets in the input field, the focus out. 
2. Parsley will show error
3. Remove invalid input, type in numbers
4. As soon as there is a keystroke, the validation code will run, causing the input field length to be > 10

For convenience, here is the code

```html
<form id="demo-form" data-parsley-validate>
  <input type="text" id="card_number" name="card_number" class="form-control"        data-parsley-required="true" data-parsley-trigger="focusout" 
         data-parsley-required-message="You did not enter Card Number!"
         data-parsley-numeric=""
         data-parsley-zeroprefix=""
       />
  <input type="submit" class="btn btn-default validate" />
</form>
```

```javascript
window.Parsley.addValidator('numeric', {
  validateString: function(value) {
    return !isNaN(parseFloat(value)) && isFinite(value);
  },
  requirementType: 'integer',
  messages: {
    en: 'Enter only numbers for Card Number.'
  }
});

window.Parsley.addValidator('zeroprefix', {
  validateString: function(value) {
    if(isNaN(parseFloat(value)) && isFinite(value)) {
      return false;
    }
    else if(value < 1) {
      return false;
    } else {
      if(value.length < 10) {
        var original_length = parseInt(10) - parseInt(value.length);
        var zero_prefix = "";
        for (var i = 0; i < original_length; i++) {
           zero_prefix = zero_prefix + 0;
        }
        $('#card_number').val(zero_prefix + value);
      }
      return true;
    }
  if(value.length < 10) {
    var original_length = parseInt(10) - parseInt(value.length);
    var zero_prefix = "";
    for (var i = 0; i < original_length; i++) {
       zero_prefix = zero_prefix + 0;
    }
    $('#card_number').val(zero_prefix + value);
    value = $('#card_number').val();
    if(value == '0000000000') {
      return false;
    }
  }
  },
  requirementType: 'integer',
  messages: {
    en: 'Card number cannot be all zeroes.'
  }
});
```

I have looked at #1003 and #955  as well as parsley documentation, I don't see an option to disable validation for keyup() after `ParsleyFailedOnce`.

**Comment by marcandre** [comment]
FYI, it validates on `input`, not on `keyup`. In any case, I feel that you should not modify the field being validated in a custom validator, ever. That modification should be done before validation occurs, e.g. by intercepting `keypress`, and an `input` event should be fired (like discussed in #1076).
In short, I do not consider this a bug, you should change how you are doing things (and probably use a standard masking library)

**Comment by hanxue** [comment]
Thanks for your suggestion. To clarify, I cannot configure the behaviour of Parsley after the 1st failure is detected?

**Comment by marcandre** [comment]
Exactly.

**Comment by cristiangiagante** [comment]
Hello guys, i have the same problem here and is not a input event triggered is a keyup event, im using parsley Version 2.0.7 and it can't be possible update it. It's possible to implement a workaround to override this keyup/input event attached by default by parsley? i need that my parsley errors only display when focusout is triggered but after the first one, when you put any key the validations are triggered again.

**Comment by DrewAPicture** [comment]
I concur that this feels an awful lot like a bug. Our custom validator fires an Ajax request on submit and once `ParsleyFailedOnce` is triggered, it fires off Ajax requests on every keystroke, which is a good way for somebody to DDoS our server. This is in a publicly-accessible signup form. Just as we can set the trigger for validation (or omit it and use the default behavior) we should be able to avoid validating on every keystroke even after `ParsleyFailedOnce` is triggered.

**Comment by marcandre** [comment]
@DrewAPicture Or simply use the `debounce` option.

**Comment by marcandre** [comment]
FWIW, a valuable feature request would be to support `debounce=auto` or similar, that would use 500 as value if and only if the input's validation uses promises (like `remote`). This would then be the default.

**Comment by marcandre** [comment]
Note: I edited my obsolete answer in this thread from 2 years ago...
