### ISSUE TITLE
Remote validation failing for a moment, then proceeding

### ISSUE THREAD

**Issue by koichirose** [guillaumepotier/Parsley.js#1091]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I'm not sure how to provide a working fiddle because of remote validation, but here's the closest I can get: http://jsfiddle.net/58vnaqur/9/

Using version 2.3.8.
What happens is:
- I click on submit
- I see the ajax request in Firebug
- the ajax request responds 200 OK
- right after that, I see the console info message ("validated") and, at the same time, the #errors div is displayed. The error right below the input field is not displayed, though.
- the form submits like no errors occurred

Why is it showing the #errors div even though the form is valid?
It also looks like it's waiting for the ajax request to complete before firing the validated event, unlike some other issues I've seen around.

**Comment by marcandre** [comment]
Mmm, you're calling `isValid` inside the event; that's redoing all the validations! Also, `isValid` returns `null` when there's async validations that needs to be done, which is your case (as is described in the doc).

Best to hide/show on `form:error` or `form:success`. Or check `this.validationResult` instead of calling `isValid`.

**Comment by koichirose** [comment]
Thank you, it works with `this.validationResult`.

If I may, the documentation is not very clear about this. `this.validationResult` is not documented.
I also thought that adding 'data-parsley-validate' would automatically validate the form (it does), fire the event and allow me to check the results with `isValid()` (which as you said redoes the validations instead of just checking the result). Thanks again!
