### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cr1t** [guillaumepotier/Parsley.js#1092]
Hi 

Line 1062 
           // Remove Parsley events already bound on this field
            $toBind.off('.Parsley');

Throws error Uncaught RangeError: Maximum call stack size exceeded in jquery

I'm using jquery 1.9.1 I was on 2.2 but had to downgrade for another control.

Any ideas?

**Comment by cr1t** [comment]
P S I'm on Parsley Version 2.3.7

**Comment by cr1t** [comment]
It seems similar to this 
https://github.com/guillaumepotier/Parsley.js/issues/138

but a very old issue

**Comment by marcandre** [comment]
Sorry, no idea. Can you provide a codepen or similar? Otherwise it's near impossible for me to investigate.

**Comment by cr1t** [comment]
Hi Here we go 

http://codepen.io/cr1t/pen/eZMaMB

You can see the error in the console

**Comment by marcandre** [comment]
Oh, got it, thanks!
You should be good with 2.3.11.
Thanks for the bug report :smile:

**Comment by pokaxperia** [comment]
I received this error with jquery select2 and parsley v 2.3.11

**Comment by marcandre** [comment]
@pokaxperia Sorry about this. It's an issue with `select2`, see #1028
