### ISSUE TITLE
2 tests fail

### ISSUE THREAD

**Issue by joeynimu** [guillaumepotier/Parsley.js#1095]
Hi,

When i ran the tests i get two tests failing as below;

```
122 passing (716ms)
  2 failing

  1) ParsleyForm should send submit button values, even for async validations:

      Error: expected [] to sort of equal [ 'other' ]
      + expected - actual

      -[]
      +[
      +  "other"
      +]

      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.eql (node_modules/expect.js/index.js:230:10)
      at Context.<anonymous> (test/unit/form.js:131:25)

  2)  "after each" hook for "should handle validators returning promises":
     Error: expected 1 to equal 0
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at Context.<anonymous> (test/setup/expect_warning.js:7:46)



[11:37:14] 'test' errored after 2.87 s
[11:37:14] Error in plugin 'gulp-mocha'
Message:
    2 tests failed.
```

**Comment by marcandre** [comment]
This particular test fails on Travis too. It passes on my machine, as well as in Chrome, Firefox, Safari.

I don't know why it fails on Travis and on your setup (which is?). If you do find out, let me know!

You can set the env variable 'Travis' to anything and that test will not run.

Unless someone comes up with an explanation, I will close this.

**Comment by guillaumepotier** [comment]
This could be quite problematic since users submitting PR here cannot be sure what they are submitting is failing because of Travis/env config or because of their code. Furthermore, this is more reassuring to have tests passing on Travis and viewable by everyone rather than just on one specific developper laptop.

I think this open should be re-opened and ask for help on that one with Travis experts.

**Comment by marcandre** [comment]
No problem, let's keep it open. I am just not investigating it. Might not be a travis issue per say, but some strange interraction of `simple-jsdom`, `jquery` and/or `node`.
@guillaumepotier do you know someone who's up for that challenge?

**Comment by marcandre** [comment]
Happy to report that a clean install gives the error for me too so I can now try to understand what's going on.

**Comment by benjaminpick** [comment]
The tests do not update locally (e.g. if I add failing tests), maybe this is because gulp says `gulp-notify: [Gulp notification] JSCS failed` ?

**Comment by marcandre** [comment]
Looks like a bad interaction with `jQuery` (2.2.0) and `simpleJSDom`.

I've tweaked the `package.json` file to exclude 2.2.0+ (even though it works in the browser) for now.

I'll keep open as it would be nice to isolate and report that bug to `simpleJSDom` (or `jQuery`?)

**Comment by marcandre** [comment]
Ok, no need to investigate, a more recent version of `jsdom` fixes this. It does require a more recent version of `node`, but otherwise should be all good now.

**Comment by jmeas** [comment]
@marcandre , you were using a **really** old simple-jsdom, which is why your `jsdom` version was so old.

Instead of https://github.com/guillaumepotier/Parsley.js/commit/fc2763824a2faff37a253bed2717a2c4fe234047, you could have just bumped the simple-jsdom version to 2.0.0.

```diff
- "simple-jsdom": "0.0.2",
+ "simple-jsdom": "2.0.0",
```

**Comment by benjaminpick** [comment]
@jmeas Thanks for this workaround, then I don't have to install node 0.12 ...

**Comment by marcandre** [comment]
lol, sorry, I should not have locked the version in my package.json...

**Comment by jmeas** [comment]
Heh, no worries. It's tough to keep up with the versions of everything! I release major versions to simple-jsdom whenever jsdom has breaking changes, so that folks with more lenient version specifications don't get errors for the opposite reason that this issue was erroring :P
