### ISSUE TITLE
Docs conflict with themselves

### ISSUE THREAD

**Issue by coreyward** [guillaumepotier/Parsley.js#1097]
First this:
![screen shot 2016-04-23 at 3 05 19 pm](https://cloud.githubusercontent.com/assets/81224/14763747/e216f55c-0964-11e6-94e8-643afb66437a.png)

Then this:
![screen shot 2016-04-23 at 3 05 22 pm](https://cloud.githubusercontent.com/assets/81224/14763748/ebcb5de0-0964-11e6-826d-ff40bf46b6e3.png)

Which is it?

**Comment by coreyward** [comment]
Ah, apparently I just missed the headings. The page is too busy with poor visual hierarchy. Perhaps addressing the “two ways to install” in the instructions would be useful. 

Closing.

**Comment by marcandre** [comment]
Sorry about the confusion. PRs always welcome
