### ISSUE TITLE
Only the first required radio/checkbox of a group will get the parsley-error class

### ISSUE THREAD

**Issue by benjaminpick** [guillaumepotier/Parsley.js#1098]
http://codepen.io/benjaminpick/pen/yOxJwa

I have wrapped each checkbox/radio input individually, so I would have expected to get a class for each wrap element. Instead, only the first element gets a parsley-error / parsley-success class.

Could you please add this class to each label instead? Or do I need a div around all inputs and then add a custom `data-parsley-class-handler` ?

**Comment by marcandre** [comment]
Yeah that's the way multiple inputs work. I think you indeed need a div around all inputs and then add a custom `data-parsley-class-handler`. Let me know if that doesn't work...
