### ISSUE TITLE
Custom validator only when form is submitted

### ISSUE THREAD

**Issue by ewerkema** [guillaumepotier/Parsley.js#1102]
The Parsley custom validators work great, but the validation is being called every time a key is pressed. When you for example have a login screen, you don't want to show the user whether they have typed the correct password while they are typing. Is there any workaround using the validators?

I tried a solution with using addError but this gave me the following error: "TypeError: Cannot read property 'name' of undefined". Reading the documentation didn't help me much with how to use this function. 
jQuery:
`$("#password").parsley().addError(this, "password");`
HTML: 
`<input type="password" class="form-control" id="password" name="password" placeholder="Password">`

Thank you very much!

**Comment by marcandre** [comment]
Which part of the following was not clear? Could you help me by rewording it?

> This issue tracker is not the place for questions. If you want to ask how to do something, or to understand why something isn't working the way you expect it to, use http://stackoverflow.com/questions/ask

**Comment by kevin7** [comment]
I'm having the same issue, what's the right way to use addError?
