### ISSUE TITLE
dist/i18n/fa.js contains import statement

### ISSUE THREAD

**Issue by franzos** [guillaumepotier/Parsley.js#1105]
I've found that the file for farsi internationalization causes the same issue that has already been mentioned in issue #1027. In fact, it looks like most of files contain this import statement. I get the following error: 

`Uncaught SyntaxError: Unexpected token import `

Once I remove the import statement, everything works as expected. 

```
// Validation errors messages for Parsley
import Parsley from '../parsley';
```

**Comment by marcandre** [comment]
I don't see an `import` statement in [dist/i18n/fa.js](https://github.com/guillaumepotier/Parsley.js/blob/master/dist/i18n/fa.js)
