### ISSUE TITLE
Manually Adding Errors

### ISSUE THREAD

**Issue by devmondo** [guillaumepotier/Parsley.js#111]
hi,

it would be great if there is a mechanism to add errors manually to the container without defining validator,

one case for that is that i want to get server errors and want to inject them to a desired field.

another thing is it would be great if we have error summary container, where it contains all the errors of all the fields.

a case for this is when you have multi tab form, and there are errors in each tab, we can extract errors for fields in each tab and add little notification number in each tab title.

thanks and sorry for asking to much

**Comment by fehimdervisbegovic** [comment]
With parsley 2.4.3 you can do this: 

`$('#fieldName').parsley().addError('forcederror', {message: 'My error message.', updateClass: true});`
