### ISSUE TITLE
Email with a single letter as tld (example@mail.a) passes validation.

### ISSUE THREAD

**Issue by erik127** [guillaumepotier/Parsley.js#1110]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I noticed that an email adress with one character after the last dot will be validated as true. For example example@email.a. As far as I know that should be a minimum of two? 

You can see it here: [http://codepen.io/erik127/pen/XKWWaJ?editors=101](http://codepen.io/erik127/pen/XKWWaJ?editors=101)

**Comment by marcandre** [comment]
Single letter TLDs are technically valid. We don't aim to validate that the TLD actually exist.

See also: http://stackoverflow.com/questions/7411255/is-it-possible-to-have-one-single-character-top-level-domain-name

**Comment by erik127** [comment]
Ah ok. Thanks for the quick response.
