### ISSUE TITLE
Multiple checkbox not validate when state changed from jQuery

### ISSUE THREAD

**Issue by UksusoFF** [guillaumepotier/Parsley.js#1111]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

On latest Parsley.js version multiple required checkbox not validate when state changed from jQuery.

Version 2.2.0 work as expected.

http://codepen.io/anon/pen/NrPZJB

**Comment by marcandre** [comment]
Indeed. Please read https://github.com/guillaumepotier/Parsley.js/blob/master/CHANGELOG.md#231

**Comment by marcandre** [comment]
PS: Thanks for the fiddle, much appreciated :smile:

**Comment by UksusoFF** [comment]
Thanks, it works!
