### ISSUE TITLE
formnovalidate is not always working

### ISSUE THREAD

**Issue by Stadly** [guillaumepotier/Parsley.js#1112]
The `formnovalidate` attribute of a `<button>` is not always considered.

In particular I've found that when the `<button>` does not only contain text, it does not work. For example with the button `<button formnovalidate>This works <span>This does not work</span></button>`, clicking "This works" will bypass validation, while clicking "This does not work" will validate the form. It seems that checking for `formnovalidate` is done on the element that is clicked, and not on the element that causes the form submit.

Have a look at the CodePen to try out the bug: http://codepen.io/Stadly/pen/qNZmba

**Comment by marcandre** [comment]
Thanks for the bug report and the CodePen, and sorry for the trouble. I'll fix this asap.

**Comment by Stadly** [comment]
Thanks, and thanks for a great library! :)

**Comment by marcandre** [comment]
This took longer than I had hoped for, as it uncovered a related [issue in `jsdom`](https://github.com/tmpvar/jsdom/pull/1523) :smile:

So I committed the easy fix without pushing my updated tests (they work in the browser only for now...) and released 2.3.15.

Thanks for the great bug report :tada:
