### ISSUE TITLE
Option 'errorsContainer' doesn't work

### ISSUE THREAD

**Issue by DominikSerafin** [guillaumepotier/Parsley.js#1113]
- [x] Bug report.

----

Like the title says, this option doesn't work in version > 2.3.11.
Demo: http://codepen.io/anon/pen/ZOOQPV?editors=1010

I think I tried every combination
- Using `ParsleyField.$element` with the help of closest() and find()
- Using `return $('.parsley-errors-container');`
- Using `return '.parsley-errors-container');` (like it's in demo)
- Using ID's instead of classes

And it still didn't worked.

----

The only other version that I checked was 2.0.7 and it was working there.
Demo: http://jsfiddle.net/milz/qdk73z1r/2/).

**Comment by marcandre** [comment]
Thanks for the codepen :-)

The difference is how you are providing the options. In the codepen, your input field is already initialized at that point, so the options are ignored. Just modify the options, e.g. http://codepen.io/anon/pen/jrrqre?editors=1010

We should probably be doing an `extend` with the given options in case the field is already initialized, that would be less error prone.

**Comment by DominikSerafin** [comment]
@marcandre thank you for solution! 

I think it deserves the 'enhancement' flag. Right now setting it up with `extend` is kinda confusing when you're just starting to use Parsley.

**Comment by marcandre** [comment]
Changed in 2.4.2
