### ISSUE TITLE
No changelog update since 2.3.1

### ISSUE THREAD

**Issue by Aure77** [guillaumepotier/Parsley.js#1114]
https://github.com/guillaumepotier/Parsley.js/blob/master/CHANGELOG.md seems not being updated until release version 2.3.1. How can we check last 15 release modification ?

**Comment by marcandre** [comment]
You can check the [commit list](https://github.com/guillaumepotier/Parsley.js/commits/master)... We follow [semver](http://semver.org/), so you'll find only various bugfixes. I make a new release every bug fix I make...
