### ISSUE TITLE
Symbol is undefined in ie9 with Parsley.js

### ISSUE THREAD

**Issue by SaurabhRSonawane** [guillaumepotier/Parsley.js#1116]
I am currently using **Parsley.js** in some of my websites for form validations. Its working fine in all major browsers but in **ie9** it is not validating the from. I tried to iterate through console, it is saying 

`SCRIPT5009: 'Symbol' is undefined
parsley.min.js, line 16 character 2355`

Don't know whats happening there?
I am using **jquery-2.1.1.js**, and **Parsley.js Version 2.4.2** its working fine in Chrome and FIrefox.
Please help...

**Comment by marcandre** [comment]
Sorry about this, it's using a modern feature that I can avoid (at least for now :smile:). Fixed and release. Thanks for the report.

**Comment by SaurabhRSonawane** [comment]
Thanks for this quick fix. Its working fine even on **ie9** also... It's awesome :-)
