### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by OrestisZag** [guillaumepotier/Parsley.js#1119]
Hey there, can you create Gitter so all of us can ask some of our questions there or help someone who has a question faster?

What kind of issue is this? (put 'x' between the square brackets)
- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
     something, or to understand why something isn't working the way you expect it to, use
     http://stackoverflow.com/questions/ask .
     Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
     We monitor the tag `parsley.js`.
- [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
     starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .
- [x] Feature Request. Make sure there's no good way to do what you want first;
     consider asking on http://stackoverflow.com/questions/ask first.

**Comment by marcandre** [comment]
Do you have an example of a "medium-size" project like parsley using gitter with a decent attendance?

**Comment by OrestisZag** [comment]
Hello Mr. Marc,
Basically no I do not. But I really like your project and I think that 
it is a good idea to create gitter. You may find some more features for 
your framework if you talk with people there. And then you may have more 
and more people. Of curse I do not know which are your targets. I am a 
junior programmer and i will use parsley to my thesis.

With Gratitude,
Orestis

**Comment by marcandre** [comment]
Closing, having no desire to spend even more time on support
