### ISSUE TITLE
Re-validate on change

### ISSUE THREAD

**Issue by ProgrammerZ** [guillaumepotier/Parsley.js#1123]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

When the error is triggered and then you just paste valid input, the field is not re-validated until you actually type something. May be it's not a big deal with paste, but I'm currently using bootstrap datepicker and after if pastes the valid date, the error does not go away, again until you actually enter something or submit the form.

**Comment by ProgrammerZ** [comment]
Found the answer:

$(document).ready(function() {
    $("form").parsley();

    $("#field").on('change', function() {
        $("input[name=field]").parsley().reset();

    });
});

But it's strange that it's not the default behavior.

**Comment by marcandre** [comment]
Which version of Parsley and which browser are you using?

**Comment by ProgrammerZ** [comment]
parsley v 2.4.3 from Jun 18th 2016
chrome v51, Firefox v 47, Explorer v11
all the same behavior.

**Comment by marcandre** [comment]
Oh, I just re-read your report.

There **is no bug with pasting text**, just a bug with bootstrap datepicker. It's actually a bug of the bootstrap datepicker that does not fire an `input` event even though it should.

I'm travelling at the moment, so not much time to check it out, but I'll post a PR for them when I can, if you or others don't in the meantime.

PS: Don't use `reset` or whatever, just `trigger('input')` yourself to circumvent the bug.

**Comment by ProgrammerZ** [comment]
My fault, tested today again and paste indeed does trigger validation as supposed to. Have tested yesterday many times without datepicker and it was not triggering it. Unfortunately I'm just a beginner in JS, and 90% of the code is still magic for me.  Again, sorry for bothering and have a great time.

**Comment by marcandre** [comment]
Doesn't look like bootstrap-datepicker is well maintained, with 50+ open PRs, some are [really embarrassing](https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1672). Maybe one day I'll be sponsored but until then, I'm not spending time trying to fix it and then waiting forever until it gets merged and released.

**Comment by marcandre** [comment]
I filed https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1846 if you want to subscribe to it.
