### ISSUE TITLE
Message in wrong place with multiple select  

### ISSUE THREAD

**Issue by VincentGarreau** [guillaumepotier/Parsley.js#1124]
### Parsley.js version
2.4.3

### Reproduction Link
http://codepen.io/anon/pen/EybObv

### Steps to reproduce
Submit the form (don't fill the fields).

### What is Expected?
Message for multiple select should be in the "fieldset" tag.

### What is actually happening?
Message is outside the "fieldset" tag.

**Comment by marcandre** [comment]
Sorry I haven't looked at this yet, I've been travelling for the past few weeks.

**Comment by marcandre** [comment]
Ok, fixed & released. Thanks for the great bug report & working example 🎉  !
