### ISSUE TITLE
Test suite empty

### ISSUE THREAD

**Issue by julmot** [guillaumepotier/Parsley.js#1127]
The test suite on the website is empty. Nothing will be inserted into `div#mocha`. No errors will be thrown.
![empty-tests](https://cloud.githubusercontent.com/assets/8310677/17092554/c3971fa8-5243-11e6-9a22-6f5d57d64803.png)

**Comment by marcandre** [comment]
Oups, indeed. Reinstated, even if I'm not sure how useful it is...
Thanks for reporting.
