### ISSUE TITLE
Remote validation cache bug.

### ISSUE THREAD

**Issue by bobchou** [guillaumepotier/Parsley.js#1131]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I think I found a bug about the remote validation. The scenario like this, using ajax to add a new user in database without refresh the page, and using parsley to do a remote validation to check if the username exist or not. so after I insert a user in database, seems parsleyjs will save this validation record in the  **Parsley._remoteCache** object, and this object does not reset except refreshing the page. 

Then the problem happen, even the new user already in the database, but because there is a **noConflict** record in the **Parsley._remoteCache** object, so parsley just consider this is a good username then do not send the ajax validation request to my API. For now my solution for this bug is whenever I inserted a record to my database, I will use  `Parsley._remoteCache = {};` to reset the remote cache manually. 

For your convenience, I think this bug due to the code around line 2232 in parsley.js.

**Comment by marcandre** [comment]
Parsley clears the cache when a form is submitted:
```
Parsley.on('form:submit', function () {
  Parsley._remoteCache = {};
});
```
So your scenario should not be a problem.
I'm closing this, will reopen if given a different scenario/live example.
