### ISSUE TITLE
Accessing the method 'setLocale' through ParsleyValidator is deprecated. Simply call 'window.Parsley.setLocale(...)'

### ISSUE THREAD

**Issue by 6233114** [guillaumepotier/Parsley.js#1132]
I am receiving the following error message with the latest version 2.4.4:

Accessing the method 'setLocale' through ParsleyValidator is deprecated. Simply call 'window.Parsley.setLocale(...)'

**Comment by marcandre** [comment]
Right.
I'm not sure why you think this is a bug. Moreover, it's not even an error message, it's a warning. 
Please read the message carefully, ask around if you need help understanding it.
