### ISSUE TITLE
Disabled radio buttons should not be taken into account for "required" validation

### ISSUE THREAD

**Issue by benjaminpick** [guillaumepotier/Parsley.js#1133]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

CodePen: https://codepen.io/benjaminpick/pen/zKBJXB?editors=101

Expected Behavior: In 2), because the selected radio button is disabled, the required validation should fail.

Actual Behavior: The validation does not fail, so the form would get submitted without any value (as disabled input elements are not sent to the server, thus invalidating the "required" contract). 

I'm not sure if the current behavior or my assumption is HTML5-compliant. The Spec doesn't talk about disabled elements https://html.spec.whatwg.org/multipage/forms.html#radio-button-state-(type=radio) - but it seems to be more in favor of the current parsley.js behavior. Still this is not what I expected intuitively ...

**Comment by benjaminpick** [comment]
Here is a workaround:

```js
$('form').parsley().on('field:validate', function() {
	var elem = $(this.$element);
    
    if (elem.is('input[type=radio]')) {
        elem = $(this._findRelated());
        var val = this.getValue();
        if (val) {
            var found = elem.filter(function() {
               return !this.disabled && this.value === val; 
            });
            if (found.length == 0)
                this.addConstraint('minlength', 600, 2);
            else
                this.removeConstraint('minlength');
        }
    }
});
```

**Comment by marcandre** [comment]
Oh, tricky case.

I don't know how to treat it. It's likely that our `getValue` should take into account disabled radio buttons but doesn't currently. OTOH, Chrome and Firefox don't consider the disabled state when doing the same validation.

I've [opened an issue](https://github.com/whatwg/html/issues/1795), maybe someone will have a good answer.

**Comment by marcandre** [comment]
So, while your interpretation would make sense, that's not the current behavior of browsers and the standard on that is fuzzy at best, so... that's the behavior we will continue having too.

**Comment by custa1200** [comment]
I would not think disabled would mean that it would not be validated if set to required. Is t their a novalidate attribute that should be applied to the input to change the behaviour?
