### ISSUE TITLE
Parsely 2.4.4 does not "see" change events when using custom <select> libraries like chosen

### ISSUE THREAD

**Issue by antonsutton** [guillaumepotier/Parsley.js#1134]
Parsley does not correctly validate when a select item is changed when using almost any jquery plugin or JS library that customizes `<select>` dropdowns and the onchange event is raised by the library. It seems inputevent.js library that Parsely now uses is eating this event as 'fake'

I've tested v2.0.7 vs 2.4.4 and can reproduce this bug:

V2.0.7: In the following example, https://jsfiddle.net/wph81s72/, if you change the dropdown the validation is performed on each change. For example, select a country and then change it back to "Select country..." and note that the validation message is displayed without needing to click the submit button. This is good.

In [this example jsfiddle](https://jsfiddle.net/wwtwv7j1/2/), using the latest version of Parsley, this functionality is now broken. No events are actually received by Parsley for onchange due to I think the inputevent library seeing them as fake events as they're raised by chosen.js to simulate the select element being changed.

**Comment by antonsutton** [comment]
Sorry about above formatting, for some reason whatever markdown I enter is stripped :/

**Comment by marcandre** [comment]
It's probably `chosen` that doesn't respect the spec in triggering `input` events... My `inputevent` library aims at patching old browsers, but not incomplete libraries. I could add an option somehow to be more agressive though (as triggering too many `input` events isn't as bad as not triggering any).
Let me check `chosen`'s code

**Comment by marcandre** [comment]
FYI, fix for this [has been merged in `chosen`](https://github.com/harvesthq/chosen/pull/2704), next release will be ok.

**Comment by antonsutton** [comment]
@marcandre thanks a million for the update and for the PR that you did for chosen :) 
A brief test confirms it works for us. I'll close this ticket.

**Comment by marcandre** [comment]
FYI, `chosen` 1.7.0 has been released and should address this issue.
