### ISSUE TITLE
Multiple validation messages shown

### ISSUE THREAD

**Issue by custa1200** [guillaumepotier/Parsley.js#1137]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I am getting multiple validations appearing under my controls. I thought that Parsley was only supposed to show one item unless otherwise specified to.

<img width="443" alt="screen shot 2016-10-14 at 2 24 45 pm" src="https://cloud.githubusercontent.com/assets/161224/19374800/52b3c0ea-921a-11e6-9adf-e3125d46ceca.png">

```html
<div class="form__column personal-information__form__column__username">
  <label class="input-label" for="username">Username <span class="input-label__secondary-text">(required)</span></label>
  <input id="username" class="input input--text" type="text" maxlength="64" data-parsley-maxlength="64" minlength="3" data-parsley-minlength="3" data-parsley-minlength-message="Minimum 3 characters" required="required" data-parsley-required="true" data-parsley-required-message="This is required" data-parsley-length-message="Between 3 and 64 characters" data-parsley-trigger="change" data-parsley-errors-container="#input-error__username" />
  <div id="input-error__username" class="input-error input-error__username"></div>
</div>
```

Pen can be found at http://codepen.io/custa1200/pen/Egpyyj

**Comment by marcandre** [comment]
Parsley will display more than one error if they have the same priority, which is the case here.
You have 3 constraints: `minlength`, `maxlength` and `length`, when only the later will suffice. Moreover, Parsley understands HTML5 attributes, so you only need the `minlength` and `maxlength` attributes. See here: http://codepen.io/anon/pen/EgpoaW?editors=1111
