### ISSUE TITLE
Parsley treats class="required" fields as required

### ISSUE THREAD

**Issue by danhardman** [guillaumepotier/Parsley.js#1138]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Codepen: http://codepen.io/anon/pen/BLOGkm?editors=101

`class="required"` is not the same as adding the `required` attribute on an input and shouldn't be treated as such. I've checked documentation and couldn't find any mention of using `class="required"` so I assume this is unexpected/unintentional behaviour

**Comment by marcandre** [comment]
Agreed. This has probably been there for a while, but there's no valid justification for that and no test either.
