### ISSUE TITLE
data-parsley-type="number"  can not enter float

### ISSUE THREAD

**Issue by fanyongfeng** [guillaumepotier/Parsley.js#1142]
i dont know  Wherethe mistake is；
              <input class="js-retail-price js-sku-value form-control" data-parsley-type="number" " data-parsley-required-message="必填项" required placeholder="">

I used the latest parsley.js;

**Comment by marcandre** [comment]
The mistake is not reading the doc (and not specifying `data-parsley-type-step`), but many people were confused like you so I just release v2.6.0 which changes the default.
