### ISSUE TITLE
Interpolation Angular 2 in Parsley

### ISSUE THREAD

**Issue by crissty** [guillaumepotier/Parsley.js#1143]
What kind of issue is this? (put 'x' between the square brackets)

 - [ x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hello, I have a problem with interpolation of Angular2:

I need to pass an interpolation as value of the data-parsley-error-container.

Example: 

`<div class="input-group" id="{{id}}">`
            `<input type="number" id="service" [(ngModel)]="service"                                                                                  name="service" class="form-control"                                         
                                  required="required" data-parsley-errors-container="{{id}}">`
           `<span class="input-group-addon">seconds</span>`
 `</div>`

I get the next error:

`Error: Uncaught (in promise): Template parse errors:`
`Can't bind to 'data-parsley-errors-container' since it isn't a known native property ("`
`data-parsley-min="1" 
                                         required="required" [ERROR ->] data-parsley-errors-container="{{id}}">
                                  <span class="input-gr"):`

Do you have any idea or solution?

**Comment by marcandre** [comment]
Thanks for posting it on SO. Next time, do only that. Thanks

**Comment by EitsamShahzad** [comment]
@chlegou Its also not working budy

**Comment by chlegou** [comment]
@EitsamShahzad i believe `[attr.data-parsley-errors-container]="id"` should work.
