### ISSUE TITLE
comparison validations work in only one way

### ISSUE THREAD

**Issue by jairoGilC** [guillaumepotier/Parsley.js#1144]
- [x ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

The comparison validations run only if change the input that have the validation, but if the reference input change the validation should be run again.

**Comment by jairoGilC** [comment]
I make the following implementation to validate in two way, I think that exist a better way but currently it work

    window.Parsley.addValidator('diff', {
      validateString: function (value, requirement) {
        console.log("LA VALIDACION",  parseFloat(value) , parseRequirement(requirement), parseFloat(value) === parseRequirement(requirement) )
        return parseFloat(value) != parseRequirement(requirement);
      },
      priority: 32,
      messages: {
        es: 'El campo debe ser diferente de %s'
      }
    });

    window.Parsley.addValidator('diffCallBack', {
      validateString: function (value, requirement) {
        if( parseFloat(value) != parseRequirement(requirement))
          var instance = $(requirement).parsley();
          instance.validate({force: true});

        return true
      },
      priority: 32,
      messages: {
        es: 'Not visible error message'
      }
    });

        <div .form-group >
          <div for="nit"> _{MsgNit}
          <input type=number name="nit" id="nit" data-parsley-errors-container="#nit-error" data-parsley-trigger="blur" data-parsley-validate-if-empty="true" data-parsley-required="true" data-parsley-min="999"  data-parsley-diff-call-back="#documentNumber">
          <span class="par-error" id="nit-error"></span>

        <div .form-group >
          <div for="documentNumber"> _{MsgDocumentNumber}
          <input type=number name="documentNumber" id="documentNumber" data-parsley-errors-container="#documentNumber-error" data-parsley-trigger="blur" data-parsley-validate-if-empty="true" data-parsley-required="true" data-parsley-diff="#nit" data-parsley-length="[3,10]" >
          <span class="par-error" id="documentNumber-error"></span>

**Comment by marcandre** [comment]
Closing in favor of #839 & al.
