### ISSUE TITLE
$('#my-form').parsley() // undefined is not a function

### ISSUE THREAD

**Issue by RobertBrewitz** [guillaumepotier/Parsley.js#1147]
- [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

Including the scripts this way:

`<script src="/shared/js/jquery-3.1.1.min.js"  type="text/javascript"></script>`
`<script src="/shared/js/parsley-2.6.0.min.js" type="text/javascript"></script>`

`$('my-form').parsley(); // returns undefined is not a function, "NOT OK"`

Including parsley with defer works

`<script src="/shared/js/jquery-3.1.1.min.js"  type="text/javascript"></script>`
`<script src="/shared/js/parsley-2.6.0.min.js" type="text/javascript" defer></script>`

`$('my-form').parsley(); // returns undefined, "OK"`

The logical answer to what the bug is, is that `parsley` doesn't allow `jQuery` to load before it defines the parsley prototype function.

**Comment by marcandre** [comment]
The part saying ** you must provide a minimal example in a CodePen** definitely applies here...
