### ISSUE TITLE
parsley().isValid() and parsley().validate() returns null on first check

### ISSUE THREAD

**Issue by Kunze** [guillaumepotier/Parsley.js#1148]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Every first time I call $("form").parsley.isValid() or $("form").parsley.validate(), it returns null. Afterwars it returns true or false. 

this is my code:

```
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script src="https://code.jquery.com/jquery-2.1.3.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/parsley.js/2.6.0/parsley.js"></script>
</head>

<body>
    <form method="post" enctype="multipart/form-data" data-parsley-validate="">
        <input 
            data-parsley-remote 
            data-parsley-remote-message="error." 
            data-parsley-remote-validator="slug"
            data-parsley-trigger="focusout" 
            id="Postagem_Titulo" 
            name="Postagem.Titulo" 
            required="required" 
            type="text" 
            value="response" />
    </form>

    <script>
        var parameters = {
            "type": "get",
            "dataType": "jsonp",
            "data": {
                "titulo": function() { return "response"; },
                "id": function() { return "1" },
            }
        };

        Parsley.addAsyncValidator("slug", function (xhr) {
            return 200 === xhr.status;
        }, "http://localhost:25923/admin/postagem/validate-slug", parameters);

        function response() {

        }
    </script>
</body>
</html>
```

**Comment by Kunze** [comment]
I could note it only happens with "data-parsley-remote"

**Comment by marcandre** [comment]
Yeah, that's the correct respond, as [per the documentation](http://parsleyjs.org/doc/index.html#usage-form)

**Comment by Kunze** [comment]
@marcandre
Is this correct to return null when I call .validate()? 
So, I need to call .validate() twice to know if my form is ok?

**Comment by henzeb** [comment]
For anyone still facing this problem: it indeed only happens with data-parsley-remote. one should use whenValid in such cases.
