### ISSUE TITLE
Please prevent Bootstrap's scrollspy from changing window.location.hash

### ISSUE THREAD

**Issue by vphantom** [guillaumepotier/Parsley.js#1149]
Premièrement, merci pour Parsley. :smiley:

I'd like to suggest that scrollspy be toned down in the documentation page, however.  I scroll a lot and my browser history immediately becomes unusable on that page, at least in Chrome where as I pass through each section, a new entry with a different hash location is created.  One quick scroll and I have 10+ history entries to "back" through…

**Comment by marcandre** [comment]
Right. Care to provide a PR for this?

**Comment by vphantom** [comment]
Ah, it's not scrollspy directly, but grepping revealed some custom code in `doc/assets/main.js`… Sure, I can make a diff for that.
