### ISSUE TITLE
Parsley not loading with new release (Bower)

### ISSUE THREAD

**Issue by jeffblake** [guillaumepotier/Parsley.js#1159]
<img width="621" alt="screen shot 2017-01-03 at 6 31 36 pm" src="https://cloud.githubusercontent.com/assets/620564/21630116/fd2bf454-d1e2-11e6-9e54-9696e5edc8dd.png">

<img width="809" alt="screen shot 2017-01-03 at 6 30 54 pm" src="https://cloud.githubusercontent.com/assets/620564/21630114/fa038152-d1e2-11e6-8ebe-7c58ad8550fb.png">

I thought it might be related to my Bower setup, but I removed parsley and all the other libs loaded fine.  I have no idea why global is undefined. Problem started happening with the new release

**Comment by jeffblake** [comment]
Maybe it has something to do with the addition of `use strict` ?

https://github.com/guillaumepotier/Parsley.js/commit/c030aec3a8760947978f19a50922d5be47962c09#diff-b750c004a5444e4bcb3fcbdf538fbf9bR13

**Comment by marcandre** [comment]
Mmm, I'm not sure what could have changed in my setup. I'm travelling so not much time to fiddle with this. Anyone has a quick patch so that `gulp build` does the right thing?

**Comment by markusdenhoff** [comment]
Jep, same problem with a Grunt setup here. Reverting back to 2.6.0 works fine.

**Comment by MatthiasKuehneEllerhold** [comment]
We've got the same problem. Reverting back to 2.6.0 fixed the problem.

**Comment by marcandre** [comment]
Oh, that was caused by #1079. Reverted, released. Sorry about this!

**Comment by jeffblake** [comment]
Thanks for the quick fix.
