### ISSUE TITLE
Exclude hidden fields from validation error

### ISSUE THREAD

**Issue by 168140** [guillaumepotier/Parsley.js#1160]
Documentation said that to exclude hidden fields from validation I should add this tag to form

`data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], [disabled], :hidden"`

And if works perfectly... but... validation messages disappearing after that (on visible elements) . The :hidden argument cause that.

Need assistans here. Regards

**Comment by marcandre** [comment]
Please provide a working example.

**Comment by devvrat4522** [comment]
<form id="demo-form" data-parsley-validate="" action="" method="post" name="form1" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], [disabled], :hidden">  
**Working**
