### ISSUE TITLE
Don't include/link source mapping in distribution files.

### ISSUE THREAD

**Issue by futhr** [guillaumepotier/Parsley.js#1161]
Source mapping files does not belong in distribution files see;

https://github.com/guillaumepotier/Parsley.js/blob/master/dist/parsley.js#L2387
https://github.com/guillaumepotier/Parsley.js/blob/master/dist/parsley.min.js#L18

**Comment by marcandre** [comment]
What actual problem is this causing for you?

**Comment by futhr** [comment]
It expect missing `*.js.map` files from `Parsley.js` that does not belongs in production.

**Comment by marcandre** [comment]
I'm sorry, I still don't understand what actual issue you are facing. What's "it"?

**Comment by futhr** [comment]
Its that you enforce to include the sourcemaps when using the `/dist` files otherwise it ask for `.js.map` files that does not exists, to bypass this I have to use `/src` files to manage my own build compiled with e.g. babel, but the issue was that in the project I was trying to apply this we was using quite simple gulp setup without es6 structure.

**Comment by marcandre** [comment]
AFAIK, the comment about the sourcemap has no adverse consequence in production, even if you choose not to use the sourcemap.
I personally feel that the sourcemap should be provided nevertheless, it won't be downloaded unless some developper wants to look at the source.
See also #1108

**Comment by futhr** [comment]
Thanks for the reply, for a nice repo!
