### ISSUE TITLE
Confusing `data-parsley-palindrome="3"` in example documentation

### ISSUE THREAD

**Issue by Miserlou** [guillaumepotier/Parsley.js#1166]
Small documentation quirk: 

In this example - http://parsleyjs.org/doc/examples/customvalidator.html - there is the line `data-parsley-palindrome="3"` - it seems like this is probably misplaced, and that "3" is probably copied and pasted from the "multiples of 3" example directly below it.

Tiny thing, just a little confusing!

**Comment by marcandre** [comment]
Indeed. Fixed. Thanks!
