### ISSUE TITLE
Parsley does not validate true when element is removed from Dom

### ISSUE THREAD

**Issue by devmondo** [guillaumepotier/Parsley.js#117]
hi, 

i have a delete button to remove each answer from an answers list,

now the problem is that parsley does not through errors, it just does not validate and 
 $('form').parsley('validate'); returns false.

as an extra step  i have tried  this and still  it does not work 
  `$('form :input').each(function () {
                        $('form').parsley('removeItem', $(this));
                    });`

what i have noticed is if i remove the element from Dom before calling   $('form').parsley('removeItem', $(this)); 
it does not work but if i call   $('form').parsley('removeItem', $(this)); first then remove the item from Dom it works.

shouldn't this be automatic?  i mean when an elemnt is removed from Dom shouldn't parsley stop validating it ?

thanks in advanced.

**Comment by shannonhochkins** [comment]
I think that's a little backwards, I don't think it should matter if the field is in the dom or not, if you're removing validation it should just honor it, triggering validation errors for elements/fields that no longer exists is very wrong!

**Comment by marcandre** [comment]
Unless I'm mistaken, if you remove an `<input>` from the DOM, parsley will not validate it anymore. This issue is *very* old and I think refer to v1. If this is still an issue, please open a new issue and provide a CodePen :smile:
