### ISSUE TITLE
Alpha dash validation

### ISSUE THREAD

**Issue by the94air** [guillaumepotier/Parsley.js#1174]
I trying to make a custom validation to only allow alpha and dashed values, i can't find in way doing that. Any help??

**Comment by the94air** [comment]
:-1:

**Comment by marcandre** [comment]
Thanks for opening your question on SO.

**Comment by the94air** [comment]
Sorry, I was so angry because i was king of on a hurry
```javascript
window.Parsley.addValidator('alphadash', {
	validateString: function(value) {
		return true == (/^[a-z-_]+$/.test(value));
	},
	messages: {
		en: 'Only alphabetic letters, dashes and underscores allowed.'
	}
});
```

**Comment by marcandre** [comment]
I meant it. Questions on StackOverflow, thanks.
