### ISSUE TITLE
Chrome browser freezes when validating 800 inputs

### ISSUE THREAD

**Issue by cheneesam** [guillaumepotier/Parsley.js#1178]
Having a unresponsive browser, validating a form validate in 800+ inputs. tried to group validate 200+ inputs still having a browser freezing. btw my version is up to date 2.6.2.

Do you guys experience this too?

**Comment by marcandre** [comment]
Pro tip: always provide a working example. Doing so shows you value contributors' time.

[This simple example](http://codepen.io/anon/pen/LWGbrY?editors=1010) for 800 inputs gives me ~200ms for binding and ~400ms for validating on my 8 year old mac pro, in Chrome.

**Comment by cheneesam** [comment]
Noted. Alright thanks! did some work around on :

> Parsley.options.excluded 
and 
> Parsley.options.inputs
