### ISSUE TITLE
'input' and 'keyup' trigger will just work after the content's length is more than 4.....

### ISSUE THREAD

**Issue by LeonDWong** [guillaumepotier/Parsley.js#1179]
Here's my code.
```
<textarea class="form-control" id="desc-textarea" data-parsley-trigger="input" data-parsley-required="true"></textarea>
```

And the check only works once i input more than 4 characters.If it works,it will check the content no matter how long the content's length is(it's right).But if i input less than 4 characters at very beginning, parsley will never work.

parsley version: 2.6.5

**Comment by marcandre** [comment]
That's a deliberate choice that can be modified, see the "Validation threshold" setting.
