### ISSUE TITLE
jQuery v3.1.1 , multistep form and remote validator issue

### ISSUE THREAD

**Issue by ankurk91** [guillaumepotier/Parsley.js#1182]
What kind of issue is this? (put 'x' between the square brackets)

 - [x] Bug report. 

Take a look at this plunker -
https://embed.plnkr.co/p5ShI5ZGAX60FCsHcBX3/

Using jQuery **v3.1.1**

I created a multi-step form using the example given [here](
http://parsleyjs.org/doc/examples/multisteps.html)

I added a remote validator to an input field, remote validator works well.
But clicking on next button does nothing even if field is valid. 

The form works well when using jQuery v2.2.4.
I believe it has something to do with ```$.Deferred()```

**Comment by marcandre** [comment]
Thank you for the detailed bug report and the working example. I am able to reproduce it and will look into it.

**Comment by marcandre** [comment]
So my first observation is that you are using `validate` with a async validations. `validate` will return `null` in case a validation is async, which is not what you want. You need to use `whenValidate` instead.
I'm still unsure as to why there's a difference between jQuery 2 and 3 though.

**Comment by marcandre** [comment]
Looks to be due to the result of your remote request: `["status": true]` is not valid JSON. jQuery 3.x composes promises a bit differently.

**Comment by ankurk91** [comment]
**whenValidate** method worked well. It was not invalid JSON problem.

```js
$('.demo-form').parsley().whenValidate({group: 'block-' + curIndex()}).then(function () {
  console.log('section is valid, moved to next');
  navigateTo(curIndex() + 1);
}).catch(function (e) {
  console.log('section is not valid')
});
```
Thanks
