### ISSUE TITLE
Form submit twice, two submit events when remote validator

### ISSUE THREAD

**Issue by ankurk91** [guillaumepotier/Parsley.js#1184]
- [x] Bug report. see [plunker](https://embed.plnkr.co/HsN9oq1k2Kpibz16ZDES/)

* Parsley.js v2.7.0
* jQuery v3.2.1 
* Chrome v57.0.2987.98 (64-bit)

**Description**
I am facing an strange issue, i want to submit form via AJAX, but my form submitted twice.
I can see two different submit events attached on form. (see screenshots or see plunker)
* One is from [parsley.js](https://github.com/guillaumepotier/Parsley.js/blob/3703d3c6d9c07dec2a0ebcaed6f15209415b26dd/src/parsley/form.js#L21)
* Second is from mine own js

The culprit is remote validator, when i remove it, form submit only once.

![screenshot from 2017-03-25 11-41-07](https://cloud.githubusercontent.com/assets/6111524/24329253/6d700432-121e-11e7-99a1-6bee0069febe.png)
![screenshot from 2017-03-25 11-28-52](https://cloud.githubusercontent.com/assets/6111524/24329254/6f918e16-121e-11e7-83d9-d5761b8368d7.png)

Any way to prevent parsley.js submit event ? What i am doing wrong ?

**Comment by marcandre** [comment]
Probably you are should be checking to see if the submit event you are handling already has it's default prevented (by Parsley). If the default is prevented, don't send your ajax request.

**Comment by ankurk91** [comment]
I found a way to prevent event triggered by code.

```js
$form.on('submit', function (e) {
  e.preventDefault();
  e.stopPropagation();
 if (typeof e.originalEvent === 'undefined' || e.isTrigger) {
    console.log('Prevent duplicate events');
    return false;
  }
  console.log('onSubmitClick');
  // Don't let form submit if form is not valid
  isCurrentIndexValid().then(function (e) {
    // do ajax here
  }).catch(function () {
    return false;
  });

});
```
