### ISSUE TITLE
changing data-parsley-pattern doesn't work

### ISSUE THREAD

**Issue by LeviWangJS** [guillaumepotier/Parsley.js#1188]
after changing data-parsley-pattern of a field,the field always shows that its validate result is error, even destroy the form before changing the attribute and init after that.

ps: the other attribute such as ' required' worked  

code: 
$('#login-form').parsley().destroy();
$('#login-by').attr('data-parsley-pattern','/^(13|14|15|17|18)\d{9}$/g');
$('#login-form').parsley();

**Comment by marcandre** [comment]
No need for `destroy`.
Closing until a working example is provided.
