### ISSUE TITLE
Parsley and clone(true) problem.

### ISSUE THREAD

**Issue by lazosweb** [guillaumepotier/Parsley.js#1189]
https://www.youtube.com/watch?v=2N6nZW1NH1M

Hi. I am trying to validate a cloned select field but it does not work.
You can see from the video that it works on the first element but it does not work on the clone when I click apply to re validate the form.

If I change the clone from true to false it works. Is that the way it should work?

**Comment by marcandre** [comment]
Parsley uses data to store it's information, so if you clone it with data, after it's been bound, then yes, you're bound into running into problems. Probably calling `destroy` before the `clone(true)` will resolve your issue.
