### ISSUE TITLE
Form:error firing multiple times when there are multiple forms in a page

### ISSUE THREAD

**Issue by careerfaqs** [guillaumepotier/Parsley.js#1193]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/bishwadeepkc/pen/QvNQBz .
![error_details](https://cloud.githubusercontent.com/assets/5218904/25259361/f81d6376-2688-11e7-85d7-cb099097fbe0.png) 
Does not happen with first form, then every form you open the error increases by 1
Live example can be found here: http://studyselect.com.au/course-providers/la-trobe-university/

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by careerfaqs** [comment]
I have list of courses in a page with forms loading in popup. I have a function that sends events to Google analytics whenever there are validation errors. I have used the following function to push the event to GA.
`window.Parsley.on('form:error', function(){
    console.log('Category: Send enquiry | Action: Validation error | Label: provider la trobe university');
});`

It runs ok when I open the first form, it sends the event to GA only once. However, whenever I open other forms and try to submit an empty form , the "form:error" is firing multiple times. Infact, the event multiplies with the form. Please let me know if you need more information.

**Comment by marcandre** [comment]
Is it possible that you are calling `window.Parsley.on` for each form? This registers an event handler globally! You probably want to either call it once, or else call `$('.a-form').on(...)` which registers it for a single form.

**Comment by careerfaqs** [comment]
Thank you for the quick reply. I will try your suggestion and let you know if there is any problem.

**Comment by marcandre** [comment]
Closing, will be reopened if need be.
