### ISSUE TITLE
Parsley Remote Validator with Visualforce (front-end component of Salesforce)

### ISSUE THREAD

**Issue by KyleAtDND** [guillaumepotier/Parsley.js#1194]
- [x] Bug report. Here is the [Codepen](http://codepen.io/3rdMillWeb/pen/EmyPRe)

We are using Parsley as a front-end validator for VisualForce (VF), a front-end component of Salesforce (SF). However, when we use the remote validation, the `xhr` in the custom validator does not include the response. The `xhr` will have the basic object fields such as `xhr.complete`, `xhr.success`, etc, but it doesn't not include `xhr.responseJSON` (it is undefined).

However, the ajax does actually happen, in the Network Console, I see the request and the response. In this scenario, the response was `jQuery19109962961296071557_1492809324867({"message": "Routing numbers are 9 digits", "code": 400, "rn": "321321"});`. And of course the problem is that that was no where to be found in the Parsley remote validator itself.

I have used this remove validator in other places without a problem (as you can see in the [Codepen](http://codepen.io/3rdMillWeb/pen/EmyPRe)).

So it would take a bit of work to setup a developer section of SF to get this where others can fully test it out and such. I can do that if need be, but I wanted to first see if this was something that is a) feasible to fix and debug and b) in the scope of Parsley bug fixes

**Comment by marcandre** [comment]
Parsley simply calls `xhr = $.ajax(options)` and passes that `xhr` to the async validator. I'm not too sure what I can do to help.

Now that Parsley handles promises natively, you could try and write your own custom validator (not remote validator) and fire the ajax request yourself, chain it with `then` and return that? Should give the same results, but might help you understand better what's going on...

**Comment by KyleAtDND** [comment]
@marcandre Thanks! Would the best place to see how to do that, just be the way in which Parsley handles remote validation in the source code?

**Comment by marcandre** [comment]
The [custom validator](http://parsleyjs.org/doc/examples/customvalidator.html) example doesn't quite show that, but instead of returning `true/false` they could return a promise. HTH

**Comment by marcandre** [comment]
I added [an example](http://parsleyjs.org/doc/examples/ajax.html) which I hope can be instructive. It returns a dynamic error message too.

**Comment by KyleAtDND** [comment]
Thank you sir @marcandre ! Very helpful. I'm packed with finishing up with a contractor right now, but afterwards, I'll test this out. The more I've done, the more I'm actually starting to think it might have more to do with a problem/configuration error of Ajax calls in VisualForce in general and not anything to do with Parsley. In either scenario, I'll give an update. I'm sure there is a way.
