### ISSUE TITLE
Allow disabling step attribute validation

### ISSUE THREAD

**Issue by MicahBrown** [guillaumepotier/Parsley.js#1195]
What kind of issue is this? (put 'x' between the square brackets)
 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I have a `type="number"` input that has a `step="25"` attribute set. I set the step for the increment and decrement buttons that show up on some browsers, but I want to allow the user to still enter values outside the step bounds. Since the step attribute is set, the validation prevents the user from entering such values.

**Comment by marcandre** [comment]
I'm afraid I have to deny your request, as it goes against HTML5 spec. Try it in any browser without Parsley, even if the user types in another value, it will not be accepted.

You may want to put your own buttons to increase/decrease by 25 next to the input instead...
