### ISSUE TITLE
Replace $.isArray with Array.isArray

### ISSUE THREAD

**Issue by Bruce17** [guillaumepotier/Parsley.js#1199]
- [x] Bug report.
 - [x] Feature Request.

Hi,
I'm using a custom build version of jQuery without the deprecated methods and was wondering, why Parsley is not working. It throws an error: `TypeError: $.isArray is not a function`. It seems that parsley uses `$.isArray` which is marked as deprecated (see https://github.com/jquery/jquery/issues/2961).

Replacing `$.isArray` with `Array.isArray` and providing a fallback if `Array.isArray` does not exist should solve this issue.

Tested with parsley v2.7.1

**Comment by marcandre** [comment]
Indeed. Replaced.

IE8 users should already be loading the ES5 shim as per our doc.
