### ISSUE TITLE
Silent Validation

### ISSUE THREAD

**Issue by olek-ursta-goemerchant** [guillaumepotier/Parsley.js#1200]
Parsley require silent validation. With silent validation I mean parsley validating form/group/fields, affecting UI (adding appropriate validation css classes) but not showing error messages.

Why this is needed:

1. Form has default fields. When $('#form').parsley() is executed it created parsley with initial states for fields. Default fields are show as invalid even if they are valid. Running $('#form').validate() will show error messages for all invalid fields. Considering it is form initialization I don't want error messages to be show. They have to be shown only when user modifies/submit the form.

2. Form has dynamic fields that are being added to the DOM base on the values of other fields. To add them to parsley one need to run $('#form').parsley() and $('#form').parsley().reset(). But $(#form).parsley().reset() will make all valid fields as invalid. Running $('#form').parsley().validate() will show errors for all invalid fields as in previous scenario when you don't need it.

By implementing silent validation this problem with error messages on form initialization and adding dynamic fields will be solved.

I suggest to add 3 new options to parsley() constructor: reset, validate, silent. All 3 should be "true" by default.

If reset = true for existing form it will reset it and there is no need to run $(#form).parsley().reset() after $('#form').parsley() when new fields were added to DOM.

If validate = true it will validate the form after initial parsley initialization. Also as in first case save one line $('#form').parsley().validate() when adding dynamic fields to the DOM.

If silent = true, it will prevent error messages being show, making it ideal for initial form validation if it has default values or dynamic fields added to the form.

Also I suggest adding "silent" as an options to "validate" method. Ex: $('#form').parsley().validate({ silent: true });

**Comment by marcandre** [comment]
Thanks for your feature request.

Unfortunately, I'm not really convinced of the need. You could easily toggle a class "hiden-error-messages" yourself and use that to hide error messages yourself with CSS.

FWIW, I am unaware of need to use `reset`.

**Comment by olek-ursta-goemerchant** [comment]
Thanks for you reply.

I don't see "hidden-error-messages" in the documentation thus not sure how it works and how I can use it to solve issues described above.

If you do not call "reset" after field was dynamically added to the form's DOM, $('#form').parsley() would add those fields to validation, but validation won't be triggered on trigger event until you trigger validation programmatically or by modifying one of the fields that were present on the form from when it was first initialized.

I can try making some example code if that would help show what I mean. Let me know if you need one.

**Comment by marcandre** [comment]
You can toggle yourself a class `"hidden-error-messages"` or whatever you like and add some CSS rules. Parsley doesn't do that for you.

After adding dynamically an input, you can simply call `$('.your-new-input').parsley()` to force initialization, for example if it has a `trigger` option that makes it validate immediately. Otherwise everything will work fine.

**Comment by olek-ursta-goemerchant** [comment]
Creating css class and toggle it myself all the time will turn validation into manual work every time something changes in the form. This defeats the whole purpose of using parsley. 

If I make a css class that I will toggle on initial parsley call with initial validation will suppress all error messages when user modifies any of the fields on the form. This will force me to manually track changes to any field and remove that css class for the field being modified. Simply, I would have to do almost everything myself instead of parsley doing it.

The same for running $('#field').parsley() for every field that was added to the form. Plus, when field is being added to the DOM, and then being removed from the DOM, base on the value/values in other fields, one would have to check all the time if the actual field is in the DOM or not, and add/remove parsley for that field. Running $('#form').parsley() should do the job of updating all parsley validation on the given form, as well as validating it the first time without showing errors.

**Comment by marcandre** [comment]
I was thinking: add `hidden-errors` to the form on init. Call `validate()` if you want. Remove the class `on('submit')`. Add a CSS rule to hide error messages for `form.hidden-errors`.

Removing inputs: there's nothing special to be done.

Classes on init: do you want the valid classes to show, the invalid classes to show, or both? The valid classes could be acceptable, but having the invalid classes show without the error messages seems like a bad idea.

Having `$('#form').parsley()` rebind all inputs is a good idea though.

**Comment by olek-ursta-goemerchant** [comment]
I created sample code on jsfiddle - https://jsfiddle.net/ny526xaw/42/

I hope this will shed some light on what is the form, how it works, and how parsley is used in it. See if you can apply "hidden-errors" class solution on it.

Classes on init: all, valid and invalid classes. I don't agree that invalid are bad idea. There may be stylesheet classes applied to invalid classes that you would want to be applied to fields if they are not valid. 

$('#form').parsley() rebind all inputs should eliminate the need to reset and re-validate fields, but silent validation is still needed to validate form when creating parsley the first time.

In all parsley is doing a great job. All it's missing for me is an option to manually validate fields without showing errors only when required, but at the same time work as normal and show errors. As I explained in my initial comment, I need fields to be validated and errors to be show as normal when field value is changed, but validate the form without showing error messages only when form validation is being initialized or updated. 

Sorry if this sounds confusing. Sample on jsfiddle I believe would make everything clear to you.

**Comment by olek-ursta-goemerchant** [comment]
It looks like it pointless expecting somebody do something...
