### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by c0fe** [guillaumepotier/Parsley.js#1203]
I posted on here a few questions, ticket closed and told to post question on stackoverflow. Reposted question on stackoverflow, down voted into oblivion no answer. So I will try here again.

Does Parsley support Recaptcha Version 2 and is there any PHP file examples for a contact form?

**Comment by marcandre** [comment]
If you don't get the help you'd like on StackOverflow, I'd recommend you use paid support, say hack.hands or similar.

**Comment by c0fe** [comment]
So Parsley.JS dev team doesn't answer question. Wonderful

**Comment by marcandre** [comment]
lol!
This is open source. There is no "parsley.js dev team". I'm the only active maintainer and I am not sponsored or paid for the time I volunteer to the project.

**Comment by c0fe** [comment]
Or so active maintainers/volunteers/etc then don't answer questions regarding the project.

**Comment by guillaumepotier** [comment]
Hi @c0fe je short answer is no. Parsley does not support recaptcha natively. And as JS maintainers we have even less PHP code to share to you. Sorry for that. If you do not have any luck with your Stackoverflow have you considered adding a bounty ? Or paying for support (not here obviously)

**Comment by c0fe** [comment]
Hello @guillaumepotier I appreciate your answer, I not against paying for premium support I just never figured a question whether or not a project supports a particular feature and/or is there any additional documentation really would be so complex as to warrant paid support. Your answer is the one I was looking to questions and I no longer any more. Thanks again.
