### ISSUE TITLE
Custom Validator which is invalid, form still says it's valid

### ISSUE THREAD

**Issue by janwidmer** [guillaumepotier/Parsley.js#1204]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I have successfully implemented a custom Validator using a jquery deferred, which makes an ajax call to my backend to validate a date of birth.

Since my form is within an overlay, I can not use a normal submit button within the form, but instead, I am having a click event listener on a button outside the form. The Form field itself has a "focusout" listener to do the field validation, which works correctly. The ajax call goes to the backend, comes back with the state "invalid". So far, so good, the error message gets displayed correctly.

Now, when I click on my button to start the action, parsley says, the form is valid, even though, the promise of the custom validator was rejected on the field.

Please find the case in the following code pen: https://codepen.io/janwidmer/pen/JNaaQo
(Sorry that  I have not used your minimal example, since my case is kinda specific..

To Reproduce the error, you can do the following steps:

1. Enter a date in the format "DD.MM.YYYY"
2. Click somewher outside the field to activate the focusout validation
3. An ajax call get's started. 
4. Since the URL of the call gives a 404, the Promise gets rejected and therefore the field is invalid
5. Click on the submit button
6. The parsley instance still says, that the form is valid

Am I doing something wrong or not, how it is supposed to use?
Any Inputs are greatly appreciated.

**Comment by marcandre** [comment]
Thank you so much for the bug report and the live example, it's greatly appreciated.

As indicated in the doc, `validate()` returns `null` when any validation involves a promise (as it can't determine validatity at that moment). You are checking for `!== false`. Use `whenValidate` instead.

Pro tip (not related): don't create a new Deferred unless you absolutely have to. Instead chain existing ones (e.g. return of `$.ajax`) with `then` or similar.

Good luck

**Comment by janwidmer** [comment]
Hey Marc,
Thanks a lot for the heads up, I overlooked the hint about Promises being involved.. Now it works.
Best Jan
