### ISSUE TITLE
[Bug report] incorrect e-mail formats as valid e-mail address

### ISSUE THREAD

**Issue by PawelGIX** [guillaumepotier/Parsley.js#1207]
Validation passed incorrect e-mail formats.

Number on begins: 12ssad@aaa.com
Underline on start _fsafds@wp.com
Unacceptable national marks: ąśółżźćń@wp.pl on "login" fragment

**Comment by marcandre** [comment]
I believe you might be mistaken and these are [all correct emails](https://en.wikipedia.org/wiki/Email_address#Local-part). If this is incorrect, please point out the relevant section of RFC 5321, 5322 and 6531 and I'll reopen this.
Thanks
