### ISSUE TITLE
Malformed email address is passed by email validator

### ISSUE THREAD

**Issue by glapa** [guillaumepotier/Parsley.js#1209]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hi.
I just found out that parsley allow to input malformed emails like **email@test.tt..com**.

**Comment by thomasuebel** [comment]
It also validates email addresses like "thöralv@localhost.com" or "märtürium@localhost.com" - i.e. German Umlauts (ä,ö,ü,ß) and special chars (é, á, à) pass the validation.

**Comment by marcandre** [comment]
@glapa: Sorry for the bug, indeed "email@test.tt..com" should not be accepted.

@thomasuebel: Special characters are acceptable as emails, please comment in #1207

**Comment by marcandre** [comment]
Should be fixed by f42e164. Thanks for reporting this!
