### ISSUE TITLE
Date validation in IE

### ISSUE THREAD

**Issue by Stadly** [guillaumepotier/Parsley.js#1211]
What kind of issue is this? (put 'x' between the square brackets)

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

Open this [CodePen](https://codepen.io/Stadly/pen/QgbzNe) in Internet Explorer. When you click submit, the error "This value should be lower than or equal to 2179-06-06." is shown, even though the value "2018-05-10" is lower than "2179-06-06". It works in other browsers, such as Edge and Google Chrome.

I'm using Internet Explorer version 11.1198.14393.0.

**Comment by diegocastro** [comment]
The same error occurs on firefox as well.

**Comment by marcandre** [comment]
Thanks @Stadly & @diegocastro 
I haven't had the time to check it out yet, travelling and stuff. PR welcome of course.

**Comment by breizoreol** [comment]
Hello, here is my attempt at fixing this bug:

https://github.com/guillaumepotier/Parsley.js/pull/1214

I put the fix in a commit and the newly generated build in another one, not sure if that's what is expected (this is my first contribution to an open source project).

**Comment by Stadly** [comment]
Ping :)

**Comment by marcandre** [comment]
Should be fixed in 2.8.0. Thanks to all for your contributions!
