### ISSUE TITLE
SELECT required passes when empty option is selected

### ISSUE THREAD

**Issue by alvipeo** [guillaumepotier/Parsley.js#1213]
I have a form with the following SELECT:

```
<select id="myid" data-parsley-required="true" name="fieldname">
<option>-- Please select one --</option>
<option value="0">All are empty</option>
<option value="1t">1 real thing</option>
<option value="2tt">2 real things</option>
<option value="1e">1 empty</option>
<option value="2ee">2 empty</option>
</select>

```
and when I do `parsleyForm.validate()` I get all valid! Why???
All other fields work.

The only possible way of making it work was to add `data-parsley-min="1"`. And not the error message says **"This value should be greater than or equal to 1."** which is completely irrelevant in my case. Becides, what if my select contains non-numeric values?

Addition: I have a simple SELECT for States (this is from Chrome dev tools - after it's validated):
```
<select data-parsley-required="true" class="form-control parsley-success" data-parsley-min-value="AL" id="someid" name="somename" data-parsley-id="50">
<option>-- Please select one --</option>
<option value="AL">Alabama</option>
<option value="AK">Alaska</option>
<option value="AZ">Arizona</option>
<option value="AR">Arkansas</option>
<option value="CA">California</option>
...
</select>
```
Why is it **parsley-success** here? As you may see `data-parsley-min-value` doesn't work here. So how do I do this?

PS. I tried 2.7.1 and 2.7.2 - same thing.

**Comment by marcandre** [comment]
You need to [disable that option](https://stackoverflow.com/questions/22033922/how-to-show-disable-html-select-option-in-by-default)
