### ISSUE TITLE
Multiple email is not supported for parsley-pattern

### ISSUE THREAD

**Issue by theromie** [guillaumepotier/Parsley.js#1217]
I am trying to accept pattern for multiple email separated by comma but parsley-pattern is not working
`<input class="uk-input dirtyInput" id="invite_email" type="email" data-parsley-pattern="^((\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)\s*[,]{0,1}\s*)+$" data-parsley-error-message="enter email" required="" multiple="">`

**Comment by marcandre** [comment]
Indeed :-(

Closing in favor of #885
