### ISSUE TITLE
Accessing UI is deprecated. Call 'getErrorsMessages' on the instance directly.

### ISSUE THREAD

**Issue by weilinzung** [guillaumepotier/Parsley.js#1222]
After I updated to `2.7.2` it displays this message `Accessing UI is deprecated. Call 'getErrorsMessages' on the instance directly.` how can I fix it?

this is my code:
`ParsleyUI.getErrorsMessages(Instance)`

**Comment by marcandre** [comment]
`Instance.getErrorMessages`...
Future questions on StackOverflow please.

**Comment by weilinzung** [comment]
this may helps: https://stackoverflow.com/questions/23008008/display-parsley-errors-in-bootstrap-tooltip

**Comment by weilinzung** [comment]
change `ParsleyUI.getErrorsMessages(Instance)`to `Instance.getErrorsMessages();` could works, too!
