### ISSUE TITLE
[Discussion] [Support needed] Using parsley on a `jq-steps` wizard form 

### ISSUE THREAD

**Issue by hellboy81** [guillaumepotier/Parsley.js#1223]
Due on [SO question](https://stackoverflow.com/q/17180175/444079) I am looking the best working solution to integrate validation library (`Parsley`, `formvalidation`, `jquery-validate`)  with `jquery-steps`.

See also: [this question](https://github.com/rstaib/jquery-steps/issues/238)

**Comment by marcandre** [comment]
I posted an [answer on SO](https://stackoverflow.com/questions/17180175/using-parsley-on-a-wizard-form-3-steps/46055160#46055160). If this is not sufficient for you, please ask a new question on SO, not here.
