### ISSUE TITLE
Deprecate jQuery.parseJSON

### ISSUE THREAD

**Issue by rahulthewall** [guillaumepotier/Parsley.js#1225]
The website that we are using Parsley.js currently runs on jQuery-2.2.4 and we are in the process of upgrading to jQuery-3.2.1. However, when running jQuery-migrate, we see the following issue:

```
JQMIGRATE: jQuery.parseJSON is deprecated; use JSON.parse
```

As you can see, the issue comes from the following piece of code in dist/parsley.js. 

```
    /** Third party functions **/
    // Zepto deserialize function
    deserializeValue: function deserializeValue(value) {
      var num;

      try {
        return value ? value == "true" || (value == "false" ? false : value == "null" ? null : !isNaN(num = Number(value)) ? num : /^[\[\{]/.test(value) ? $.parseJSON(value) : value) : value;
      } catch (e) {
        return value;
      }
}
```

Could you please update this code?

**Comment by marcandre** [comment]
Indeed. Done, thanks!
