### ISSUE TITLE
SonarQube security scan compliance

### ISSUE THREAD

**Issue by jillsaintcyr** [guillaumepotier/Parsley.js#1230]
Please consider implementing minor reformatting of code in the library in order to pass the standard, default security scan rules of SonarQube: https://docs.sonarqube.org/display/SONAR/Documentation

**Comment by marcandre** [comment]
I'm not sure what this entails, but I definitely do not have the time to read that documentation... Care to elaborate / make a PR?

**Comment by jillsaintcyr** [comment]
Thank you - I admit I didn’t expect you to review so soon! Sonar is a very common static code analysis tool which can be free or paid. Based on some issues flagged by the tool, I and others may not be able to use this library on certain client business. Most issues are regarding minor formatting issues. I’ll plan to try to submit a PR myself, but I thought I’d register interest in the meantime to see if others had the same request. Thanks again for your attention!
