### ISSUE TITLE
Concise constraint notation

### ISSUE THREAD

**Issue by SteveTheTechie** [guillaumepotier/Parsley.js#1233]
While I am sure that there are people who appreciate the verbosity of the data attributes for specifying validation constraints, I tend to identify more with the "less is more" crowd.

For example if I look at the Custom Validators example in the docs, I see the following in the HTML:
`<input name="zip" required="" data-parsley-type="digits" data-parsley-length="[5,5]" data-parsley-zip="us">`

When I look at this, I tend to wonder why there could not just be an additional, alternative, more concise notation, with delimiters similar to that used for inline CSS:
`<input name="zip" data-parsley-concise="required;type:digits;length:[5,5];zip:us">`

This would certainly cut down on bytes in the HTML used for specifying validation constraints.

Now I would be just fine with creating a custom validator for this notation.  However, it begs the question of whether a custom validator could invoke any of the built in or other custom validators after parsing the above concise notation into the individual constraints.  Without spending the time to scrutinize all the underlying code to determine this, I am not certain of whether it would be worth an attempt to create a custom validator that would take the above notation, parse it, and successfully hand it off to other validators.  (The first two I know I can do; the last step is the big question mark for me.)  Is that type of "interplay" between custom validators even possible with how the Parsley.js code is structured?

**Comment by marcandre** [comment]
To answer the question: all the `data-parsley` attributes are parsed into the `options` object of the parsley instance.

FWIW, some web frameworks will output the attributes from a concise source. For example in Rails:
`<%= f.input :zip, data: {parsley: {type: :digits, length: [5,5], zip: :us}}%>` and can even deduce the `required` attribute, for example.

HTH

**Comment by SteveTheTechie** [comment]
Thanks.  I did consider just doing some sort of parse and create the appropriate individual data-parsley attributes. However, I thought doing this as a custom validator would probably force me to get familiar w/ the underlying Parsley.js code. (I am a Parsley.js newbie.)

**Comment by marcandre** [comment]
Well, there's no callback for custom validators except when it's time to validate, at which time it would be too late, especially for the 'required'.

You'd have to highjack the `actualizeOptions` method somehow. I'm not sure I can recommend this.

What you might want to consider is using some other attribute, say `data-validate`, and produce the long form `data-parsley` attributes with your code.

Good luck.
In the meantime, I'll be closing this as I don't see what should be done for the library
