### ISSUE TITLE
Webpack error: Unexpected token: punc (.)

### ISSUE THREAD

**Issue by florianflock** [guillaumepotier/Parsley.js#1237]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

----

I am getting an error when my webpack is compiling and concetinating a parsley.

I require
```javascript
require('parsleyjs');
require('parsleyjs/src/i18n/de');
```

and on compiling and uglifying I get this error:

```
ERROR in js/script.js from UglifyJs
Unexpected token: punc (.) [js/script.js:10422,26]
```

which points to this line of code:
![image](https://user-images.githubusercontent.com/3831745/34454906-fd12efc8-ed74-11e7-82b6-9915c7e3f0f6.png)

Can anyone help me? :-)

**Comment by marcandre** [comment]
You need `dist/parsley.js`, not `src/parsley.js`. The later is in ES6, which is why you are getting an error.
