### ISSUE TITLE
Extreme lag when an email is surrounded by double quotes

### ISSUE THREAD

**Issue by xposedbones** [guillaumepotier/Parsley.js#1240]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

======================================================================

There is extreme lag when entering an email that has a . in it and is surrounded by " ", you can try it out here http://parsleyjs.org/doc/examples/simple.html

Steps to reproduce:
paste "test.hello@test.com" in the email field and focus out. The bugs seems related to the email validator.

Note: 
"abc@def.com" => No lag
"abc.d@asd.com" => Almost no lag
"mathieu.math@thisisatest.com" => ~3 sec lag
"abc.asdasdasdasdasdasd@asd.com" => This will likely crash your browser

**Comment by marcandre** [comment]
I can't reproduce the lag on Chrome Version 64.0.3282.119 (OS X).

Which browser and OS are you seeing this?

**Comment by xposedbones** [comment]
Chrome 64.0.3282.119 (Official Build) (64-bit) (OSX), I can also reproduce it consistently on Firefox and Opera. 

Go there: 
http://parsleyjs.org/doc/examples/simple.html

copy "as.asdasdasdasdasdasdasda@as.com" and press Tab.

**Comment by marcandre** [comment]
Oh, I see, I didn't include the quotes, sorry.

**Comment by xposedbones** [comment]
yup, having the double quote is the problem, which can happen if a user copy & paste an email address. I just tested and the '.' is unrelated, I can have a browser crash just by entering "adadasdasdasdasdasdasdadasdasdadasdasdasd@asd.com" and pressing tab

**Comment by marcandre** [comment]
Got it. It's the `/.../i` flag, with the wide character ranges, that is causing the issue. Easy fix too :-)

**Comment by marcandre** [comment]
Will release soon.
Thanks again for the bug report!

**Comment by xposedbones** [comment]
Parfait Merci! T'es à Montreal, j'ai le goût de te payer une biere!

**Comment by marcandre** [comment]
Avec plaisir. Contacte moi par courriel (voir dans mon profil)
