### ISSUE TITLE
Set Locale problem for zh_cn and zh_tw

### ISSUE THREAD

**Issue by alucard001** [guillaumepotier/Parsley.js#1248]
In your `Parsley.js/dist/i18n/`, there is a language loading problem for zh_cn.js and zh_tw.js.

Inside zh_tw.js, you are running `Parsley.setLocale('zh-tw');`, which did not match the file name zh_tw.js.

As a result, the language file cannot be loaded.

Same situation as zh_cn: you are running `Parsley.setLocale('zh-cn');` inside zh_cn.js, which is wrong.

Please change your file name from zh_tw to zh-tw, and zh_cn to zh-cn.

By the way, please also add zh-hk.js, which represents Hong Kong.  The content is the same as zh-tw.js.

Thank you.

For details here is [my blog that describe the problem](https://alucard-blog.blogspot.hk/2017/11/parsleyjs-zhhkzhcn-is-not-available-in.html).

**Comment by marcandre** [comment]
It doesn't have to match the filename, only the key given in 'addMessages'. 

I imagine that you still have somewhere code that calls `Parsley.setLocale('zh_tw')`, which would have worked 3 years ago but no longer.
