### ISSUE TITLE
Custom error message not show when the input number on data-* attribute

### ISSUE THREAD

**Issue by anmaitrannguyen** [guillaumepotier/Parsley.js#1255]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [ x ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from https://codepen.io/anon/pen/aKNWZJ?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

[Codepen here](https://codepen.io/anon/pen/aKNWZJ?editors=101)

On the "fullname" input, when use custom error message attribute, data-parsley-required-message="123", if the message is a number, the message will not be shown. Maybe some issues with type case of data-* attribute.

**Comment by marcandre** [comment]
Could I know why you'd want an error message to be a number?

**Comment by anmaitrannguyen** [comment]
I manage to workaround this issues by override the formatMessage function, since it's always check if the string type is not String, it will return '';

```
window.Parsley.formatMessage = function (string, parameters) {
    if (_.isNumber(string)) {
        string = _.toString(string);
    }
    if ('object' === typeof parameters) {
      for (var i in parameters)
        string = this.formatMessage(string, parameters[i]);

      return string;
    }

    return 'string' === typeof string ? string.replace(/%s/i, parameters) : '';
 }
```
