### ISSUE TITLE
Empty fields are passed

### ISSUE THREAD

**Issue by toplisek** [guillaumepotier/Parsley.js#1256]
I have used many years Parsley and it is excellent. 

But I have noticed that empty strings inside my form are still passed using other hacker's methods. 

How to validate also this option as it seems form is submitted even when we use PHP validation, Google gCaptcha and Parsley.

**Comment by marcandre** [comment]
Parsley is client side. You can not trust client side. You must (re-)do validations server side.

Let me know if there's an actual bug in Parsley, but any hacker worth his salt can bypass it easily and there's nothing anyone can do about it.
