### ISSUE TITLE
Window.ParsleyValidator.setLocale('de')

### ISSUE THREAD

**Issue by toplisek** [guillaumepotier/Parsley.js#1257]
In the previous versions it was defined setLocal like
`<script type="text/javascript">window.ParsleyValidator.setLocale('de');</script>`
I have an issue that we like to set in the same manner also updated version.

How is the correct way in this setLocal?
I have not seen inside URL and documentation:
http://parsleyjs.org/doc/index.html

It shows me all the time English version for all error messages.

**Comment by marcandre** [comment]
Right, I'm sorry, the documentation is lacking (PR welcome!).
`Parsley.setLocale('de')` should do it. That's what you'll see at the end of the locale file for german, btw.
