### ISSUE TITLE
email validation and umlauts

### ISSUE THREAD

**Issue by OlafDoering** [guillaumepotier/Parsley.js#1275]
The email validator validates an email like olaf.döring@somewhereelse.de as correct.

I think umlauts are not allowed in localpart.

**Comment by marcandre** [comment]
Your mileage might vary as to if it will work or not, but it is supported by standards and some mail services (like gmail)
https://en.wikipedia.org/wiki/International_email#Email_addresses
https://stackoverflow.com/a/15152095/8279
