### ISSUE TITLE
Issue in layout in Inputs with additional <span> with a button near it

### ISSUE THREAD

**Issue by Sargius** [guillaumepotier/Parsley.js#1276]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by Sargius** [comment]
Hi there,

I implemented Parsley in my admin panel and revealed a error in layouts. It is about error message under input fields, if content doesn't satisfy a condition. I have a button near my input and as error message appears this button's positions messed up.

Here is screenshot attached, you can see the red button with minus sign, not on its right position:
![2018-11-08 15 30 47](https://user-images.githubusercontent.com/1336051/48197318-dab4f480-e36e-11e8-8a01-3bd672fcd89e.png)

Here is also a piece of code for better understanding the problem:

<div class="form-group">
			<label>Адреса:</label>
            <div class="controls">
              <div class="addresses">
                <div class="address-container">
                <div class="entry input-group">
                <input class="form-control" placeholder="Адрес заказчика"
                    id="idAddressLegalBody" name="addresslegal[]" type="text" data-parsley-trigger="change" required>
                <span class="input-group-btn">
                    <button class="btn btn-success btn-add" type="button">
                      <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </span>
                </div>
              </div>
              </div>
            </div>
        </div>

How can I fix this issue, or maybe you need to update the library at your side?

Thank you in advance and thank you for your great library!

With best regards,
Sargius

**Comment by marcandre** [comment]
From the looks of it, parsley is doing what it should. The problem is the way your css is made doesn't behave correctly when parsley...
You'll need to tweak your CSS, or look at the documentation for "errors container"

**Comment by Sargius** [comment]
Well, I corrected the "data-parsley-errors-container" and the error messages appears under the right place now. 

But the message is still deforms my Input, even now when the contain is moved outside of input's container. Here is the code:

<div class="form-group">
     <label>Adresses:</label>
            <div class="controls">
              <div class="addresses">
                <div class="address-container" id="idAddressContainerLegalBody">

                <div class="entry input-group">

                    <input class="form-control" placeholder="Адрес заказчика"
                        id="idAddressLegalBody" name="addresslegal[]" type="text"
                           data-parsley-errors-container="#idAddressContainerLegalBody" data-parsley-trigger="change" required>

                    <span class="input-group-btn">
                        <button class="btn btn-success btn-add" type="button">
                          <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </span>

                </div>

             </div>
              </div>
            </div>
        </div>

Here is result:
![2018-11-11 18 00 40](https://user-images.githubusercontent.com/1336051/48313900-cd507200-e5db-11e8-9b48-96a3fa78b7b4.png)
As you can see, the error message deforms the red button with minus sign.

What we can do here?

**Comment by Sargius** [comment]
I think Parsley is so configured, that <input> filed should now have any elements near it. But with elements, packed along with <input> in some container ruins the layout.
