### ISSUE TITLE
`isValid` result should be polled instead of just checked

### ISSUE THREAD

**Issue by kstratis** [guillaumepotier/Parsley.js#1283]
Parsley v2.8.1
JQuery v3.x

---

Hi,

I was skimming through the source code the other day and was a bit confused over the `isValid` method of the form instance.

`isValid` is supposed to fire validations and let us know the returned promise's status by using `null`, `true` or `false`. 

My question is how is it possible to trigger a form validation through `isValid` and then "attach a handler" to it (`then`) since `isValid` will just return the promise's status...

Also, what’s the whole point of just returning a promise’s status and not returning the promise itself since in case it's `null` the user will have to manually check back again..?

---

For instance in the [Events](http://parsleyjs.org/doc/examples/events.html) example I noticed the following:

```javascript
$(function () {
  $('.demo-form').parsley().on('form:validate', function (formInstance) {
    var ok = formInstance.isValid({group: 'block1', force: true}) || formInstance.isValid({group: 'block2', force: true});
    $('.invalid-form-error-message')
      .html(ok ? '' : 'You must correctly fill *at least one of these two blocks!')
      .toggleClass('filled', !ok);
    if (!ok)
      formInstance.validationResult = false;
  });
});
```

In the example above `ok` could turn out to be `null` meaning that the promise hasn't resolved yet. In this scenario -assuming that the promise resolves say a second later- `$('.invalid-form-error-message').html` will have missed the time window to **properly** update the DOM node and will normally have to check back again for the proper response which in this case it doesn't. 

Am I missing something critical here? 
Any feedback will be more than welcome!
Thanks

**Comment by marcandre** [comment]
Use `whenValid` if you have validations that use promises. `isValid` is only really useful for simple cases that are 100% synchroneous. HTH

**Comment by kstratis** [comment]
@marcandre Thanks for the clarification. Just one quick follow-up:

Is `$.when(arg1).state()` guaranteed to execute synchronously if `arg1` is not a promise/thenable?

**Comment by marcandre** [comment]
`state()` will be `"resolved"`, yes.

Note that calling `when(function() {...})` on a resolved promise has changed between jQuery 2 & 3. jQuery 2 would call the function synchroneously, while jQuery 3 will call it "on next tick" (can't recall the actual term).

```
$.when(42).then(function(){console.log('in')}); console.log('out')
// outputs "in", then "out" in jQuery 2, but "out", then "in", in jQuery 3
```
