### ISSUE TITLE
Some useful validators

### ISSUE THREAD

**Issue by MarcoSulla** [guillaumepotier/Parsley.js#1288]
I think these are a good set of custom validator. I hope they could be added (with some improvement):

```
window.Parsley.addValidator('date', {
    validate: function(value, format) {
        var date = moment(value, format, true);
        return date.isValid();
    },
    messages: {
        en: 'It must be a valid date with format %s',
        it: 'Deve essere una data valida nel formato %s'
    }
});


window.Parsley.addValidator('vatcode', {
    validate: function(value, format, parsleyField) {
        var re = /^[A-Za-z][A-Za-z][A-Za-z0-9]{1,13}$/;
        
        return re.test(value);
    },
    messages: {
        en: "It's not a valid VAT code",
        it: "Non è un codice IVA valido"
    }
});

window.Parsley.addValidator('phone', {
    validate: function(value, format, parsleyField) {
        var re = /^[0-9+*#,;]+$/;
        
        return re.test(value);
    },
    messages: {
        en: "Enter a valid phone number",
        it: "Immetti un numero telefonico valido"
    }
});
```

**Comment by marcandre** [comment]
Thanks for the PR. It's really more like 3 PRs too :-)

Bug: Your regex seem anchored only at the beginning (`^`) but not at the end (missing `$`).

1) date: Good, but depends on the `moment` library. I would rather not add another dependency, but maybe we could put it in `extra/` or in the wiki

2) VAT: Sounds good. Two things though: should be stricter (can only be 2 letters + 13 letters maximum) and requires tests. It would be awesome if you could make a separate PR for this.

3) Phone number: I'm not sure everyone will agree on what can be part of a phone number or not. Note that HTML5 has a "tel" input type but has no validation for it.

**Comment by MarcoSulla** [comment]
Bug: thank you I'll fix it

2. ok for the 2+13, but validation is very difficult, since it depends by state. See [Wikipedia](https://en.wikipedia.org/wiki/VAT_identification_number) for an example.

3. If you see the check is very permissive. It allows any character that you can input in your smartphone, without checking any starting number or so on. I know that `input='tel'` has no validation, but this way it's practically useless.

**Comment by marcandre** [comment]
> Bug: thank you I'll fix it
> 
> 1. ok for the 2+13, but validation is very difficult, since it depends by state. See [Wikipedia](https://en.wikipedia.org/wiki/VAT_identification_number) for an example.

Right, you don't have to go state by state though, I would be afraid this could change in the future? But 2+13 shouldn't.

> 2. If you see the check is very permissive. It allows any character that you can input in your smartphone, without checking any starting number or so on. I know that `input='tel'` has no validation, but this way it's practically useless.

Right, but it's probably too context dependant. For example we use `()` all the time in America for regional code, not so much in Europe. I don't want to provide one builtin.

**Comment by MarcoSulla** [comment]
Ok, I updated the vatcode validator. Should I add a separate issue for date and vatcode validators?

**Comment by marcandre** [comment]
A PR for the vatcode validator would be great. Maybe `vatin` would be a better name, as it seems to be an accepted accronym for it?

Normally a different PR for the `date` validator in `/extra` would be best, but you can include them in the same PR if you prefer.

**Comment by marcandre** [comment]
BTW, it's `{2,13}`, not `{1,13}`

**Comment by MarcoSulla** [comment]
Ok for `vatin`. Why 2?

**Comment by marcandre** [comment]
From wikipedia: "... and then has **between 2** and 13 characters"

**Comment by MarcoSulla** [comment]
Don't know, I read the list and the shortest are Romania ([that is incorrect](url)) and San Marino that seems to have the shortest: SM + 5 digits ([source](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fforum.commercialistatelematico.com%2Fiva-intrastat-spesometro-san-marino%2F24688-intra-san-marino-codice-fiscale.html))

**Comment by marcandre** [comment]
Your link for *thas is incorrect* leads nowhere. What is Romania's shortest VATIN then? Might as well fix wikipedia...

**Comment by MarcoSulla** [comment]
Excuse me, I fixed the link

**Comment by MarcoSulla** [comment]
There's a little problem. Some countries uses spaces, hypens or dots as separators. Should we add these characters to the validator?

**Comment by marcandre** [comment]
Your link says 8. [This link](https://www.avalara.com/vatlive/en/eu-vat-rules/eu-vat-number-registration/eu-vat-number-formats.html) says 10. [This other link](https://www.gov.uk/guidance/vat-eu-country-codes-vat-numbers-and-vat-in-other-languages) says 2-10... Hard to say which is right 😢 . I posted on the Talk page of wikipedia, but for now probably best to keep it safe at minimum 2.

**Comment by MarcoSulla** [comment]
Oh well, let be 2.
What about special characters?
PS: Indonesia seems to have a longer length, 20 characters, thanks to separators

**Comment by marcandre** [comment]
I was looking at EU VAT. Maybe the name should be `EUVATIN`? Looks like poland allows `-` for formatting, but I'd be fine with excluding it, your call.

**Comment by MarcoSulla** [comment]
We can create two validators, vatin and euvatin. I think to let people to add the special characters, they could think it's not correct without them.

PS: it seems that Indonesia [has a greater length](http://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Indonesia-TIN.pdf). I think we can remove the max limit, since it can change in any state at any time.
