### ISSUE TITLE
Strange behaviour of data-parsley-excluded added and removed on the fly on a single field

### ISSUE THREAD

**Issue by MarcoSulla** [guillaumepotier/Parsley.js#1290]
1. `data-parsley-excluded` must be added with `$().attr()`. `$().data()` does not work.
PS: I tried this also with `data-parsley-required`, so it seems a common behavior:
https://jsfiddle.net/6xqs4c9j/1/
2. If you add `data-parsley-excluded` you must destroy and recreate parsley on the form, or it does not work
3. once `data-parsley-excluded` is set to true, if you subsequently set it to false or remove the attr completely, it continues to works as it is true, even destroying and recreating parsley on the form.

https://jsfiddle.net/7kh4tvd8/7/

4. the only way to simply handle this case is to set
`$single_input.parsley().options.excluded = true;`
and
`$single_input.parsley().options.excluded = false;`
https://jsfiddle.net/6xqs4c9j/

**Comment by marcandre** [comment]
Hopefully this should be resolved at the same time as #1177.

Let me know if that's not the case...

**Comment by MarcoSulla** [comment]
Thank you, it works like a charme now.

It's not possible to do nothing about the first point? It's a bit misleading that you can enable parsley options with `attr` but not with `data`, since they are `data` attrs.

**Comment by marcandre** [comment]
I understand your confusion. `data` gets *initialized* from `data-` attributes, but once you have called `data` *once* on a DOM element and initialization is done, then there is no longer a relationship between the attributes and the values of `data()`; both can be changed independently and jQuery never updates the counterpart.
Parsley always uses the attributes, never the `data`, which I believe is the right way to go.
You can change Parsley's default and replace `data-parsley-` with something else; note that only `data-...` attributes are supposed to be used according to the HTML specs though.
HTH
