### ISSUE TITLE
Vatin validators

### ISSUE THREAD

**Issue by MarcoSulla** [guillaumepotier/Parsley.js#1292]
```
window.Parsley.addValidator('euvatin', {
    validate: function(value, format, parsleyField) {
        var re = /^[A-Z][A-Z][A-Za-z0-9 -]{2,}/;
        
        return re.test(value);
    },
    messages: {
        en: "It's not a valid VAT Identification Number",
        it: "Non è un codice IVA valido"
    }
});
```

PS: GB allows spaces...

**Comment by MarcoSulla** [comment]
Ok, I dropped vatin, since there's countries like Belarus that uses Cyrillic...

**Comment by marcandre** [comment]
It would be great if you made an actual PR, with modifications to `src/...` and `/test/...`?

**Comment by MarcoSulla** [comment]
Well, PR was done and it passed all the tests. The same for the extra/ date validators.

**Comment by marcandre** [comment]
Right, but implementation isn't done properly, should be as `integer` and all

**Comment by MarcoSulla** [comment]
I tried to put it like integer, but it does not work. Please prove yourself.

**Comment by MarcoSulla** [comment]
See? I changed it as you like, and the tests fail with an obscure message.
