### ISSUE TITLE
CHANGELOG.md is outdated, Tag for current version is missing

### ISSUE THREAD

**Issue by Tilogorn** [guillaumepotier/Parsley.js#1300]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [x] Feature Request

Just noticed the update from 2.8.1 to 2.8.2 and couldn't find any information in the CHANGELOG.md mentioning the changes. There isn't even a "release" or "tag" for this version. Could you provide more information?

**Comment by marcandre** [comment]
Indeed, the tag was missing, I just pushed it, thanks.

I made the Changelog more clear too in bb6781098d2e7

So updated language files, and #1151 and an updated build system.
