### ISSUE TITLE
Strange warnings

### ISSUE THREAD

**Issue by MarcoSulla** [guillaumepotier/Parsley.js#1301]
> Accessing the method 'addValidator' through Validator is deprecated. Simply call 'window.Parsley.addValidator(...)' utils.js:89:63
>
> Calling validate on a parsley form without passing arguments as an object is deprecated. utils.js:89:63

I have no utils.js in my project, and your `utils.js` has no `addValidator`. I don't know why I get this warnings.

**Comment by marcandre** [comment]
`utils.js` is where the warning is issued. Check the whole backtrace.

**Comment by MarcoSulla** [comment]
But in [utils.js](https://github.com/guillaumepotier/Parsley.js/blob/master/src/parsley/utils.js) there's no `addValidator()`

**Comment by marcandre** [comment]
There's `addValidator` somewhere, that calls `warn` in `utils` that calls `console.warn`.

Please understand that I am only a volunteer and can not reasonably help people debug issues on my free time.
