### ISSUE TITLE
Bug: 0 is valid when min is a number greater than 0. 

### ISSUE THREAD

**Issue by zahrank21** [guillaumepotier/Parsley.js#1303]
- [x] Bug report. 

For the input with type number, if the min is greater than 0,  0 still is a valid input. Note: only parsley believed its valid when [javascript validation api](https://www.w3schools.com/js/js_validation_api.asp) can ascertain that number is invalid. 

`<input id="number" type="number" class="form-control" min="3" max="5600" step="0.01" required="" data-parsley-type="number">`

https://codepen.io/anon/pen/oOpoXp?editors=101&editable=true

**Comment by marcandre** [comment]
Oh, that's pretty bad. Thanks for the report. I think this was broken by #1151. I probably should not have accepted it...

**Comment by krnjn** [comment]
Thanks for the confirmation @marcandre - is there an estimate on a fix or suggested workaround you have for this?

**Comment by krnjn** [comment]
For what it's worth and for others coming across this, we added a custom validator as a workaround to *just* check that the value is non-zero (though this presumes that it's numeric which you can achieve using the data-type number and a number input with step of 0.01):

```
parsley.addValidator('nonZero', {
    validateNumber: value => Number.parseFloat(value) !== 0,
    messages: { en: "You must enter an amount greater than zero." }
  })
```

**Comment by marcandre** [comment]
Sorry for the delay. Should be reasonable easy to fix, i'm just hesitating between fixing it or reverting #1151

**Comment by krnjn** [comment]
No problem -- we'll look out for a fix and will just leave our custom validator in play for now. Thanks for being so responsive!

**Comment by marcandre** [comment]
Fixed and released.

Thanks again for the bug report.
