### ISSUE TITLE
Floats and Parsley validation

### ISSUE THREAD

**Issue by toplisek** [guillaumepotier/Parsley.js#1305]
I try to implement floats and also digits. When I have numbers for the price in USA format it will not be the correct code. How to manage floats or digits. An example: 

The price can be 10 USD, 10.55 not 10.5 USD. As I understand it will work required just floats using type="text" and data-parsley-type="number", but how to solve max. two decimals? 

Is this working and the correct? 
`
data-parsley-pattern="[0-9]*(\.?[0-9]{2}$)" using type="text" and data-parsley-type="number"`

Need help.

**Comment by toplisek** [comment]
Can be suggested exact demo to work floats? Maybe I missed...

**Comment by marcandre** [comment]
I'm afraid I'll have to close this. First, this is a question and thus does not belong here, second it's not even clear what issue you are having with your solution.
