### ISSUE TITLE
Parsley 2.9.1 missing on GitHub releases

### ISSUE THREAD

**Issue by kumy** [guillaumepotier/Parsley.js#1308]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

The version 2.9.1 is not downloadable. Not GitHub release, and link on https://parsleyjs.org/doc/download.html is indeed broken.
Bests

**Comment by marcandre** [comment]
Oh, indeed. Should be fixed now, thanks for the report.
