### ISSUE TITLE
Selectpicker doesn't work with parsley

### ISSUE THREAD

**Issue by sanoj26692** [guillaumepotier/Parsley.js#1311]
i want to validate bootstrap-select (selectpicker), i done everything that's need it works fine with `input` but in `select` it just display error message and not the border color for select

here is the code https://jsfiddle.net/sanoj908572/jdo6reaf/2/

![Untitledl](https://user-images.githubusercontent.com/7949017/61295309-5b2cce80-a7f5-11e9-936d-cb08b370b7b1.jpg)

**Comment by FireEmerald** [comment]
Even though this issue has already been closed, here is my solution:
``` html
<div class="form-group">
    <label for="example">Select:</label>
    <select multiple class="form-control selectpicker" id="example" name="example"
            data-parsley-errors-container="#error-container" required="">
        <option value="1">Option 1</option>
        <option value="1">Option 2</option>
    </select>
    <div id="error-container"></div>
</div>
```
``` js
$('#modifyExistingModal form').parsley({triggerAfterFailure: 'focusout changed.bs.select'}).on('field:validated', function() {
        var ok = $('.parsley-error').length === 0;
        // do something with ok
    })
    .on('form:submit', function() {
        return false; // Don't submit form for this demo
    });
```

The **important** parts are:
- `data-parsley-errors-container="#selector"` and
- `parsley({triggerAfterFailure: 'focusout changed.bs.select'})`.

See also [events](https://developer.snapappointments.com/bootstrap-select/options/#events) of bootstrap-select and [this](https://stackoverflow.com/questions/30122028/change-the-position-of-parsley-errors-list-in-parsleyjs) stackoverflow answer.
