### ISSUE TITLE
Custom validator only runs when checkbox checked

### ISSUE THREAD

**Issue by iamkeir** [guillaumepotier/Parsley.js#1313]
- [ x] Bug report

I _think_ this is a bug, but I could be misunderstanding.

**Description**
When creating a custom validator for a checkbox, it only runs the validation when the checkbox is checked, not when unchecked/lose focus/submit. This is a problem if custom validation is related to the unchecked state.

**Expected behaviour**
Custom validation should run when checking, unchecking, lose focus and submit. Especially as `trigger: 'focusout change'` and `triggerAfterFailure: 'focusout change'` are set.

**Actual behaviour**
Custom validation only runs on checking checkbox.

**Demo**
https://codepen.io/iamkeir/pen/gOYrzaZ?editors=1011

**Comment by marcandre** [comment]
I understand this may be confusing, but Parsley handles "empty" inputs differently; you'll want to add `data-parsley-validate-if-empty` to your checkbox (or you pass `force: true` when calling `isValid` & al.)

**Comment by iamkeir** [comment]
Thanks @marcandre, no that makes sense. Is it possible to pass `force: true` to a custom validator rather than add it as a `data-attr`?

**Comment by marcandre** [comment]
I'm afraid not; the flag is attached to an input, not to the validator.

You could add the attribute to the form if that's what you want (since all attributes are inherited).
