### ISSUE TITLE
max date validation failing on chrome ONLY with minified version

### ISSUE THREAD

**Issue by hanoii** [guillaumepotier/Parsley.js#1321]
This is an odd issue, I was reported of this issue on a project,

https://codepen.io/hanoii/pen/YzzRGgq

Simply hit submit and parsely will throw the error. I debugged the minified version and it seems that the [max operator comparison](https://github.com/guillaumepotier/Parsley.js/blob/ab918a1176c8c48f800b62da06ecb848deea51ae/src/parsley/validator_registry.js#L347) is getting a "yyyy-mm-dd" while the requirement is a date object.

I _**believe**_ that the issue is [in a line](https://github.com/guillaumepotier/Parsley.js/blob/ab918a1176c8c48f800b62da06ecb848deea51ae/src/parsley/validator.js#L53) that was not properly minified.

See the a working codepen where the only difference is that is using the non-minified version:

https://codepen.io/hanoii/pen/xxxQENK

**Comment by marcandre** [comment]
Hi! I'm really grateful that you seem to have looked deeper in this issue, and I'm sorry it's there at all.
For the first time if my life, I don't have my computer with me, as I'm trekking the Annapurna circuit! I will be reunited with my laptop in about two weeks; I'll either look at this on a plane or when I'm back home in early December...

**Comment by hanoii** [comment]
@marcandre wow, awesome. The fact that you replied to this while trekking is even more mind boggling than the bug itself. Please enjoy and don't restrain yourself from attaching pictures here, always nice to dress a github issue a bit.

**Comment by marcandre** [comment]
![PANO_20191115_110743](https://user-images.githubusercontent.com/33770/68948439-cab8c780-07af-11ea-9d12-72fff5d63226.jpg)

Today's destination was Tilicho lake at almost 5000m :-)

**Comment by guillaumepotier** [comment]
Whoa, impressive ;) What kind of wide-angle to you have there? 14mm?

**Comment by hanoii** [comment]
My money is on a mobile panorama :).

**Comment by marcandre** [comment]
@hanoii almost has it, but I'm using an android phone.

**Comment by marcandre** [comment]
I battled with the tooling, updated the versions and when I managed to get it to compile again, the minimized version was correct. v2.9.2 should be ok.

Thanks again for the great detective work 🕵️‍♂️
