### ISSUE TITLE
prevent copy error message when use jquery clone() method

### ISSUE THREAD

**Issue by asadghazanfary** [guillaumepotier/Parsley.js#1330]
hello 

how can prevent copy error message created with parsley js when use clone() method to create daynamicaly multiple input field  in jquery?

i

**Comment by asadghazanfary** [comment]
@marcandre why closed this issue?

**Comment by marcandre** [comment]
>       This issue tracker is not the place for questions. If you want to ask how to do
>       something, or to understand why something isn't working the way you expect it to, use
>       http://stackoverflow.com/questions/ask .
>       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
>       We monitor the tag `parsley.js`.
