### ISSUE TITLE
Where is parsley.remote.js?

### ISSUE THREAD

**Issue by rob101** [guillaumepotier/Parsley.js#1335]
The [docs](https://parsleyjs.org/doc/#remote) suggest you need to include `<script href="parsley.remote.js"></script>` when using `addAsyncValidator`. However this file is not included separately in the lasted dist (2.9.2 `/dist/`). Is it now in the main package?

**Comment by marcandre** [comment]
Oh, sorry, good catch. Yes, it's builtin since v2.0.0 :-)
Doc fixed, thanks
