### ISSUE TITLE
Required option with only text is treated like having a value and passes validation

### ISSUE THREAD

**Issue by djiest** [guillaumepotier/Parsley.js#1344]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [X ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

When adding text to a **_required_** `<option>`, but not the value attribute, it is validated as if having a value

`<option> Make your choice</option>` passes validation
`<option />` does not pass validation

See this example https://codepen.io/djiest/pen/mdEomGB?editors=101, where the first <select> passes validation and the second one does not

**Comment by marcandre** [comment]
I don't understand your bug report. You mean that after clicking "destroy" things don't work as you want?

**Comment by djiest** [comment]
Ah, that was unclear I understand. I have updated Codepen, see https://codepen.io/djiest/pen/mdEomGB?editors=101

When you click 'Submit' the first dropdown passes validation, whereas the second one doesn't. I would expect the first one to fail validation as well, since I have not selected one of the options with a value.

**Comment by marcandre** [comment]
Oh, I see. I believe this is as per spec.

Typically, `parsley` will follow the standard. If you remove parsley in your example, your first `<select>` does not generate an error either.

I think you want `<option disabled selected> Make your choice</option>`. If not disabled, then it is technically selectable.
