### ISSUE TITLE
Parsley.js bug

### ISSUE THREAD

**Issue by bartollajos** [guillaumepotier/Parsley.js#1348]
Hello,

Could you help please in the following parsley.js issue?

It seems to be a Parsley bug: Parsley should remove the error container if there are no errors anymore.

https://stackoverflow.com/questions/65236237/parsley-validation-after-a-successful-input-validation-an-empty-element-is-rema

@marcandre Do you have any idea? There is a screenshot under the stackoverflow link above which explains the issue. 

Thank you,
Lui

**Comment by bartollajos** [comment]
@marcandre Thank you for answer on stackoverflow.
I would need a jquery script which will remove the .parsley-errors-list when the input is succeeded. 
It seems otherwise it is remined there. Although i used .filled class in CSS.

https://stackoverflow.com/questions/65236237/parsley-validation-after-a-successful-input-validation-an-empty-element-is-rema

**Comment by bartollajos** [comment]
@marcandre it seems this script does the trick. Maybe it is ugly bit works:

```
$('#contactForm').parsley().on('field:success', function() { 
    $('ul').not(':has(li)').remove();
});
```

**Comment by marcandre** [comment]
Great :-)
