### ISSUE TITLE
Email validation does not support gTLDs as email domain

### ISSUE THREAD

**Issue by jmac-digital** [guillaumepotier/Parsley.js#1367]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Email validation does not take into account for all TLD variations.

Whilst trying to sign up for a website where they use parsley - my email address was rejected multiple times.

it seems to be something around the second segment in a regex where if I enter in more than 5 characters it triggers the error validation stating that it is not a valid email address.

The email domain that i use is `.digital` meaning it won't accept anything past `.digit` as the last segment in the email.

The website is using v2.9.2 of Parsley and jQuery v3.5.1

**Comment by marcandre** [comment]
I tried "a@b.digital" in the [example page](http://parsleyjs.org/doc/examples/simple.html) and it validates correctly.
