### ISSUE TITLE
How to exclude field from validation ? 

### ISSUE THREAD

**Issue by MROALI** [guillaumepotier/Parsley.js#1370]
Hello, i have a multistep form, and i need to exclude on fly some field depending on some critrerias... 

I tried to implement  field:validate , but not working. Do you have anyidea how can i do it, any idea ? 

```
Parsley.on("field:validate", function(field) {
    var objField = field.$element
	if(!isFieldToValidate(objField)){
          objField.attr("data-parsley-excluded","true");
        return false;  
	}
	return true;
});
```

**Comment by marcandre** [comment]
Interdependencies are not super easy to handle. See [this example](http://parsleyjs.org/doc/examples/custom-validator-events.html) and #949.

Good luck.
