### ISSUE TITLE
Inefficient regular expression

### ISSUE THREAD

**Issue by freonirons409** [guillaumepotier/Parsley.js#1374]
What kind of issue is this? (put 'x' between the square brackets)
 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .
----------------------------------------
`development/src/scripts/plugins/parsley.js:574`

This part of the regular expression may cause exponential backtracking on strings starting with '0.' and containing many repetitions of '00.'.

![Screenshot 2024-04-18 2 43 31 PM](https://github.com/guillaumepotier/Parsley.js/assets/7460484/b1984028-9c7b-460d-a786-7e9622baccdd)

---

Some regular expressions take a long time to match certain input strings to the point where the time it takes to match a string of length n is proportional to nk or even 2n. Such regular expressions can negatively affect performance, or even allow a malicious user to perform a Denial of Service ("DoS") attack by crafting an expensive input string for the regular expression to match.

The regular expression engines provided by many popular JavaScript platforms use backtracking non-deterministic finite automata to implement regular expression matching. While this approach is space-efficient and allows supporting advanced features like capture groups, it is not time-efficient in general. The worst-case time complexity of such an automaton can be polynomial or even exponential, meaning that for strings of a certain shape, increasing the input length by ten characters may make the automaton about 1000 times slower.

Typically, a regular expression is affected by this problem if it contains a repetition of the form r* or r+ where the sub-expression r is ambiguous in the sense that it can match some string in multiple ways. More information about the precise circumstances can be found in the references.

## Recommendation
Modify the regular expression to remove the ambiguity, or ensure that the strings matched with the regular expression are short enough that the time-complexity does not matter.

## Example
Consider this regular expression:

`/^_(__|.)+_$/`

Its sub-expression "(__|.)+?" can match the string "__" either by the first alternative "__" to the left of the "|" operator, or by two repetitions of the second alternative "." to the right. Thus, a string consisting of an odd number of underscores followed by some other character will cause the regular expression engine to run for an exponential amount of time before rejecting the input.

This problem can be avoided by rewriting the regular expression to remove the ambiguity between the two branches of the alternative inside the repetition:

`/^_(__|[^_])+_$/`

## References
OWASP: [Regular expression Denial of Service - ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS).
Wikipedia: [ReDoS](https://en.wikipedia.org/wiki/ReDoS).
Wikipedia: [Time complexity](https://en.wikipedia.org/wiki/Time_complexity).
James Kirrage, Asiri Rathnayake, Hayo Thielecke: [Static Analysis for Regular Expression Denial-of-Service Attack](https://arxiv.org/abs/1301.0849).
Common Weakness Enumeration: [CWE-1333](https://cwe.mitre.org/data/definitions/1333.html).
Common Weakness Enumeration: [CWE-730](https://cwe.mitre.org/data/definitions/730.html).
Common Weakness Enumeration: [CWE-400](https://cwe.mitre.org/data/definitions/400.html).

**Comment by marcandre** [comment]
Thanks for opening the issue.

I consider this a negligible issue, since the code runs on the client's machine.

That said, if you can propose a PR with an improved regex I'd welcome it.
