### ISSUE TITLE
validation against multiple selects

### ISSUE THREAD

**Issue by vitxd** [guillaumepotier/Parsley.js#156]
Hi, this is not a bug, rather a request of feature or in case an explanation.
I need to validate a date of birth. the inputs are 3 dropdown lists.
If I tried to use the same validator (data-dob) passing as parameter the figure name (day, year, month) and validating the whole lot. It works but in the meanwhile I fill every single dropdown, it prints different error boxes and once all 3 fields are ok, it deletes just one. I also tried to use data-group but without good results. do you have a suggestion how to achieve it?
I have other minor bugs/annoying features to report as well as I used your library a lot in the last two weeks :)

I had time I would have helped directly on the code, anyway thanks a lot for the work you have done!

**Comment by custa1200** [comment]
I'm still hoping to see this solution as it is something that I find to be quite common with forms.

**Comment by shaselboeck** [comment]
+1 for this feature

**Comment by marcandre** [comment]
Those interested can (after reading up on the new custom validator API) follow #949 to discuss the API for this
