### ISSUE TITLE
Option to silence error messages inside form

### ISSUE THREAD

**Issue by happz** [guillaumepotier/Parsley.js#214]
Hi,

would it be possible to add an option to order Parsley not to report error messages? My use case is this: I use my own form builder to create forms, that displays errors in designated place inside form. Hooking Parsley inside my code was easy but I had to silence its reports by:

``` css
parsley-error-list {
  display:        none !important;
}
```

All I'm interested is "tell me if all values are valid or not", or better "tell me what fields contain invalid values" - I'll report this to user my own way. Parsley does it's validation job perfectly (for my needs, at least :) but talks too much :) Using CSS to silence Parsley works, no doubt about that, but I just thought it'd be nice to have an option for this behavior - it'd be more straightforward, readable and understandable.

**Comment by ingro** [comment]
@oprichnik Thank you sir, you saved me a lot of time!

**Comment by mckinleymedia** [comment]
Hey.  No problem.  Glad it helped.


--Will

---
                             Will McKinley
                        McKinley Media Inc
               Adding vision to corporate design
www.mckinleymedia.com <http://www.mckinleymedia.com/>     will@mckinleymedia.com <mailto:will@mckinleymedia.com>     (415) 924-1975
---

**Comment by holoiii** [comment]
Is there a way to show / hide error messages when calling validate on a field group? I don't want to use data-parsley-errors-messages-disabled because it isn't flexible enough for this use case.

**Comment by marcandre** [comment]
@holoiii not sure what you mean. Calling `isValid()` will not trigger events (and thus not update the error messages), while `validate()` will.

**Comment by ivangretsky** [comment]
Is there a way to prevent errors display while still adding the error classes from the js (not with the attribute)?

**Comment by karlingen** [comment]
@oprichnik Can this be set on the form? I have tried the following approach but it doesn't:

```
$('#steps').parsley({
    "errors-messages-disabled": true
});
```

It only works when I add it to the input field.

**Comment by dwilhel1** [comment]
As of the current date, the following worked for me: 

`data-parsley-errors-messages-disabled`

I added this value as an attribute to the form element as follows: 

`<form data-parsley-validate data-parsley-errors-messages-disabled id="form-id" >`

According to the [API documentation](http://parsleyjs.org/doc/#frontend-form-validation):
> Add `parsley-success` and `parsley-error` classes on field, but no error message.
