### ISSUE TITLE
Documentation site broken

### ISSUE THREAD

**Issue by scottmboring** [guillaumepotier/Parsley.js#256]
The documentation site depends on a CSS file and JS file from yandex.st which never load, at least in the US at my office.

These two files never load
http://yandex.st/highlightjs/7.3/styles/github.min.css
http://yandex.st/highlightjs/7.3/highlight.min.js

The documentation site subsequently hangs for over 3 minutes displaying nothing before the two files time out and then the site can be viewed.

**Comment by akuzemchak** [comment]
This appears to still be an issue... same scenario for me as OP. Can't load the documentation site in my US-based office. I'm willing to bet this is because _yandex.st_ redirects to a _.ru_ domain, which I think most offices here are likely to block. Any chance of simply checking the highlight code into the repo itself? I can do a PR if need be.

**Comment by marcandre** [comment]
@akuzemchak AFAIK, we do not have any reference to `yandex.st` anywhere. Let me know if I'm wrong, by pointing out in the source where the issue is. All the doc is in the source.

**Comment by akuzemchak** [comment]
@marcandre please see here: https://github.com/guillaumepotier/Parsley.js/search?utf8=%E2%9C%93&q=yandex.st

**Comment by marcandre** [comment]
Oops, sorry, bad setting for search in my text editor...

**Comment by akuzemchak** [comment]
Ha, no worries! Maybe using CDNJS would be a better alternative? Replacement URLs are:

* https://cdnjs.cloudflare.com/ajax/libs/highlight.js/7.3/highlight.min.js
* https://cdnjs.cloudflare.com/ajax/libs/highlight.js/7.3/styles/github.min.css

**Comment by akuzemchak** [comment]
Pull request here: https://github.com/guillaumepotier/Parsley.js/pull/1025

**Comment by marcandre** [comment]
lol, I was faster by 2 minutes :smile:
Thanks for this

**Comment by akuzemchak** [comment]
Ha, I'll take that! Thanks :)
