### ISSUE TITLE
Min Char Validation Configuration

### ISSUE THREAD

**Issue by cfenn** [guillaumepotier/Parsley.js#325]
Hello,
Set up Parsley on an HTML form using data-validate="parsley">.  I have a few fields that need to be exactly 3 digits long with a change trigger.  I set up the field constraints as a Range [3,3] and it validates okay upon submission, but not upon the field change.  

Reading the "Heads Up" towards the top of the Documentation, I saw that Parsley is set up by default to not validate a field when less than three characters have been entered, but this is customizable. 

It looks to me like changing ", validationMinlength: 3" to ", validationMinlength: 1" should do the trick, but it doesn't seem to work.  It will work if the max length is eclipsed, but not with the min value.  

Am I missing something?  Any help would be appreciated.

Thank you.

**Comment by sumit-bharekar** [comment]
You might need to configure data-parsley-validation-threshold="9" if you are using 2.0.
