### ISSUE TITLE
Configurable error removal

### ISSUE THREAD

**Issue by noahlh** [guillaumepotier/Parsley.js#34]
Another thought / feature request:

Might be useful to allow configuration / customization of the error removal process.  Right now I believe the only option is as-described in the "Le UX tips" section:

"when a field is detected and shown as invalid, next checks are done on each keypress to try to quickly remove error(s) message(s) once field is ok."

This makes sense for many cases, but here's an example where some customization might be nice (I'll give example with pictures from the form I've been building).

Start with a blank field:

![Screen Shot 2013-01-22 at 11 12 27 AM](https://f.cloud.github.com/assets/113276/86903/8db8a428-64ae-11e2-8752-c1124749d3aa.png)

I have data-validation-minlength set to 0 and a trigger on blur/change, so if leave the field blank or tab out, I get the error message as expected (I have minlength set to 0 because otherwise tabbing out of the field won't trigger the message, which is what I want).

![Screen Shot 2013-01-22 at 11 14 13 AM](https://f.cloud.github.com/assets/113276/86908/c8fd3c1a-64ae-11e2-9967-dbb34ab8501e.png)

So if I tab back in and start typing a name, because the default behavior is to check for validity on every keypress, as soon as I type the first letter I'm given the positive feedback that the field is now valid:

![Screen Shot 2013-01-22 at 11 16 28 AM](https://f.cloud.github.com/assets/113276/86918/19987ae0-64af-11e2-8e63-5c25c00a4813.png)

But I haven't finished typing my name, so that feedback is interruptive.  At least in this case, what would make more sense is to allow the user to type the name, and then be able to run a validation check as they move to the next field.

So I guess in other words, what I'm requesting is configuration of the validation-correction check -- instead of a default "keyup" event right away I'd like to be able to configure the validation check to be the same as my initial validation check (in my case, the blur or change event) or whatever event I may choose.  

Let me know if this makes sense :)

**Comment by jasonblalock** [comment]
Does anyone have an answer to noahlh's question? I'm running into the same issue. Thanks!

**Comment by dsgrant** [comment]
@noahlh @jasonblalock 

Not a config option, but if you want a global change you can find the manageFailingFieldTrigger function and change this:
```
if (!new RegExp('keyup', 'i').test(fieldInstance.options.trigger || ''))
        return fieldInstance.$element.on('keyup.ParsleyFailedOnce', false, $.proxy(fieldInstance.validate, fieldInstance));
```

To this:

```
if (!new RegExp('keyup', 'i').test(fieldInstance.options.trigger || ''))
        return fieldInstance.$element.on('focusout.ParsleyFailedOnce', false, $.proxy(fieldInstance.validate, fieldInstance));
```
