### ISSUE TITLE
Error: $(...).parsley is not a function

### ISSUE THREAD

**Issue by sque89** [guillaumepotier/Parsley.js#355]
Hey guys,

I'm using you parlsey lib in a project and have an issue, which is surely my fault. I try to update a constraint of a text field. This is the code:

Im binding the parley validation to my DOM with: $( '#datenbank' ).parsley();
This works, im getting no error.

But when i try to update the constraint with this function

function swapDisabled(checkname, textname)
        {  
            document.forms["datenbank"].elements[textname].disabled =                     !document.forms["datenbank"].elements[checkname].checked;
            $( '#inserat1' ).parsley( 'updateConstraint', { "data-required": true } );
        }

Im getting the following error in the console:
$(...).parsley is not a function

You see the code on http://vox-animalis.de/?page_id=21

Whats wrong? thanks a lot for your help.

**Comment by charlesthinks** [comment]
Me too dude

**Comment by marcandre** [comment]
Looks like the library isn't loading (at all or properly). Check the console / error logs...
