### ISSUE TITLE
Does not work with AngularJS until refresh window

### ISSUE THREAD

**Issue by ghost** [guillaumepotier/Parsley.js#356]
Hi there!
I'm trying to make Parsley get activated on AngularJS but it works just when you refresh the page, but this is not how AngularJS works.

Is this a bug or there is something that i'm missing?
Tkz in advance!

Cheers from Brazil! ;)

**Comment by ralberts** [comment]
Here is my current solution for using AngularJS and Parsley:  http://ryanalberts.com/797/parsley-validation-with-angularjs/ 

Hope it helps someone as I was looking for a solution all over the web :-)

**Comment by mjpattani** [comment]
I have integrated this in my Angular 4 project and i am having a similar issue- It works only after page is refreshed. I am using v2.8.0 of parsley.js

**Comment by marcandre** [comment]
My guess is that the Angular is playing tricks that make Parsley's auto-binding not work. I haven't played with Angular, but if you rebind things manually (by calling `$('[data-parsley-validate]').parsley()`) using the right callback from Angular, it would probably resolve the issue?

Fixes welcome, especially that it's the kind of issue that I won't have the time to investigate unless I'm sponsored for it.
