### ISSUE TITLE
What about select validation ?

### ISSUE THREAD

**Issue by bendem** [guillaumepotier/Parsley.js#38]
Hi guy, at first, thanks for this awesome jQuery plugin...

I tried to make sure that the first option of my select will not passed (it's something to say user to choose an option...) so i put an empty value and tried "data-notblank", "required", "data-regexp" but nothing seems to work at the moment.

I looked in the code but i don't understand all of it ;) is there a simple way to do that ?

Cordially,

**Comment by SimonFricker** [comment]
+1

**Comment by nadnadia96** [comment]
I am using selectric dropdown. Parsley is not validating with select dropdown when using selectric class. Please suggest a solution how to use selectric class with parsley validation.

**Comment by marcandre** [comment]
Config probably needs to be tweaked, since by default Parsley will exclude hidden fields.

If someone needs me to spend time writing a complete solution I'm available for hire.

**Comment by PranayHalder** [comment]
> @dotcominfo I was running into this issue when using a placeholder as the first option. For example, if you have a dropdown of US states and the first option is something like:
> 
> ```
> <option>Select a state...</option>
> ```
> 
> , you need to make sure to explicitly set the value as empty for that first option, e.g.:
> 
> ```
> <option value="">Select a state...</option>
> ```
> 
> . Once I did that, the validation worked as expected, meaning the error message was displayed if the default placeholder was selected, and not an actual US state option. For what it's worth, I also used parsely-required="true" and data-trigger="change" on the select tag.


This works Perfectly. THanks
