### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by pedropiedade** [guillaumepotier/Parsley.js#396]
I'm trying to validate a captcha with Parsley.

Here's my code:

```
$('#contact-form').parsley({
        validators: {
            recaptcha: function(val) {
                var status = false;
                var recaptchaChallengeField = $("#recaptcha_challenge_field").val();
                var recaptchaResponseField = $("#recaptcha_response_field").val();
                $.ajax({
                    async: false,
                url: AJAX_ROOT + "recaptcha",
                type: "POST",
                data: {"recaptcha_challenge_field": recaptchaChallengeField, "recaptcha_response_field": recaptchaResponseField},
                success: function(reply) {
                    status = true;
                },
            });
                return status;
            }
        },
        messages: {
            recaptcha: "The captcha is incorrect"
        }           
    }
);
```

It kinda works, but when the captcha is wrong and I try to type it again, for every letter I type it keeps sending AJAX requests and it all gets really slow. Is there a way to change this behavior?

Thanks!

**Comment by serhioV** [comment]
@pedropiedade what was your #contact-form content?

something like: 

    <input class="textbox" type="text" 
               name="recaptcha_response_field" 
               id="recaptcha_response_field" 
               data-parsley-required="" 
               data-parsley-recaptcha="???" >

?
