### ISSUE TITLE
exact length validator?

### ISSUE THREAD

**Issue by jordanstephens** [guillaumepotier/Parsley.js#417]
Any reason there is not an exact length validator built in?

I see min length, max length, and range length, but i don't see exact length.

Am I missing something?

Should I add it? I'd be happy to whip up a pull-request.

**Comment by lupetalo** [comment]
This worked for me:
`data-parsley-length="[9,9]" data-parsley-length-message="This value should be exactly 9 digits long" data-parsley-type="digits"`
