### ISSUE TITLE
Force Validator on empty field

### ISSUE THREAD

**Issue by throrin19** [guillaumepotier/Parsley.js#489]
Hi, I want to force validator on Empty field. In my application, i have input groups (different names) and if : 
- all are empty : input is valid
- one of them has value and current is empty : input is invalid
- all have value : input is valid

But, in current time, it's not possible to call custom validator if input is not required and if it's empty (or i can't find this in documentation).

I test parsley-validation-minlength="0" but nothink. Remove required constraindt or add dynamicly but it does not work.

The last and simple case is to force this validator on non required empty fields.

Thanks

**Comment by rob101** [comment]
@guillaumepotier  in your example above (updated for recent depreciations), this amends the UI but how would you manually force is_invalid() on the fields involved so the form does not submit?

**Comment by marcandre** [comment]
I didn't read the whole thread, but what seems like the correct way to do this is to either actually change the `required` attribute when inputs are changed, or add a custom validation to the fields that checks the state of other fields. HTH
