### ISSUE TITLE
Conflation of type="number" and parsley-type="number"

### ISSUE THREAD

**Issue by pipes161** [guillaumepotier/Parsley.js#508]
This is for version 1.2.3.

The implementation of type="number" and parsley-type="number" is supposed to be the same, according to the documentation.

However, the implementations are not the same. A test case is the number 4.5. It will pass parsley's validation, but not HTML5's.

Test page for HTML5's input type="number": http://www.w3schools.com/html/tryit.asp?filename=tryhtml5_input_type_number

**Comment by almogdesign** [comment]
Has this been fixed ?

**Comment by marcandre** [comment]
Closing, as #731 has been merged.

**Comment by fsunset** [comment]
@guillaumepotier @marcandre - guys I have: 
```
<input type="number" data-parsley-min="0" data-parsley-type-message="Please enter a valid number" data-parsley-type="number" step="1" name="insideNightCount" id="insideNightCount" data-parsley-id="5950">
``` 
The *__data-parsley-type="number"__* validation is not working, -please notice I'm even using the ```step="1"``` attribute-. I already have latest code ```2.0.7```.

Thanks for the help!

**Comment by marcandre** [comment]
@fsunset Same as #874?

**Comment by fsunset** [comment]
Thanks for the fast reply @marcandre. After know [this](issuecomment-86518813) I think I'm going to see if I can change the ```type``` attribute :|
