### ISSUE TITLE
Error message does not dissapear when a auto-fill value is selected by using the Tab key

### ISSUE THREAD

**Issue by thorhallur** [guillaumepotier/Parsley.js#509]
Thanks for a great validator!

One thing I'm running into - with required fields, it marks it red with error box and usually those markings disappear once the user enters a value.  The problem case is with Auto-Fill values. If a value is selected from the list using the TAB key, the error markings do not disappear for some reason.  I'm using Google Chrome on MacBook Air.

Thanks!
Thor.

**Comment by roshancp360** [comment]
In autofill function add this code to validate the autofill fields again:

    ```
function autofill_function_name(){
       your code;
       $("#autofill_field_name").parsley().validate();
    }
```
