### ISSUE TITLE
Parsley doesn't adapt when adding attribute with Jquery

### ISSUE THREAD

**Issue by lucasbeef** [guillaumepotier/Parsley.js#52]
Hi, here is my situation : 
One field of my form is mandatory only if a radio button is at a particular value.

So i add/remove the attribute required="required" according to the value of my radio button. I do so using the jquery methods attr() and removeAttr().

When i check my DOM this attributes toogles exactly like I want, but parsley doesn't seems to adapt as it will always ignore the attribute modifications.
(but it is working just fine otherwise, good job btw)

It might come from my code as I am quite a newbie in JS/JQuey but i really dont understand what i got wrong.

Thanks

**Comment by himleyb85** [comment]
Having similar problem, and using the JQuery.data('params', 'here') didn't work for me, the way you described in your stackoverflow answer.  You can see my issue [here](http://stackoverflow.com/questions/29684804/getting-two-errors-using-parsley-js-to-add-validators-to-fields-that-are-dynamic).

**Comment by guillaumepotier** [comment]
I saw that @marcandre answered your question on SO. Cloning field is a bad idea with Parsley, and we cannot do much on Parsley's side to allow this behaviour :( Good news, there are plenty of other solutions than cloning :) Hope you found a way.

Best
