### ISSUE TITLE
data-parsley-errors-container and id with a colon

### ISSUE THREAD

**Issue by konstlepa** [guillaumepotier/Parsley.js#526]
Hi.

errorsContainer doesn't understand id with a colon. Look at http://jsbin.com/qexolabo/1/edit?html,output . 
Firefox's output: TypeError: b.options.errorsContainer is not a function.

Thanks

NB: JavaServer Faces appends form's id to a component automatically. For instance, login-form:username, login-form:password and so on.

**Comment by evisong** [comment]
Glad I find this old issue. My `data-parsley-equalto="#password"` just didn't work, until I changed it to `data-parsley-equalto="input[id='password']"` according to above hint.

Could you please also update this in the doc: http://parsleyjs.org/doc/index.html#psly-validators-list ? 

Thanks.

**Comment by marcandre** [comment]
@evisong AFAIK, `#password` should work, this issue is only if the ID contains a colon.

**Comment by evisong** [comment]
Strange, `#password` doesn't work in my Thymleaf (with SpringMVC) rendered code.

**Comment by guillaumepotier** [comment]
Could you please share a pastebin or jsfiddle (or live page of yours) in order to look deeper into this problem?

Thx
