### ISSUE TITLE
Some URLs do fail the the regexp check

### ISSUE THREAD

**Issue by medihack** [guillaumepotier/Parsley.js#530]
Some URLs do fail your [url regular expression](https://github.com/guillaumepotier/Parsley.js/blob/master/src/parsley/validator.js#L130) check. For example the URL `http://192.168.1.1/foo/bar` does fail as the regexp expects a top level domain. Maybe something like `/(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}(\.[a-z]{2,4})?\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/i` would be more appropriate.

**Comment by marcandre** [comment]
Should be better now.
