### ISSUE TITLE
parsley.remote.js: get custom error message from ajax response

### ISSUE THREAD

**Issue by StAn187** [guillaumepotier/Parsley.js#560]
It would be great if one could pass an error message to the corresponding form field via a json property returned by an ajax call. I guess this was possible in parsley 1.x but the parsley.remote.js plugin does not have this capability. Therefore I have to override "_remote" and "_handleRemoteResult" functions with my own - slightly altered - implementation.

in "_remote"

```javascript
// ...
promise = $.ajax($.extend(true, {}, {
         url: that.options.remote,
         data: data,
         type: 'GET'
      }, that.options.remoteOptions || {}));

      // Depending on promise result, manage `validationResult` for UI
      promise
         .done(function (data) {  // <--- pass the response to handleRemoteResult
            that._handleRemoteResult(true, deferred, data);
         })
         .fail(function (data) {  // <--- pass the response to handleRemoteResult
            that._handleRemoteResult(false, deferred, data);
         });
// ...
```
in _handleRemoteResult:

````javascript
_handleRemoteResult: function (status, deferred, response) {
// ...
if (status) {
// ...
} else if ('undefined' !== typeof response.responseJSON) {
    this.options.errorMessage = response.responseJSON.error.message;
}
// ...
```

Would be cool if parsley.remote.js would be able to show custom error messages out-of-the-box.

**Comment by marcandre** [comment]
It's now very easy to do this with a custom validator.
Say a json service returns  `{ok: true}` for valid fields, and `{error: "custom-error message"}` for errors, you could:

    validateString: function(value, requirement) {
        $.ajax('my-url', {value: value}).then(function(data) {
          if(data.ok)
           return true;
         return $.Deferred.reject(data.error).promise();
        }
