### ISSUE TITLE
"You must bind Parsley on an existing element." on a blank page ?

### ISSUE THREAD

**Issue by rizkytahara** [guillaumepotier/Parsley.js#562]
Hi,

I'm upgrading parsley to version 2.

I have a blank page that load a jQuery and parsley. After that load, I got a warning in console: "You must bind Parsley on an existing element." 
Why I'm getting that warning?

Here is a fiddle: http://jsfiddle.net/xtSK5/

**Comment by bnomei** [comment]
@peef is right. still there when using js init.

**Comment by marcandre** [comment]
This will happen when calling `parsley()` on an empty jQuery set.
What should it do in that circumstance?

**Comment by vphantom** [comment]
This error message is hard-coded at two distinct places:

- `src/parsley/main.js` line 50.  I don't see the relevance in emitting a warning when operating on a valid jQuery set that happens to be empty, which is a very common situation.

- `src/parsley/factory.js` line 30 is internally involed by the above.  Clearly if _that_ point is reached, issuing a warning does make sense.

I'll try a PR.
