### ISSUE TITLE
classHandler doesn't seem to work if two fields share the same element

### ISSUE THREAD

**Issue by stringbeans** [guillaumepotier/Parsley.js#573]
Hi,

I'm using Twitter bootstrap 3.0 and selectize.js.

My markup:

```
<div class='form-group col-sm-4'>
    <label for="quoteFor">Quote For</label>
    <select class='selectize' id='quoteFor' name='quoteFor' data-parsley-required='true'>
        <option value='1'>A</option>
        <option value='2'>B</option>
    </select>
</div>
```

I initialize #quoteFor with selectize.js...

```
#("#quoteFor").selectize();
```

Selectize will hide the original select field, and essentially append some additional markup to the parent container div.form-group that includes an input text field.

For my parsley configuration I have the following:

```
this.$el.parsley({

    successClass: '',
    errorClass: 'has-error',
    trigger: "change",

    classHandler: function(parsleyField) {              
        return parsleyField.$element.closest(".form-group");
    },

    errorsWrapper: "", //disable error message
    errorTemplate: "" //disable error message
});
```

As you can see, it should be adding the "has-error" class to the div.form-group element when there is an error, but it doesnt :( 

It looks like there is some sort of bug when two fields share the same classHandler element. 

Right now I have two ways around this... 
1) Change the classHandler to return parsleyField.$element.parent(). I don't like this solution because the immediate parent is not always what I want.
2) setting the "excluded" default option to include the input text field that selectize creates. this is a good solution for now, but I believe this bug should be fixed :)

Thanks for taking the time to read this! I love this library

**Comment by Aure77** [comment]
Any news about this enhancement ? I am experiencing similar problem with 2 field that share same classHandler element. I am using latest parsley version.

**Comment by MelentQ** [comment]
I found a solution
Add `data-parsley-excluded` attribute to the library-generated input
Here is an example for Choices.js
```js
new Choices(container, {
  searchEnabled: true,
  callbackOnCreateTemplates: () => ({
    input(...args) {
      const input = Choices.defaults.templates.input.call(this, ...args);
      Object.assign(input.dataset, {
        parsleyExcluded: true,
      });
      return input;
    },
  }),
})
```

[Choices.js docs](https://github.com/Choices-js/Choices?tab=readme-ov-file#callbackoncreatetemplates)
[Parsley.js docs](https://parsleyjs.org/doc/index.html#usage-field)
