### ISSUE TITLE
Feature? make errorsWrapper and errorsTemplate empty

### ISSUE THREAD

**Issue by andywenk** [guillaumepotier/Parsley.js#580]
I have the following options:

    @options =
        priorityEnabled: true
        errorClass: 'error'
        errorsWrapper: '<span></span>'
        errorTemplate: '<span></span>'
        errorsContainer: (ParsleyField) =>
           ParsleyField.$element.parent().next()

As I am defining the errorContainer by myself, I already have the markup I need to display the error message. So I don't need extra tags in errorsWrapper and  errorsTemplate defined. But when leaving them blank like errorsWrapper: '', the error message will not be displayed.

I suggest to make this possible. This would for sure require the dependency to a defined errorsContainer.

**Comment by marcandre** [comment]
You can have more than one error on one field, so having an empty `template` seems like a bad idea.
Moreover in many places in the code, the wrapper and templates are expected to be a DOM elements.
Closing, will reopen if you can show actual problems with having those `<span>` like in your example.
