### ISSUE TITLE
custom namespace -multiple doesn't re-evaluate correctly

### ISSUE THREAD

**Issue by mstduff** [guillaumepotier/Parsley.js#595]
stripped down fiddle: http://jsfiddle.net/4M7Un/1/

when using a custom namespace, if you have a required group of radios (havnt tried other types of multiple, assuming same issue). if you fail validation, it never re-evaluates when one of the required radios are now checked.

works when not using custom namespace.

**Comment by telesma** [comment]
Doesn‘t seem to work anymore with single checkbox fields if I have a custom namespace. (v2.3.5)

**Comment by marcandre** [comment]
@telesma could you provide a codepen/jsfiddle please?

**Comment by telesma** [comment]
Sorry, wrong alert. Works for me now.
