### ISSUE TITLE
Add validator with referenced field

### ISSUE THREAD

**Issue by goffreder** [guillaumepotier/Parsley.js#605]
It could be useful to add a couple of validators that check other field's, so that if you want to validate a 'range' form you can specify that 'from' value must be less than 'to' value and viceversa.

I'm trying to add these constraints myself, I'm almost there but I'm missing one last step. My work is exposed here: http://stackoverflow.com/questions/22838235/add-parsley-js-validator-with-referenced-field. Is this the right way to achieve what I want?

**Comment by marcandre** [comment]
Closing, answer in SO thread.
