### ISSUE TITLE
Access to error message(s)

### ISSUE THREAD

**Issue by PureDude** [guillaumepotier/Parsley.js#607]
How do I get access to the error message(s) in following context. 
e.$element.data('error-message') doesn't work. It would be great if you had a solution!

```
$.listen('parsley:field:error', function (e) {

    errorMsg = e.$element.data('error-message');

    e.$element
        .attr('data-content', errorMsg)
        .popover('show');

});
```

**Comment by btburton42** [comment]
@guillaumepotier i have multiple constraints on a single element (min-length, alphanum, required, etc). is there any way to currently return an array of all the unsatisfied constraints on an element?
