### ISSUE TITLE
Error message on number input.

### ISSUE THREAD

**Issue by vsn4ik** [guillaumepotier/Parsley.js#609]
On `<input type="number" required>` if value not equal integer, validation message not correct.

Reproduce issue:
1. http://jsfiddle.net/S34G3/1
2. Print on input some text (not integer), for example: 'some_text'.
3. Click submit.
4. Message "This value is required." not correct.

**Comment by marcandre** [comment]
I don't think there's a satisfactory solution for this, beyond what's been done already (#874).
