### ISSUE TITLE
Trouble Declaring Constraints With Bind Plugin

### ISSUE THREAD

**Issue by aedenj** [guillaumepotier/Parsley.js#620]
@guillaumepotier In this issue

https://github.com/guillaumepotier/Parsley.js/issues/610#issuecomment-41220793

you suggested using the bind plugin. I tried specifying constraints in the following tow ways

```javascript
$('form').parsley({ fields: {
   '#username' : { required: true },
   '#password' : { required: true }
}});
```

```javascript
 window.ParsleyConfig = {
   fields: {
     '#username':{ required: true },
     '#password':{ required: true }
}};
```
Only the last validator in both ways of specifying them above seem to fire.  Thoughts? Thank You.

**Comment by marcandre** [comment]
Not too sure it answers the question, but IMO the `bind` plugin is a misfeature.

To do what you want, you can simply set the `options` on the field directly: `$('my-field').parsley().options.required = true`.

Closing this, will reopen if need be
