### ISSUE TITLE
remote validation limited support on rest style URL

### ISSUE THREAD

**Issue by xfcjscn** [guillaumepotier/Parsley.js#627]
For rest style URLs, normally they are the combination of baseURL and resource ID.
E.g. http://xxx.com/books/1
And the resource ID normally populated with the input's value. 
In this case, an interface to manipulate the URL is required. But currently this is not supported in remote validator. Can this be added?

**Comment by marcandre** [comment]
This is now easy to do in `master`, with `url: "http://api/checkvatid/{value}"`
