### ISSUE TITLE
Parsley Extension API not elegant

### ISSUE THREAD

**Issue by xfcjscn** [guillaumepotier/Parsley.js#628]
When use AMD with Parsley, its easy to be understand to get ParsleyExtention depends on Parsley. But if ParsleyExtension(e.g. asyncValidators) maintained in AMD module, it can not depends on Parsley, since addAsyncValidator need to be invoked on parsleyFormInstance.

**Comment by marcandre** [comment]
Closing. We'll reopen if there's enough feedback to understand.
