### ISSUE TITLE
how i tell parsley to deal with it when i use javasript add a validate attribute

### ISSUE THREAD

**Issue by bruceliang** [guillaumepotier/Parsley.js#631]
<  input value="123" type="number" name="number" parsley-min="1"
				parsley-trigger="change" class="form-control" required
				placeholder="数量(必填)" id="number" />
when I use 
$("#number").attr("parsley-max",10);
parsley  can not validate the input.

**Comment by marcandre** [comment]
Please update to parsley 2.0 and use `data-parsley-min` and `data-parsley-max`, it should all work.
