### ISSUE TITLE
.addError still lets me submit the form

### ISSUE THREAD

**Issue by jnsandrew** [guillaumepotier/Parsley.js#636]
I've added 

var emailField = $('#id_email').parsley();
window.ParsleyUI.addError(emailField, "emailError", "Your email address isn't valid");

to my form (I'm trying to integrate it with MailGun Validator), it shows the error message but it will still let me submit the form. Have I missed something?

**Comment by marcandre** [comment]
I think this issue can be closed now. If I'm mistaken, ideally open a new one with current state. Thanks.
