### ISSUE TITLE
Custom error message for field of type 'email' not working

### ISSUE THREAD

**Issue by mrsippy** [guillaumepotier/Parsley.js#646]
Hi,

I'm currently integrating Parsley for a site, and am having a problem setting a custom error message for an email field. I also have a 'required' constraint on this field, with an accompanying error message, and that works, but when the email address is not valid I'm seeing the default "This value should be a valid email." error message rather than the one I've set. My field looks like this:

`<input class="form-control" data-parsley-required data-parsley-type="email" data-parsley-required-message="email address required" data-parsley-email-message="must be a valid email address" name="email" type="text" id="email">`

Many thanks -

**Comment by martin-g** [comment]
I've been tripped by this too.
The documentation at http://parsleyjs.org/doc/index.html#ui-for-field
> Validator error message #2.0	data-parsley-`constraint`-message="my message"	Customize the error message for the field constraint. eg: data-parsley-required-message="this field is required"

is a bit confusing here.

**Comment by fabiocaccamo** [comment]
How to do this via js instead of via DOM?

**Comment by marcandre** [comment]
> How to do this via js instead of using DOM?

`...({requiredMessage: '...'})`

Questions on StackOverflow please.

**Comment by yabdab** [comment]
This does not appear to be a fix, but a work around. What if we want a custom "required" message AND a custom "email" message?

**Comment by marcandre** [comment]
It's related to the name of the validator: `data-parsley-<validator name>-message`.
