### ISSUE TITLE
Passing additional dynamic data to the remote validator

### ISSUE THREAD

**Issue by KimPrince** [guillaumepotier/Parsley.js#648]
It seems to me that we can not pass a dynamic value via ajax to the remote validator, is that correct?  For example, in the following code ...

    data-parsley-remote-options='{ "type": "POST", "dataType": "jsonp", "data": { "token": "value" } }'

... the "value" of the token can be a literal (such as 'myparam'), but can not be the value of another form element (such as $('user').val()).

Using the javascript method I tried making the "value" a function, but was unsuccessful there too.

Is there a way to pass a dynamic value?  Its important for a remote validator.

Here are a couple of related stackoverflow questions:

http://stackoverflow.com/questions/23690448/parsley-remote-and-additional-parameters
http://stackoverflow.com/questions/23675442/remote-validation-for-a-field-which-depends-on-others

**Comment by marcandre** [comment]
Closing, as this is now fixed.

**Comment by nsamuels0510** [comment]
How is this closed..maybe I am missing something? How are you able to pass dynamic parameters with the remote validator? Are there any coding examples of how to do this pass $('#test').val() as one of the parameters for the remote validation url? For example...
{ "type": "POST", "dataType": "jsonp", "data": { "FirstParam": $('#FirstParam').val(), "SecondParam" :$('#SecondParam').val()} }

**Comment by marcandre** [comment]
@nsamuels0510  Check http://parsleyjs.org/doc/index.html#remote-events

**Comment by nsamuels0510** [comment]
Thank you for your quick reply, I understand to match the name of the input that is being validated to the param of the url call. But I need to pass the value of another input to the same url call, I tried adding the name of that param to the other input not being validated but i need for the call but that is not working.

**Comment by marcandre** [comment]
@nsamuels0510 Questions -> StackOverflow please, thanks

**Comment by nsamuels0510** [comment]
Sorry! I only asked on this board because all stackoverflow questions about passing extra dynamic parameters with parsley remote pointed to a lot of these issues that are all marked closed with no answers or coding examples! Thanks anyway!
