### ISSUE TITLE
Can not updateError on remote validators

### ISSUE THREAD

**Issue by KimPrince** [guillaumepotier/Parsley.js#652]
updateError does not seem to apply for remote validators.  The following code does not work.  The error message remains "This value seems to be invalid."

    window.ParsleyExtend = {
        asyncValidators: {
            emailallowed: {
            fn: function (xhr) {
                if (xhr.responseJSON.code == 'true') return true;
                window.ParsleyUI.updateError($('#email').parsley(), 'remote', 'That email is already in use');
                return false;
            },
            url: '/invitation/allowed'
        }
    }
}

**Comment by marcandre** [comment]
The way to do this is with `addMessage`. No need to call `updateError`
