### ISSUE TITLE
Count of valid or invalid fields

### ISSUE THREAD

**Issue by martinpesout** [guillaumepotier/Parsley.js#673]
Hi, 

is there any way how to get a number of valid/invalid fields before submitting whole form by submit button? I need to create some progress bar in the sidebar and update it automatically during filling my form. Is there any way how to do it with Parsley.js? Maybe any asynchronous solution? 

Note: I need to get only these numbers, not trigger validation messages.

Thanks for your help.

Martin

**Comment by ibnuh** [comment]
I found a solution, might be useful for someone

```
var countErrors = 0;
window.Parsley.on('field:error', function () {
    countErrors++;
});
```
