### ISSUE TITLE
removing parsley-error on condition

### ISSUE THREAD

**Issue by pasupathy** [guillaumepotier/Parsley.js#679]
Hi, i have a form with few header form fields with  an  input type=file and rows of line item forms fields, I want to do the following : 
1. if no file uploaded, validate the form - ( i was able to do this by adding the attribute required in both header and lineitem form fields) 
2. if file upload, disable the lineitem form fields only - ( i was able only to remove the error message divs, the required attribute and the parsley-error class is not removable )

 if ( $("#fielupload").val().length !==0 ){	
	  $( ".lineitemfields" ).each(function() {
  var aid = $(this).attr("data-parsley-id");
		   $('#parsley-id-'+aid).remove();	
$("#"+this.id).removeClass('parsley-error');		 
$("#"+this.id).removeAttr('required');
$("#"+this.id).removeAttr('data-parsley-id');

});

How to remove the parsley-error class from the lineitem fields

**Comment by marcandre** [comment]
If you haven't done so, please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)
