### ISSUE TITLE
How do I use a required and a not validated error message on an email field?

### ISSUE THREAD

**Issue by Eworm** [guillaumepotier/Parsley.js#680]
Hi,

As I understand it, this is the way I should add custom error messages:
```<input type="email" data-parsley-trigger="change" data-parsley-email-message="Not validated" data-parsley-required-message="This is required" required>```

Unfortunately this doesn't work. I see the 'This is required' message, but when validation fails I get the standard 'This value should be a valid email.' message. How should I use this?

Thanks!

**Comment by marcandre** [comment]
You can use `data-parsley-type-message` for now, although this might change (see #840)
