### ISSUE TITLE
Checkbox/Radiobutton doesn't validate inside form but on whole page

### ISSUE THREAD

**Issue by johnvanhulsen** [guillaumepotier/Parsley.js#683]
Hi,

I have two forms on one page, with the same fields and names. A person can choose one form and all fields are required.

All the default text, email and tel elements are validating good but it seems that radio and checkbox-elements do not look to his parent form, no, it checks of the name of the element exists in the whole DOM of the page.

So radio and checkboxes with the same name aren't validating in the second form.

I made a jsbin demo with the problem:
http://jsbin.com/wemika/2/

**Comment by marcandre** [comment]
Sorry for the lack of feedback. Has been fixed [years ago](https://github.com/guillaumepotier/Parsley.js/commit/7734291d66158301af74fed4da29d67adcdb4fe4)
