### ISSUE TITLE
Please use jQuery to refer to jQuery and not $

### ISSUE THREAD

**Issue by kennypu** [guillaumepotier/Parsley.js#685]
including parsley.min.js with a regular Wordpress install will cause an 'undefined is not a function', since the file is using $ to reference jQuery.

**Comment by joelcdoyle** [comment]
I am still having this issue with the latest version of WordPress, Bones theme, and the latest Parsley.js

How is that possible?

**Comment by marcandre** [comment]
But this *is* the official Parsley.js repo.

**Comment by joelcdoyle** [comment]
Yep, you're right. I got confused. I'm using Parsley 2.0.6

**Comment by marcandre** [comment]
I'm not familiar with wordpress, but did you include jQuery?

**Comment by joelcdoyle** [comment]
Btw, parsley require attributes still work, without calling
```
$('#myform').parsley();
```
But, data-parsley-equalto="#confirm-password" , for example, does not work. Plus, I get 
```
undefined is not a function
```

**Comment by joelcdoyle** [comment]
jQuery is included in WordPress by default.

**Comment by marcandre** [comment]
Can you provide a link?

**Comment by joelcdoyle** [comment]
I wish I could, but it's a private project. :hankey:

**Comment by joelcdoyle** [comment]
Created a stack issue: https://github.com/guillaumepotier/Parsley.js/issues/685

**Comment by joelcdoyle** [comment]
Thanks @marcandre. Changing the document ready function fixed my problem.
