### ISSUE TITLE
Disable ParsleyFailedOnce Trigger after Successful Validation

### ISSUE THREAD

**Issue by boushley** [guillaumepotier/Parsley.js#692]
Currently once a field has failed validation [extra events are added](https://github.com/guillaumepotier/Parsley.js/blob/3ae35866031d565db28004c26ec82e4683c04b59/src/parsley/ui.js#L338) as triggers for validate.

This has a great and intuitive benefit of updating the UI while the user makes changes to reflect things being in a valid state, however it can cause some confusion around how often events like `parsley:field:success` are fired. If I provide a trigger value of `focusout` I would not expect `parsley:field:success` to be 

I would expect that once validation passes any `.ParsleyFailedOnce` events would be removed.

Has this been discussed before? Would a PR that adds this functionality as an option (removing .ParsleyFailedOnce hooks on success) be of interest for this project?

**Comment by marcandre** [comment]
Sorry for the lack of feedback. This has been fixed a long time ago. Thanks for reporting this!
