### ISSUE TITLE
data-required is not working while using dynamically in parsley validator

### ISSUE THREAD

**Issue by shankumars** [guillaumepotier/Parsley.js#695]
Hi 
 I am using the parsley validate plug-in to validate my form. But when I am add the attribute ' data-required="true" ' manually through jquery based on the radio button option select by client.

please any one help me or guide me right path for this problem.

thanks
Kumar Shanmugam

**Comment by MxRay** [comment]
I've got the same problem. I manually add `required` attribute only when user selected a certain option. I'm using parsley.js with Step Form Wizard [http://ajoke.cz/wizard2/site/index](url), and i need to validate manually added `required` before user moves to next step.

**Comment by marcandre** [comment]
For the scenario when there is a validation error showing and `myinput` is no longer required, then parsley needs to be called somehow.
The best way is probably to `$myinput.trigger('input')`, basically faking that the user has modified that input. If there's an error showing, validation will be redone.

Closing this, please provide CodePen if there's still an issue.

**Comment by MxRay** [comment]
New version of parsley.js(2.3.6) did the trick. It works ok, now.
