### ISSUE TITLE
Does Version 2.0 still support parsley.extend.js ?

### ISSUE THREAD

**Issue by CodingSamurai** [guillaumepotier/Parsley.js#701]
It's not clear from the documentation if the parsley.extend.js is still supported with Parsley 2.0.  If it's not then the missing LUHN validator from the new parsley.extras is a critical issue that will likely hold a number of people from upgrading.

**Comment by marcandre** [comment]
Closing, as this has been addressed

**Comment by marcandre** [comment]
Closing, as this has been addressed.
