### ISSUE TITLE
parsely breaks bootstrap radio-inline

### ISSUE THREAD

**Issue by bradrice** [guillaumepotier/Parsley.js#703]
For some reason even if the fields are not required parley is putting a <ul><li class=:ist-errors"> ... below each radio button and causing the inlines to not be inline.

The only way I got it to work was to put data-parsley-errors-container="#element" in each inline radio.

I tried data-parsley-errors-messages-disabled and it didn't seem to have any effect.

**Comment by safoorsafdar** [comment]
I'm facing the same issue to, any one able to resolve it?

**Comment by bradrice** [comment]
You can create a custom error element for your radio buttons.

**Comment by coogleyou** [comment]
I have the same problem too.
I add `data-parsley-errors-messages-disabled` to the field but nothing happen, the errors container is still there.
I think it's a bug.

**Comment by marcandre** [comment]
Which version of Parsley are you all using?
I'm asking because v2.1 should generate errors containers unless when needed
