### ISSUE TITLE
Tweak wrapper for UMD compatibility and correctly declare dependencies

### ISSUE THREAD

**Issue by willdady** [guillaumepotier/Parsley.js#708]
Can we get the AMD style wrapper tweaked so it's UMD compatible? This will allow the plugin to be loaded via AMD loaders (require.js, almond.js) as well as CommonJS style loaders (node, browserify, webpack).

See: https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

Also, package.json does not declare jquery as a dependency which seems odd since it's a hard-dependency and won't function correctly when loaded with node/browserify.

**Comment by joshlasdin** [comment]
+1

**Comment by marcandre** [comment]
I think [2.1.0-rc8](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc8) should be good. Let me now :smile:
