### ISSUE TITLE
Firefox not focusing correctly on validation error

### ISSUE THREAD

**Issue by dlichten** [guillaumepotier/Parsley.js#712]
When there are validation errors after submitting a form using Firefox (version 31), the focus does not work properly. It will focus the page slightly below where it should. Can't replicate the issue on Chrome or Safari.

**Comment by marcandre** [comment]
We are using jQuery's `focus`, so I doubt there's anything we can do. Please provide a fiddle illustrating the issue if you think there is :smile:
