### ISSUE TITLE
Fields being given the same random ID

### ISSUE THREAD

**Issue by ChrisSalt** [guillaumepotier/Parsley.js#715]
Due to the random ID generated for each field being a 4 digit number there is a large possibility of 2 fields being given the same ID. When this happens any validation that should apply to the second field will not occur.

For a form with 30 fields there is a 4% chance of this happening, 50 fields is 12%.. if the form has 300 fields this goes up to 99%, so if Parsley is used on very large forms it is pretty much guaranteed to happen.

If the ID has to be generated by a random number increasing the length of the ID to say 8 or 16 digits should significantly reduce the chances of this happening.

**Comment by marcandre** [comment]
Good point. Will be fixed in upcoming v2.1.
Thanks for reporting this!
