### ISSUE TITLE
Can't specify excluded form fields

### ISSUE THREAD

**Issue by roberttaraya** [guillaumepotier/Parsley.js#716]
in the docs it says that form fields can be excluded from parsley validation by using data-parsley-excluded.

when you set data-parsley-excluded using

    $('.vex-dialog-form').data('parsley-excluded', "input[type=button], input[type=submit], input[type=reset], input[type=hidden], [disabled], :hidden")
    
parsley still validates my hidden fields. but when you set data-parsley-excluded using

     $('.vex-dialog-form').attr('data-parsley-excluded', "input[type=button], input[type=submit], input[type=reset], input[type=hidden], [disabled], :hidden")
     
it works correctly, as advertised.

**Comment by marcandre** [comment]
You can *not* use `$.fn.data` to specify parsley settings, as it does not modify attributes (it only pulls them in first time it's called).
