### ISSUE TITLE
Move i18n to dist

### ISSUE THREAD

**Issue by bzmwillemsen** [guillaumepotier/Parsley.js#717]
I was wondering if the production build could be expanded to include the i18n files?

I'm would like to add the i18n files to jsDelivr, but they would prefer that they be minified and approved for release by being in the dist folder.

Thoughts?

cc: https://github.com/jsdelivr/jsdelivr/pull/1502

**Comment by guillaumepotier** [comment]
I'll look closer your PR this week end, it sounds really good though :)

Best

**Comment by marcandre** [comment]
The latest release now has `dist/i18n` :smile:
