### ISSUE TITLE
a caret or strudel in a text field with a pattern defined will pass validation

### ISSUE THREAD

**Issue by em0ney** [guillaumepotier/Parsley.js#719]
I have a field defined as below:

``` <input name="contactName" type="text" class="form-control" data-parsley-trigger="change" pattern="[a-zA-Z ,-_]+" required /> ```

Entering the value `#$#!&*()` or any part thereof, the validation appears to fail, as expected.

Adding either a `@` or `^` to this will cause the validation to pass.  While this does go away when matching the start and end of the line in the pattern, this should not pass as neither the strudel not the caret match the character class defined.

**Comment by marcandre** [comment]
You need to escape the `-`, otherwise you're including all characters between `,` and `_`, which include `@`, `^`, digits, etc...
Note: pattern is currently un-anchored, this will change, see #764
