### ISSUE TITLE
parsley remote validation don't call when group validation

### ISSUE THREAD

**Issue by thcao** [guillaumepotier/Parsley.js#720]
html:

< input data-parsley-group="step1" data-parsley-remote="" data-parsley-remote-validator="validateUsername" data-parsley-required="true" data-parsley-trigger="focusout" id="id_username" name="username" type="text" data-parsley-id="3571">

javascript
$('#id_username').parsley()
.addAsyncValidator('validateUsername', function (xhr) {
	        validated = (404 === xhr.status);
	    }, 'http://mycustomapiurl.ext';
--> this action still work when I input data on field

$('.next').on('click', function () {
           if (false == $('#demo_form').parsley().validate('step1'))
                     return false;
});
--> it didn't call username remote validation

**Comment by marcandre** [comment]
Closing this, as Parsley has changed tremendously, `group` is better handled, so are `remote` validations, so I expect this has been fixed. Please reopen if still an issue in `2.2.0`. Thanks!
