### ISSUE TITLE
How to prevent firing of validtion

### ISSUE THREAD

**Issue by chandrikakandru** [guillaumepotier/Parsley.js#733]
I have two panel in same page.I want to fire validation for only one panel.
Now i am using parsley.js latest version.I am facing problem as, i don't want to fire validation when button in first panel is clicked.I want to fire validation when button in second panel is firing.Both panels in same form.

**Comment by marcandre** [comment]
If you haven't figure out a way yet, please ask this question on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)

**Comment by marcandre** [comment]
Also check http://parsleyjs.org/doc/examples/multisteps.html
