### ISSUE TITLE
Data Attributes not working

### ISSUE THREAD

**Issue by jsnarroyo** [guillaumepotier/Parsley.js#742]
Okay, I've used parsley's data attributed before and have had not issues. When I use the "min=6" attribute parsley just ignores it and as soon as i enter 1 character is validates?

can been seen here
http://madmen6raphics.com/clients/bestbuilding/free-estimates.html

thanks,
Jason

**Comment by marcandre** [comment]
I believe that with the `required` you added, this works as you want it. Otherwise there's an option to validate empty fields.
