### ISSUE TITLE
Remote Validation on iPad Safari/Chrome freezes the browser

### ISSUE THREAD

**Issue by marvindanig** [guillaumepotier/Parsley.js#746]
I am using a custom validator with parsley.remote to check uniqueness of email address during user signup. The things works as expected on desktop Safari and Google Chrome. 

However, on the iPad/iPhone iOS 8.0.2 it fails miserably and freezes up the browser (or sometimes even the device). This happens especially when an invalid value is typed into the field. It's impossible to edit, type, focus into URL or even close the browser then.

Anyone else facing this issue with parsley.js on tablets/iPad?

**Comment by nodefortytwo** [comment]
I am having the same issue with parsely v2

**Comment by marcandre** [comment]
Has any of you tried the iOS simulator, or does it only freeze actual devices?

**Comment by nodefortytwo** [comment]
I actually don't think its the remote validation. 

Basically it seems that focusing on an element doesn't cause it to scroll to the item. on iPhone (emulator and real device) it simply doesn't scroll but the page is still responsive. on iPad the page freezes and a reload is required.

**Comment by F1sn1k** [comment]
@nodefortytwo did you manage to solve parsley validation focus for iPhone devices ?

**Comment by marcandre** [comment]
Sorry everyone that this is not yet resolved. I'm closing this in favor of #938, please follow that issue
