### ISSUE TITLE
Type="number" not showing error when letters are entered

### ISSUE THREAD

**Issue by epigeyre** [guillaumepotier/Parsley.js#751]
Hi and thanks for the plugin, it's really great!

I don't quite understand though, I have an input type="number" but when I put letters (a,b,c...) it does not show an error (it doesn't validate either). Is it normal behavior?

**Comment by Raulvv** [comment]
If you are talking on Chrome and Firefox it should work, can you show the code please? Also its important to know what version are you using.

**Comment by marcandre** [comment]
This is now in the documentation. Nothing we can do about that... See #874
Thanks
