### ISSUE TITLE
Custom message for URL field type?

### ISSUE THREAD

**Issue by deronsizemore** [guillaumepotier/Parsley.js#753]
I was wondering if there's an attribute for customizing the message for the field type? For example, on my "URL" field now, if someone enters an invalid URL, it will return "this value should be a valid url."

But what if i want to change that? Is that possible?

**Comment by marcandre** [comment]
@Dayjo is correct. 

Closing, but I'm taking note of @Dayjo's request.

**Comment by deronsizemore** [comment]
Thanks @Dayjo. I apologize, but could you be a littler more specific on where I would that line of code to get the desired result?

**Comment by marcandre** [comment]
@deronsizemore anywhere after parsley has loaded. Did you try it?

**Comment by deronsizemore** [comment]
@marcandre Sorry, I did try it but for whatever reason I was under the impression it was supposed to go into the input tag in place of data-parsley-required-message="" parameter. I got it sorted out though after your response; never occurred to me to put it in script tag below where parsley.js is called. I did that and it works now. Sorry, just not real experienced with JS stuff. Thanks.

**Comment by marcandre** [comment]
:+1:
