### ISSUE TITLE
Parsley 2 might be causing JSON traversing conflict in IE8

### ISSUE THREAD

**Issue by puzumaki** [guillaumepotier/Parsley.js#759]
We are using Bootstrap 3 for pulling in carousels with content that is delivered in JSON format, and when we migrated our Parsley script to version 2, IE8 could no longer display the carousels.  Investigating this, oddly any data that is in an array in the delivered JSON array (so a nested array) cannot be found.  This is only an issue in IE8 (and possibly older) that we can tell.

An example is at: https://apps.hclib.org/catalog/record.cfm?id=547083
(Carousels exist in Details and You May Also Like)

For the carousel, we are pulling some of the data from data.meta.author.fullName, and the error message in IE8 is "Unable to get value of the property 'author': object is null or undefined".  But as soon as we take out Parsley (which is being used on the page), it starts working again.

Do you have any idea why this might be happening?  Any guidance would be greatly appreciated.

**Comment by marcandre** [comment]
I also don't quite see how that's possible. Still the case with a newer version? Version 2 has some extensions to jQuery that could potentially cause conflicts (`$.emit`, `$.listen`), but you'd have errors in the console and it would be cross platform. Newer versions would show a deprecated warning in the console.
In any case, we aren't in a position to pin this down, so I'll close this.
