### ISSUE TITLE
Force field to invalid or change parsley:field:success event behavior?

### ISSUE THREAD

**Issue by studzinek** [guillaumepotier/Parsley.js#760]
Hi,

I would like to change fields to invalid or change parsley:field:success event to fire up even when valid (green) fields are changed.
Is there a something like unvalidate(force) or invalid(force)?

My case:
I have 2 input fields (group). This fields have to contain numbers. I can check it with parsley and this is OK.
But the sum of this 2 fields have to be 50. I can check this sum by using parsley:form:validated event.
When this event fires up I can check if sum is equal 50, if not I can prevent sending this form and show a message. It's ok too.
But how I can set this inputs to 'invalid' state? I can set .parsley-error class with jquery to 'imitate' invalid fields but I'd like to use parsley:field:success event. It won't fire up if I edit valid (green) input field.
I would like to change fields to invalid or change parsley:field:success event to fireing up even on editing valid (green) fields.

I think that parsley:field:success event should be called even when valid field (green) is edited (now it fires only on editing invalid fields (red)). This would solve my problem because I could calculate sum if one of fields will be changed.
This behaviour for parsley:field:success event will be helpfull for other forms.
For example: http://parsleyjs.org/doc/examples/events.html
1. If I put 'as' as firstname and 'asdf' as a lastname I will get an error on submit (this is ok),
2. if I change firstname to 'asdf' field becomes green (this is ok),
3. if I change lastname to 'as' field will stay green (it's not ok in my opinion) -> new error will be shown after submit. I think field should become red before submit.

Could you help me?
Maybe my whole idea is wrong (and I can do this in other way)?

**Comment by marcandre** [comment]
This is a longstanding problem that is next on the agenda.
I'm closing this, let's discuss in #839
