### ISSUE TITLE
Source Map on minified JS

### ISSUE THREAD

**Issue by Dayjo** [guillaumepotier/Parsley.js#762]
It would be great if the minified version of the JS had source map. I believe this should be relatively easy to add to the Gruntfile, although I've yet to investigate further.

**Comment by marcandre** [comment]
[Sounds simple enough](http://code.tutsplus.com/tutorials/source-maps-101--net-29173), but I've never done this. Would be nice. PR welcome.

**Comment by marcandre** [comment]
Done. Thanks

**Comment by Dayjo** [comment]
Nice one :+1:
