### ISSUE TITLE
Unable to validate text field 

### ISSUE THREAD

**Issue by abhisg2007** [guillaumepotier/Parsley.js#763]
Hi,
I need to validate text field using parsley like If some one write PO BOX in the text field I have to show the error message "we don't accept PO BOX Address please enter correct address".
Can you guys please let me know how can I apply this validation on my text box.

**Comment by marcandre** [comment]
Please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Ideally **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)
