### ISSUE TITLE
Parsley's pattern attribute handling doesn't match the HTML5 spec

### ISSUE THREAD

**Issue by liamjones** [guillaumepotier/Parsley.js#764]
The HTML5 spec states the following for the [pattern attribute](http://www.w3.org/TR/html/forms.html#attr-input-pattern):

> The compiled pattern regular expression, when matched against a string, must have its start anchored to the start of the string and its end anchored to the end of the string.
>
> **Note:** This implies that the regular expression language used for this attribute is the same as that used in JavaScript, except that the pattern attribute is matched against the entire value, not just any subset (somewhat as if it implied a ``^(?:`` at the start of the pattern and a ``)$`` at the end).

Parsley doesn't anchor the regexp it reads out of a pattern attribute so patterns which would result in a failure with raw HTML5 browser validation start allowing values through once Parsley is included.

See test case: http://jsfiddle.net/9kg8g9w0/3/

If Parsley only used it's own attributes (data-parsley-pattern) then I think this differing behaviour would be fine. Since it's pulling from HTML5 validation properties I'd personally expect its behaviour to match that of a HTML5 validation on the same property.

**Comment by marcandre** [comment]
I agree, at least for "standard" regex.
Parsley also extends regex by accepting a full pattern (e.g. "/hello/i"). These could remain unanchored?
v2.1/3.0 would be a good occasion for this.

**Comment by liamjones** [comment]
Agreed, there should probably be some way of specifying a full pattern as well. I'm wondering if it should only be allowed via a parsley specific attribute though?

My thinking; if it's specified in the pattern attribute and the page ends up falling back to HTML5 validation (say, Parsley doesn't load or JS is disabled) then the validation is going to behave differently. E.g. `/.{0.5}/i` in the pattern attribute would look for the literal `/` and `i` characters within your input (and it's still anchored automatically by the browser too).

**Comment by marcandre** [comment]
It's true that we're "incompatible" if pattern is set to `/.{0.5}/i` as this will be interpreted literally in HTML5. On the other hand, I just can't see anyone using such a pattern for real. If they really need that (say they want someone to enter a regex?!?), they can escape the `/`, like `\/.{0.5}/i` would be the same in parsley and html5.
In short, I can sleep peacefully with such an "incompatibility", it should just be noted in the specs.
The main question though is this: should "extended" regex be anchored too or not?

**Comment by marcandre** [comment]
@guillaumepotier Any opinion on the above?

**Comment by guillaumepotier** [comment]
I like to current `data-parsley-pattern` behavior, highly permissive and powerful. The html5 incompatibility though is a problem.

Maybe we might keep `data-parsley-pattern` like it is, but do some extra work when binding html5 `pattern` attribute to this validator, and manually anchoring like the html5 spec states.

Dunno if there is an elegant way to do it though and if it would make sense.

**Comment by marcandre** [comment]
@guillaumepotier  It's your call!

I had started coding a change to anchor patterns, except if they look like `/pattern/flag` (see [branch](https://github.com/guillaumepotier/Parsley.js/tree/anchored_pattern)), but if you'd rather introduce a difference between `pattern` and `data-parsley-pattern` that could work too.

So IIUC your proposal, `pattern="a"` would be equivalent to `data-parsley-pattern="^a$"`?
And `pattern="/a/"` would be equivalent to `data-parsley-pattern="^/a/$"`, i.e. a regex like `/^\/a\/$/`?

**Comment by marcandre** [comment]
Either way, these are potentially breaking changes...

**Comment by marcandre** [comment]
Merged in `master`. Patterns are now anchored, unless they are of the form "/pattern/flags"
