### ISSUE TITLE
Range validator will not accept 0  - again?

### ISSUE THREAD

**Issue by fsunset** [guillaumepotier/Parsley.js#770]
@guillaumepotier There is a problem with this again or is it totally fixed? I've been trying to do it without success and I'd like to know if finally you'd fixed this bug. 
Thanks.

**Comment by marcandre** [comment]
Appears to work with current version, i.e. `$('<input type="string" data-parsley-range="[0,4]" value="0">').parsley().isValid()` returns `true`.
Let me know if I'm missing something.

**Comment by Umangksharma** [comment]
<input type="text" data-parsley-range="[1,4]" value="0"> this is not showing out of range error. For some reason 0 is accepted.
