### ISSUE TITLE
1 Test fails on master on web based test

### ISSUE THREAD

**Issue by Dayjo** [guillaumepotier/Parsley.js#772]
The following test is failing on the master branch when I run `/test/index.html` in Chrome 38.0.2125.122 and Firefox 33.1.1

![](http://cl.ly/image/2c0X431E0Y43/Image%202014-11-20%20at%2012.17.48%20pm.png)

Not sure what it's related to, but wanted to raise this before I do a pull request in which this error still occurs (so I know it's not me). 

`npm test` seems to run fine.

**Comment by marcandre** [comment]
Should be fixed in `master`. Thanks for reporting this.
