### ISSUE TITLE
Problem with multiple checkboxes array

### ISSUE THREAD

**Issue by dlgresults** [guillaumepotier/Parsley.js#779]
Hey hows it going, I'm getting an error when trying to set up multiple checkboxes. I'm naming the checkboxes with an array name 

example:    <input type="checkbox" name="choose[]" value="x">   but its not working when using the brackets. It only works when the brackets are removed.

**Comment by marcandre** [comment]
Appear [to work](http://jsfiddle.net/marcandre/8payh4bn/). Let us know if we're missing something.
