### ISSUE TITLE
number validator is not locale aware

### ISSUE THREAD

**Issue by sargue** [guillaumepotier/Parsley.js#799]
The current 'number' validator is defined as this regular expression:

```
'^-?(?:\\d+|\\d{1,3}(?:,\\d{3})+)?(?:\\.\\d+)?$'
```

Which expects numbers in english locale, using a comma as a group separator and a dot as a fraction separator. That is locale dependent. I need exactly the opposite (catalan locale).

The locale packages should be able to change that along with the messages.

Maybe the solution would be to define all those regular expressions the same way the messages are stored (some dictionary) and be fetched in a locale aware fashion.

**Comment by Fargeau** [comment]
+1 for this issue

**Comment by crebuh** [comment]
+1 instead of 49.55 the validator should accept 49,55 as a valid number

Is there a workout at the moment to overwrite the current regex? I tried to change it from

```javascript
'^-?(?:\\d+|\\d{1,3}(?:,\\d{3})+)?(?:\\.\\d+)?$'
```

to

```javascript
'^-?(?:\\d+|\\d{1,3}(?:,\\d{3})+)?(?:\\,\\d+)?$'
```

without success

**Comment by guillaumepotier** [comment]
+1 this is a great idea. Maybe adding / creating L10n variable / file with this kind of information. Would be easy then to make some validators localization aware.

Unfortunately I'm currently running out of time and going on vacation for 1month+, so you'll need to think about it and maybe make a PR for that :)

Best

**Comment by sargue** [comment]
Maybe that should be aligned with the already existing i18n files which currently only deal with messages. I'm currently changing jobs (to [freelancing](https://sargue.net/cv/), BTW) and won't be able to look at it in some weeks but if no one can take it I will remind this to myself in a few weeks to try my first github PR.

**Comment by marcandre** [comment]
The `number` validator now follows the HTML5 spec, in particular no comma is accepted.
The `pattern` validator should probably be used, but I'm opened to feature requests.

**Comment by retorquere** [comment]
This also means that min & max won't work, correct?

**Comment by marcandre** [comment]
@retorquere Not sure what you mean exactly. `min` and `max` (and Parsley in general) uses `parseInt`. HTH.
