### ISSUE TITLE
Custom message for custom validator

### ISSUE THREAD

**Issue by jalandis** [guillaumepotier/Parsley.js#805]
Custom messages not working as expected with custom validators when containing hyphens.  Not sure if this is intended or a bug.
```
<input data-parsley-trigger="submit"
           data-parsley-length="[8, 16]"
           data-parsley-password-complexity="3"
           data-parsley-password-complexity-message="Custom error."
           type="password"
           value="">
```

```
window.ParsleyValidator.addValidator('passwordComplexity', function (value, requirement) {...}, 32);
```

**Comment by brunowego** [comment]
Inside validator, how access data attributes @jalandis? thanks.

**Comment by brunowego** [comment]
Any idea?

**Comment by marcandre** [comment]
@brunowego please realize that it would be best to
1) read the Readme and the Contributing guidelines, and thus ask questions on StackOverflow (as requested)
2) not post in issues that have been closed for months
3) post a question that is understandable, ideally with a working example
This is valid for any open source project, btw...

I also ignore why you ask the question specifically to @jalandis who was simply kind enough to signal a problem and provide a solution.

**Comment by brunowego** [comment]
Ok, thanks @marcandre
