### ISSUE TITLE
Group validation not working after first submit

### ISSUE THREAD

**Issue by ferjgar** [guillaumepotier/Parsley.js#812]
I'm trying to implement a multistep registration process using parsley for the validation. It's very similar to the official demo (http://parsleyjs.org/doc/examples/multisteps.html), but I need to bind the validation to the submit event to be able to capture it when the enter key is used.

The problem is that the first time it validates only the fields of the group specified, but the next ones it validates the entire form.

This can be tested here, just press submit twice: http://jsfiddle.net/n5q7n1yb/1/

**Comment by marcandre** [comment]
Multistep example has been modernized, so has Parsley... Closing this, please open new issue if needed.
Sorry about lack of response.
