### ISSUE TITLE
OptionFactory refactor

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#816]
Unless I'm mistaken, it is currently very unintuitive how to set a field option via JS after it has been initialized:

    // Either:
    $input.parsley().OptionsFactory.staticOptions.trimValue = true
    // or must be destroyed first:
    $input.parsley().destroy()
    $input.parsley({trimValue: true})

One can't simply change the options because these are reset by the `OptionFactory` by combining all different layers (e.g. global, form, field) of options.

An alternative approach to the OptionFactory approach would be to use a prototype chain instead. The global options would be the prototype of form data options, which in turn would be the prototype of the form static options, itself prototype of field data options, with the field static level being the last level.

The main advantage would be that it would allow setting options directly. For example, the following would work naturally:

    $input.parsley().options.trimValue = true

This would work as `actualizeOptions` would only change (in place) the values for the prototypes of `options`, and keep the own properties of `options` intact.

Another advantage would be that it fixes the fact that the static level (which combine default options and options passed as a parameter) is currently overridden by data options. Especially for the field level, it makes no sense to me that specific options passed via JS would be overridden by data options of the form...

I think the solution would also be quite elegant (and consume a bit less memory, but that's really negligible in the big scheme of things).

Before I work on the PR, does this sound good to you?

**Comment by guillaumepotier** [comment]
Hi,

OptionsFactory is by far the worst bit of Parsley 2.x. Like you clearly stated above, this is very unintuitive, a bit overcomplicated a rework would clearly help.
I agree too that javascript options should prevail on data binded values.

I might see what you want to do here, that seems great, it may be clearer with your PR. Hope actual tests would help you do this refactoring peacefully :)

Best

**Comment by marcandre** [comment]
Ok, so it wasn't too bad to write after all.

One drawback I didn't think of is that this all works beautifully, but I haven't coded for nested options. So someone doing `$field.parsley().options.validators.foo = function()` would actually modify the `ParsleyConfig.validators` object. I think `validators` is the only option that isn't flat, right?
