### ISSUE TITLE
Initiate Parsley using JQuery seems not working

### ISSUE THREAD

**Issue by imrefazekas** [guillaumepotier/Parsley.js#817]
Dear All,

I tried using the following form:

```jade
	#project-form
			.form-line
				input#project-name-field(type="text", placeholder="Name of the project", data-parsley-trim-value="true", data-parsley-required="true", data-parsley-length="[3, 50]", data-parsley-trigger="change")
			.form-block-wide
				textarea#project-details-field(rows="5", placeholder="Details about the project...", data-parsley-trim-value="true", data-parsley-required="true", data-parsley-length="[20, 1000]", data-parsley-trigger="change" )
```

My JS code is even simpler:
```javascript
window.jQuery = window.$ = $;
var Parsley  = require( 'parsleyjs' );
$(document).ready(function(){
	console.log( $('#project-form') );
	var ParsleyForm  = $('#project-form').parsley();
	console.log( $('#project-form') );
});
```

After the execution I receive the ParsleyForm object and no error anywhere, but the form itself does not contain any parsley id attribute it should.
If I add the _data-parsley-validate_ attribute to the form, so not using JS, it works.

Any idea?

**Comment by imrefazekas** [comment]
JSFiddle:
http://jsfiddle.net/17b5rxfu/

**Comment by marcandre** [comment]
The problem with the idea is that you could then have a parsley form nested inside another parsley form, that would complicate matters greatly.

**Comment by marcandre** [comment]
Closing for now. If you write code and make progress let us know.
