### ISSUE TITLE
ParsleyUI.addError, not respecting priorityEnabled setting

### ISSUE THREAD

**Issue by timkelty** [guillaumepotier/Parsley.js#819]
I'm validating a couple of my fields from a separate api, `recurly`.

On `parsley:field:validated`, I'm adding/removing the error.
I also have other validation (`required`) on these fields that I want Parsley to handle.

The errors get added, but I end up with multiple errors per field (`priorityEnabled` not being respected).
I want to have the only 1 error at a time, with the Parsley validation with a higher priority than the custom ones I'm adding.

Here's my code:
```
  $forms.each(function(index, el) {
    var $form = $(this);
    var $recurlyFields = $form.find('[data-recurly]').not('[type=hidden]');

    $form.parsley();

    $recurlyFields.each(function() {
      $(this).parsley().subscribe('parsley:field:validate', function(fieldInstance) {

        // Request token from Recurly, or add errors
        recurly.token($form[0], function(err, token) {
          if (err && err.fields && err.fields.length) {
            var isErr = $.inArray(fieldInstance.$element.data('recurly'), err.fields);

            // Remove existing errors
            window.ParsleyUI.removeError(fieldInstance, 'recurlyError');

            // Add errors if present
            if (isErr) {
              window.ParsleyUI.addError(fieldInstance, 'recurlyError', err.message);
            }
          }
        });
      });
    });
  });
```

**Comment by timkelty** [comment]
So I discovered if instead of using the `parsley:field:validate` event, and instead creating a custom validator, `priorityEnabled` works as expected.

This works how I want it to with 1 exception, I now cannot use `err.message` in my error message because of how things are differently encapsulated. Is this to prescribed way to add this kind of validation, or is there a way to fix the first example?
```
  $forms.each(function() {
    var $form = $(this);
    var $recurlyFields = $form.find('[data-recurly]').not('[type=hidden]');

    window.ParsleyValidator
      .addValidator('recurly', function (value, requirement) {
        var isErr = false;
        recurly.token($form[0], function(err, token) {
          if (err && err.fields && err.fields.length) {
            isErr = fm.inArray(requirement, err.fields);
          }
        });
        return !isErr;
      }, 32)
      .addMessage('en', 'recurly', 'This field is invalid.');

    $recurlyFields.each(function() {
      var $field = $(this);
      var fieldInstance = $field.parsley();
      $field.attr('data-parsley-recurly', $(this).data('recurly'));
    });

    $form.parsley();
  });
```

**Comment by marcandre** [comment]
I know this was opened ages ago...

Anyways, there's no current way to return an error message.

Closing this in favor of #840.
