### ISSUE TITLE
Cannot set validation trigger to anything but "change"

### ISSUE THREAD

**Issue by timkelty** [guillaumepotier/Parsley.js#821]
I want my fields to validate on `blur` or `focusout`.

I've tried setting `data-parsley-trigger="focusout"` on my fields, as well as setting `window.ParsleyConfig.trigger = "focusout"`, but all fields seem to still validate as I type (on `change`)

**Comment by jasonblalock** [comment]
+1

**Comment by guillaumepotier** [comment]
That's weird. Every supported jQuery event should work, `focusout` and `blur` should not fail the rule. I'll try to have a look.

**Comment by jasonblalock** [comment]
Thanks. Actually it seems like it might be working. I think part of my confusion is that the validation after an error is shown is still on `change` so it seems like it's ignoring my `focusout` setting.

I see in your docs that "quick error removal" is one of the UX mottos, but that it should be customizable. Though I'm probably being dense, I don't see a way to customize the error removal process. I would like it also to be on `focusout` instead of on change. Is there a way to do that?

**Comment by marcandre** [comment]
Indeed, this is not (yet) customizable.

**Comment by jasonblalock** [comment]
In #34 for the previous version guillaumepotier had suggested modifying the onFieldValidate listener to get this to work. Does that translate to 2.0 somehow?

**Comment by marcandre** [comment]
@jasonblalock Sorry, I meant not data customizable. You can customize the code, but that's not the same kind of undertaking :smile:

**Comment by brunowego** [comment]
+1

**Comment by dsgrant** [comment]
Not a config option, but if you want a global change you can find the manageFailingFieldTrigger function and change this:
```
if (!new RegExp('keyup', 'i').test(fieldInstance.options.trigger || ''))
        return fieldInstance.$element.on('keyup.ParsleyFailedOnce', false, $.proxy(fieldInstance.validate, fieldInstance));
```

To this:

```
if (!new RegExp('keyup', 'i').test(fieldInstance.options.trigger || ''))
        return fieldInstance.$element.on('focusout.ParsleyFailedOnce', false, $.proxy(fieldInstance.validate, fieldInstance));
```

**Comment by marcandre** [comment]
As mentionned in #892, most, if not all of these events should be changed to the 'input' event. Would that solve the need for customizing the trigger?

**Comment by marcandre** [comment]
The latest release defaults to `input`, which should be the perfect event for this, but this can now be customized too.
