### ISSUE TITLE
Custom Validation with events / subscribe and selects

### ISSUE THREAD

**Issue by christophrumpel** [guillaumepotier/Parsley.js#823]
Hey,

I've been working on a similar validation to your example here: http://parsleyjs.org/doc/examples/events.html

But instead of using inputs I need to work with selects. Since I can't use data-parsley-range like in your example I've used data-parsley-required to make sure this field is validated, but this does not work. When I use data-parsley required the "or" function is not working. Is there a problem with selects or am I missing something here?

Find my code here: http://codepen.io/christophrumpel/pen/RNKmGW?editors=101

Thanks and cheers

**Comment by marcandre** [comment]
This fell through the cracks, sorry. Parsley has evolved and the example page has too.
Closing this, please open new issue if needed. Sorry again
