### ISSUE TITLE
Submit Button Value not being submitted due to Parsley

### ISSUE THREAD

**Issue by fabianabela** [guillaumepotier/Parsley.js#826]
I have encountered an issue where the value of a submit button is not being submitted with the form data. This is happening because of parsley. After some more troubleshooting I have discovered that if I make use of the script parsley.js and not parsley.remote.js, the issue is not there anymore.

Note: This issue only happens in Internet Explorer and Firefox, while in Chrome everything works just fine.

Working example

Here is an example in plunkr which demonstrates that with the script - parsley.js, this issue does not happen in neither of the browsers, see: http://plnkr.co/edit/0ylxasiyrlxhSrhrMaFH?p=preview

This means that if we run the above plunkr in any browser and enter anything in the text box and then click on submit, the submit button value is going to change from "undefined" to "submitBtn" as it should.

Not working example

Here is another example in plunkr which demonstrates that with the script - parsley.remote.js, there is this issue in both Firefox and Internet Explorer, while it is fine in Chrome, see: http://plnkr.co/edit/ODqZannjYFBEwppXOXiF?p=preview

This means that if we run the above plunkr in either internet explorer or firefox and enter anything in the text box and then click on submit, the submit button value is never going to change to "submitBtn" as it should, but instead it will always stay "undefined".

Anybody has ever encountered this problem or have a solution? Thanks a lot.

**Comment by marcandre** [comment]
First of, **thank you** for providing a working example of the issue!

This is a problem, and in all browsers this will also cause issues with forms with multiple submit buttons.

It's also not easy to solve, as there is no way to know what causes a submit event. We can check the `click` events of submit buttons and remember the value, but I'm not even sure what's the best way to submit the right information next.

**Comment by fabianabela** [comment]
@marcandre thanks a lot for your response. To be honest, I didn't completely understood your reply. Note, this issue does not occur in Google Chrome (I am re-saying this, since you have said - "in all browsers"). Do you think there is a temporary solution that I can adopt in order to fix this please?

**Comment by lekoala** [comment]
If you are ok for an ugly solution to fix this meanwhile, you can add this when you initialize parsley. The idea is indeed to register the submit handler and then submit it as a hidden element. Not pretty, but works for me.

		// Add action to submitted form for parsley.remote
		// See issue https://github.com/guillaumepotier/Parsley.js/issues/826
		var submitActor = null;
		$('form.parsley [type=submit]').click(function() {
			submitActor = $(this);
		});
		$.listen('parsley:form:success', function(formInstance) {
			if(submitActor) {
				formInstance.$element.append('<input type="hidden" name="'+submitActor.attr('name')+'" value="'+submitActor.attr('value')+'" />');
			}
		});

**Comment by marcandre** [comment]
@lekoala Yes, that's what I was thinking at first, and it will work in most cases. I think that it could create an issue if the form also has other things dealing with `on('submit')`. For example, if some javascript code intercepts them to send the request via ajax (say it's a single-page application), it will work the first time but now we've added a hidden element and if the form is submitted again, but using a different button, we're toast.

**Comment by lekoala** [comment]
yes you're right, in that case it would be better to clear any parsley generated hidden input before adding it again...  I hope it will be fixed in the next version anyway because this is a big issue in my opinion.

**Comment by marcandre** [comment]
I was focusing on removing it after successful submit (not possible I think), but duh, just need to remove when called again, I can't believe I didn't think of that :blush:

**Comment by marcandre** [comment]
Mmm, that might be better, but wouldn't really work fully either, as the first dialog wouldn't fade-in and would come into view at once when the second lightbox is removed.

**Comment by davidrothschild** [comment]
I'm encountering the same issue under certain circumstances, even while using the current version of Parsley (2.2.0-rc1)...

It happens for me when 1) I have a form with a parsley-remote validated field, and 2) the remote validator isn't called until I've already clicked the submit button on the form.

Example -- I have a form where a user can change their username, like so:

    <form id="profile-username" action="/profile" method="post" role="form" data-parsley-validate>
	<input type="text" name="username" value="{{ username }}" maxlength="255" required
		data-parsley-type="alphanum"
		data-parsley-trigger="change"
		data-parsley-remote="/api/checkuser"
		data-parsley-remote-reverse="true"
		data-parsley-remote-message="Username already taken"
		data-parsley-type-message="Username can only contain letters A-Z and numbers 0-9" >
	<input type="password" name="password" required minlength="6" maxlength="150">
	<input type="submit" name="submit" value="Change Username">
</form>

If I change the value in the `username` field, it triggers the remote validator.  Later when I click submit, the form will submit including the value of the `input [type=submit]` as expected.  Good.

However if I *don't* change the value in the `username` field and just submit the form as is, the remote validator isn't called until after I've already clicked submit, and the form posts **without** a value for `submit`.  Not good.

It seems to be a timing issue... I'm thinking whatever Parsley is doing with the submit button behind the scenes doesn't have a chance to finish in between the user clicking 'submit' and the browser going on to the next page.

**Comment by marcandre** [comment]
This is fixed in `master` :fireworks:

Sorry it took so long.

**Comment by jamestowers** [comment]
Thanks! Any chance you could update NPM? This is stil on rc1: https://www.npmjs.com/package/parsleyjs

**Comment by marcandre** [comment]
Sorry about that. @guillaumepotier could you please add me to the npm users?
