### ISSUE TITLE
Adding "autocomplete" attribute to form fields being validated

### ISSUE THREAD

**Issue by madmath** [guillaumepotier/Parsley.js#827]
Hello Guillaume,

It would be great if Parsley.js would add HTML5 "autocomplete" attribute values when processing form elements. Many forms are missing the attribute and it could be nice added value.

This way the produced forms would have autofill support out of the box. Here is the spec for the possible values:

https://html.spec.whatwg.org/multipage/forms.html#autofill

Let me know what you think!

**Comment by marcandre** [comment]
Hi.
I'm sorry, I don't understand how `autocomplete` is related to validation and how parsley should know when to add `autocomplete` nor how.

It's not `parsley`'s duty to "fix" a form, the form must be generated properly. Parsley takes a good form and validates the data according to the given constraints.

Maybe a complete scenario of what should happen and why would help?

**Comment by madmath** [comment]
Hi Marc-André, 

I agree the use case is not the strongest, but validation is more likely to be successful, and lead to more filled forms, if Parsley would add the proper annotation.

I thought since people enter their constraints into Parsley, you may use that to make the form better.

Thanks
