### ISSUE TITLE
type = 'tel' is not working

### ISSUE THREAD

**Issue by Raulvv** [guillaumepotier/Parsley.js#836]
I was watching all the issues refered to the input type phone or tel, and nothing seems to work for me. Also I tried to put a number type and limite the length but a cannot remove the arrows at the right side of the input so its useless. And in the documentation I cannot see anything about phone validation, just manual regexp. I also view this issue but its not working: #334 

Just need a simple phone validation, or number validation... I have 2.0.7. version
 
PD: Really good work with Parsley! ^^

**Comment by coliff** [comment]
type=tel does not and is not supposed to do validation on the phone number. It does bring up the number keyboard on mobile devices though.

Depending on your requirements you could add the pattern attribute, see here for a few examples:
http://html5pattern.com/Phones

**Comment by coliff** [comment]
Also, if you do use type=number you can remove the arrows at the right side (Firefox and Chrome) with this CSS:

input::-webkit-outer-spin-button,input::-webkit-inner-spin-button{-webkit-appearance:none;margin:0}
input[type=number]{-moz-appearance:textfield}

**Comment by marcandre** [comment]
Closing, as `type="tel"` is meant to accept any pattern
