### ISSUE TITLE
Version mismatches between downloads of parsley.js & dist/parsley.js

### ISSUE THREAD

**Issue by dflock** [guillaumepotier/Parsley.js#837]
This is similar to issue #600, but different:

If I download this file: http://parsleyjs.org/dist/parsley.js and this archive: https://github.com/guillaumepotier/Parsley.js/releases/tag/2.0.7, unpack the archive, then compare the two parsley.js files, they're different:

`diff ~/Downloads/Parsley.js-2.0.7/dist/parsley.js ~/Downloads/parsley.js`

```
4c4
< * Version 2.0.6 - built Sat Jan 24 2015 14:44:37
---
> * Version 2.0.7 - built Sat Jan 24 2015 14:50:11
200c200
< * Version 1.0.1 - built Mon Aug 25 2014 16:10:10
---
> * Version 1.0.0 - built Sun Aug 03 2014 17:42:31
211c211
<     this.__version__ = '1.0.1';
---
>     this.__version__ = '1.0.0';
556c556
<           throw new Violation( this, collection, { value: Validator.errorCode.must_be_an_array } );
---
>           throw new Violation( this, array, { value: Validator.errorCode.must_be_an_array } );
1887c1887
< //     Parsley.js 2.0.6
---
> //     Parsley.js 2.0.7
1895c1895
<     this.__version__ = '2.0.6';
---
>     this.__version__ = '2.0.7';
```

**Comment by guillaumepotier** [comment]
You're right. When I built the 2.0.7 I have done it before updating `package.json`, where version is taken for comments. The validator thing too is a glitch on `gh-pages` branch, I should not build there dist versions in my generate doc command, cuz it builds different version if package not up to date.

short version: I screwed up, but (https://github.com/guillaumepotier/Parsley.js/releases/tag/2.0.7)[https://github.com/guillaumepotier/Parsley.js/releases/tag/2.0.7] despite the wrong comment is a valid 2.0.7. You should in any case rely on the one on parsleyjs.org.

I'll fix that for 2.0.8 or 2.1.0.

Best

**Comment by dflock** [comment]
Okay, I'll use the version from parsleyjs.org - but it's not just the comments which are different - there are a few code differences too.

**Comment by guillaumepotier** [comment]
Nope, use 2.0/7 tagged one instead of parsley.org one :)

**Comment by dflock** [comment]
Ok, thanks!
