### ISSUE TITLE
Using parsley in jQuery Generated DOM 

### ISSUE THREAD

**Issue by oroalej** [guillaumepotier/Parsley.js#845]
How can I use parsley in generated DOM?
I generate whole form using jquery and i want to validate the fields using parsley, but it's not working even tough I already called the $(form-id).parsley() or placed data-parsley-validate in the form..

Thank for you help!

**Comment by marcandre** [comment]
Please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)

**Comment by oroalej** [comment]
Okay, thank you

**Comment by oroalej** [comment]
found solution, you should place the `$(form-id).parsley()`  inside the event. for example

~~~~~~~
$().click(function()){
$(id).parsley();
}
~~~~~~~
