### ISSUE TITLE
parsley:form:validate slow to report the proper validationResult

### ISSUE THREAD

**Issue by jonathansimmons** [guillaumepotier/Parsley.js#846]
I've noticed that when I subscribe to `.subscribe('parsley:form:validate')` the returned validationResult is not correct immediately, it always reports true. Which is forcing me to have to put a timeout to wait for it to be properly updated 

Screenshot of some logs: 
![screen shot 2015-02-08 at 12 33 11 pm](https://cloud.githubusercontent.com/assets/945202/6097752/b6cd3c02-af8e-11e4-9b4b-edfc067615ff.png)

I was able to reduce the timeout to 100ms and get the right result. Can anything be done to correct this?

**Comment by guillaumepotier** [comment]
`parsley:form:validate` is actually fired **before** validation and often used to alter some fields before validation. I think you should instead subscribe `parsley:form:validated` instead to have the proper validation result.

**Comment by marcandre** [comment]
Indeed. And you can use `parsley:form:success` or `:error` if you only want to do something on success or failure.

**Comment by jonathansimmons** [comment]
Totally missed the validated event. Thanks guys!
