### ISSUE TITLE
pattern validation does not work on prefilled input fields

### ISSUE THREAD

**Issue by supergundel** [guillaumepotier/Parsley.js#847]
I have a prefilled input field which is required and has a pattern validation.
The required validation works as expected - if you delete the initial value the field gets an error. 

if you alter the value the pattern validation does not work or isn't fired. the field does not get an error and I can send the form.
it only works if you delete the value und retype something.

**Comment by marcandre** [comment]
Please provide us with a fiddle demonstrating your issue.

**Comment by supergundel** [comment]
I think I can close the issue... seems it was a faulty regex pattern :( 
i hate regex....

sorry
