### ISSUE TITLE
Copyright dates need to be updated in src/parsley.js

### ISSUE THREAD

**Issue by vsn4ik** [guillaumepotier/Parsley.js#848]
https://github.com/guillaumepotier/Parsley.js/blob/master/src/parsley.js#L3
`20012-2014` -> `2012-2015`

**Comment by marcandre** [comment]
Thanks, but there's actually no really compelling reason to change a copyright date. See http://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by vsn4ik** [comment]
First date incorect (`20012`).

**Comment by marcandre** [comment]
Oh, that's good to fix :smile:
Done. Thanks :+1:

**Comment by vsn4ik** [comment]
Forgot to add a `src/parsley.js` (line 3).

**Comment by marcandre** [comment]
Indeed, and that's the one that matter. Fixed for good now. Thanks!
