### ISSUE TITLE
Checkbox mincheck validation not working properly on demo page.

### ISSUE THREAD

**Issue by jadlr** [guillaumepotier/Parsley.js#849]
here: http://parsleyjs.org/doc/examples/simple.html

follow these steps:

1. fill in everything (full name, email, gender, heard us by and message)
2. check a single 'Hobbies' checkbox
3. click submit
4. uncheck the checkbox

it says: 'Yay! Everything seems to be ok :)' but it should highlight the 'Hobbies' section.

![image](https://cloud.githubusercontent.com/assets/696999/6247986/155c7352-b77b-11e4-93d7-28fcdbb9be9d.png)

**Comment by guillaumepotier** [comment]
Nope Parsley code is working as expected. The form maybe is not perfect. If you look closer, Hobbies is not required. It is optional. **But** if answered, 2 checkboxes at least should be checked. So if left empty there is no problem. If only one checkbox checked, it would throw an error.

Maybe changing this by something more explicit (like "2 minimum if answered") ?

**Comment by jadlr** [comment]
oh ok, thanks! I guess that changing the text would make sense.

**Comment by jadlr** [comment]
How would I configure parsley to get the behaviour I wanted?

**Comment by guillaumepotier** [comment]
What is your wanted behavior exactly ? :)

**Comment by jadlr** [comment]
Nevermind, I figured it out :) (just add required)
Thanks you very much for your fast responses!

**Comment by guillaumepotier** [comment]
No problem. I would have suggested to add required anyway :) Best, and thanks for using Parsley
