### ISSUE TITLE
Parsley remote validation with angularjs need page refresh

### ISSUE THREAD

**Issue by bdairy** [guillaumepotier/Parsley.js#850]
Hello folks,,

  I have an issue with parsley remote when using in AngularJS,,, ths issue is as follow:
I've created a generic directive to load js files when needed dynamically in forms.. this general directive takes the functionality name as a parameter, and load the corresponding script from an array of scrips tags that is defined in the App configuration.. it works fine with normal direct parsley validation..

now when using it with remote validation.. it also works fine at the first page load.. but if I come back to the page through normal navigation is not fired at all.. it does not call the API at all,, until I refresh the whole page then it comes back to life normally..

I've created a plnk to demonstrate this issue.. I used the github API to validate.. then in all the cases I returned 0 which should normally fire the validator.. you can view my blunk from here http://plnkr.co/edit/Fo4EdjtyWOc1fd1tj3k5?p=preview

as you can see, loading the main view ,, if you click the add user link, it will take you to the add user view.. then you can type anything in the username field it will fire parsley remote validation and cause a validation error... and you also can see that the email validation in the email field is working,,, now click on the view users link in the navigation,, then click the add user link to go back to the add user page.. the remote validation will not work,, but the normal email validation is working... unless I refresh the whole page then everything goes back to normal..

you can view the userController.js there you will see the ParsleyExtend function that adds the asyncvalidator for my input.

I hope someone help me with this because its sucking my time and killing me..

**Comment by marcandre** [comment]
You're killing ParsleyExtend.

Replace
```
      window.ParsleyExtend = {
          asyncValidators: {
          // ...
      };
```

with
```
      window.ParsleyExtend = $.extend(window.ParsleyExtend, {
          asyncValidators: {
          // ...
      });
```

**Comment by bdairy** [comment]
Thanks for the help! U r the best ...
