### ISSUE TITLE
parsley very slow on large form

### ISSUE THREAD

**Issue by loki5100** [guillaumepotier/Parsley.js#855]
Hello,

parsley is very slow on form with around 100 - 200 inputs. it's take around 1000 ms for the dom to complete. I do like this

```javascript
$(document).ready(function(){
  $myForm.parsley();
});
```

i guess it's because  $myForm.parsley(); will modify the dom mostly by adding/removing new elements. this effect of updating the dom is very slow (and bad) ! maybe it's better to add the new elements when they are actually need. exemple empty elements like `<ul id="parsley-id-9096" class="parsley-errors-list"></ul>` are they really necessary before an error is raised ?

**Comment by guillaumepotier** [comment]
I agree with you. We should consider adding these nodes in dom only if errors happen. This is actually important BC Break and should be carefully considered in major upcoming release.

What do you think @marcandre?

**Comment by marcandre** [comment]
Agreed; actually, this is already the case for the current release candidate (since 35aba59e784c8f8d)

@loki5100 If I'm not mistaken, you are using v2.0.x, right? Could you try the [latest release candidate](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc2)?

**Comment by loki5100** [comment]
in the 2.1. it's even worse :( :(

in 2.1.0-rc2 the Time taken by javascripts launched in the "DOMready" event: 1530 ms
in the 2.0.6 the Time taken by javascripts launched in the "DOMready" event: 1006 ms

if i simply do 
setTimeout(function(){$myForm.parsley();},1000);
then in 2.0.6 the Time taken by javascripts launched in the "DOMready" event: 341 ms

to calculate the timing i use in javascript: window.performance.timing.domContentLoadedEventEnd - window.performance.timing.domContentLoadedEventStart

**Comment by wheeyls** [comment]
+1 on this issue. This goes slowly on any large form, even if only one field is actually validated.

**Comment by marcandre** [comment]
I've only started checking this (on Chrome). On a very basic test with 1000 inputs, I'm getting ~1100ms.

The attribute reading is what needs to be optimized. For a form with `n` input fields, we were calling `attributes` (which builds a non negligible object) for each field `4 * n` times (instead of `n`) and each field also re-reads the form's attributes (so of `4 + 4 *n` instead of `1`).

I've started optimizing it a bit, still requires some work though.

**Comment by marcandre** [comment]
Ok, the attribute parsing is now done the right number of times, so it should be better. Checked in Firefox, got from ~3800ms down to ~900ms (for 1000 trivial inputs).
Released 2.1.0-rc3.

**Comment by marcandre** [comment]
@loki5100 @wheeyls Can you try out the latest release and let me know if it's quite fast for you guys now?
Otherwise please send me your forms so I can check what's the remaining bottleneck.

**Comment by wheeyls** [comment]
It's faster for me now, but is not particularly fast yet. My form that has ~1000 inputs (mostly radios) went from 7s to 2s. That seems to be about on scale with your performance improvements.

I've found that this performance is dramatically worse on my iPad/iPhone. Whereas the forms on the previous version would simply break on my iPad, the new version does complete... but takes about 20 seconds.

https://jsfiddle.net/x7oehcpm/

**Comment by marcandre** [comment]
Thanks @wheeyls for your fiddle. I haven't looked at the code for multiple inputs, maybe there's something there. The profiling info confirms that the JS is now spending most of the time in jQuery (`data()`, or looking things up).

**Comment by marcandre** [comment]
Just to be clear though: the best way to speed up a form with a ton of inputs with very few being validated is to tweak `inputs` / `excluded` so the bulk of the non validated items are not selected at all...

**Comment by wheeyls** [comment]
Ah awesome @marcandre I wasn't aware of that.

**Comment by marcandre** [comment]
I've pushed two more [performance tweaks](https://github.com/guillaumepotier/Parsley.js/compare/37cc49bd853df26a16d1f5be93b5e03eb98f5d17...f878efd8392d86c0277b42b8b20269874488f8d7) for multiple fields (radios/checkboxes). On @wheeyls example, it shaves 20% execution time. Not bad, but that still ain't fast.

Looks like the bulk of the remaining time is spent within jQuery, in particular while triggering events. I'll have a look at that. Maybe we'll have to rollback some kind of pubsub instead, or give the option of using either.

The other avenue is to simplify what's going on for trivial fields, i.e. those without constraints, but for a form with a whole bunch of required fields, for example, that wouldn't help.

**Comment by loki5100** [comment]
hello everyone, sorry i was in trouble and can't respond before. i just try today with the last version on parsley (2.1.0-rc7)

the form is not very big, you can see it on http://beta.arkadia.com/enu/

with parsley (2.0.7)
Time taken to parse the HTML (to mark the DOM as ready): 408 ms
Time taken by javascripts launched in the "DOMready" event: 1031 ms

with parsley (2.1.0-rc7)
Time taken to parse the HTML (to mark the DOM as ready): 402 ms
Time taken by javascripts launched in the "DOMready" event: 1063 ms

without parsley :
Time taken to parse the HTML (to mark the DOM as ready): 351 ms
Time taken by javascripts launched in the "DOMready" event: 397 ms

so nothing change between the 2.0.7 and 2.1.0-rc7 :(

**Comment by loki5100** [comment]
by the way doing for exemple parsley({excluded: 'input'}) or parsley() not really change the speed :( i don't understand why parsley take so long time when all the input are excluded :(

**Comment by marcandre** [comment]
It's not clear in the doc, but exclusion is decided after elements have been initialized, so it's possible to have a `data-parsley-excluded` attribute on specific elements to exclude, so it won't change much the loading time.
We have decided to roll back the jQuery events and go back to a homegrown pubsub for 2.1. Stay tuned...

**Comment by loki5100** [comment]
by the way, i m still testing on simple form ( like you can see on http://beta.arkadia.com/enu/ ) and i need to say that it's disaster on mobile :(

The number i gave you 
with parsley (2.1.0-rc7)
Time taken to parse the HTML (to mark the DOM as ready): 402 ms
Time taken by javascripts launched in the "DOMready" event: 1063 ms

it's only on fast desktop use for developpement ! on mobile phone, it's 5x to 10x more slower, and even more slower on firefox also

And as you see the form is not really huge :( many input, but most of them are disabled

also another remark, even if i already do $aSearchBoxForm.parsley();
and after doing on form submit
$aSearchBoxForm.on('submit', function(){
  if ( !$aSearchBoxForm.parsley().validate() ) return false 
}
it's took on mobile around 2 seconds just to do the validate :(

is their any way to completely remove form element (input, checkbox, etc) from the parsley to speed a little? ex: <input type=checkbox data-parsley-excluded="true">.

also does parsley ignore deactivated input element on the submit to not loose time with them ?

**Comment by loki5100** [comment]
I find a small workaround for now. i want to exclude some elements, but using the excluded option not really help. So i found an easy way by looking the code

instead of doing :

$aSearchBoxForm.parsley({excluded: 'input[type=radio], input[type=checkbox], input[type=button], input[type=submit], input[type=reset], input[type=hidden]'});

that not really help for the speed, doing this instead :

$aSearchBoxForm.parsley({inputs: 'input[type=text], textarea, select'});

change a lot !!

i guess it's because of this in the code :


    _bindFields: function () {
      var self = this;
      this.fields = [];
      this.fieldsMappedById = {};
      this.$element.find(this.options.inputs).each(function () {
        var fieldInstance = new window.Parsley(this, {}, self);
        // Only add valid and not excluded `ParsleyField` and `ParsleyFieldMultiple` children
        if (('ParsleyField' === fieldInstance.__class__ || 'ParsleyFieldMultiple' === fieldInstance.__class__) && !fieldInstance.$element.is(fieldInstance.options.excluded))
          if ('undefined' === typeof self.fieldsMappedById[fieldInstance.__class__ + '-' + fieldInstance.__id__]) {
            self.fieldsMappedById[fieldInstance.__class__ + '-' + fieldInstance.__id__] = fieldInstance;
            self.fields.push(fieldInstance);
          }
      });
      return this;
    }

**Comment by marcandre** [comment]
Yes, change `inputs` instead of `excluded` to speed things up.

@guillaumepotier are there any legitimate case where a field would customize the `excluded` option? Currently, `inputs` can only be customized for a form / global, while `excluded` can also be customized per field, but that might be confusing and unnecessary?

**Comment by loki5100** [comment]
Yes i think their are legitimate case because it's could be great to have to possibility to exclude field on the field himself. but exclude must really work ... so params like "data-parsley-excluded"="true"

**Comment by marcandre** [comment]
First, it would have to be `<input id="example" data-parsley-excluded="#example">`, not just `true`.
See, `excluded` is a jquery selector, so it's quite unnatural on a field.
I also would really like to have an example scenario where one would want to do a per field extension this way.

**Comment by loki5100** [comment]
"First, it would have to be <input id="example" data-parsley-excluded="#example">, not just true.
See, excluded is a jquery selector, so it's quite unnatural on a field."

in this way, yes, it's fully unnatural (and ugly) !!

"I also would really like to have an example scenario where one would want to do a per field extension this way."

exemple on http://beta.arkadia.com/enu/  .. on the form i have many input that do not need any validation, so i would like (to win speed) to remove theses fields from the parsley process ...

**Comment by marcandre** [comment]
I wasn't clear, but I meant legitimate cases for other reasons than for speed.

Even for speed, you could have `excluded="[data-parsley-nothing-to-see-here]"` and mark your excluded fields with `"data-parsley-nothing-to-see-here"`.

I think the `inputs` and `excluded` settings are ok, but should probably be specified at the form and the global level only.

Also, not using jQuery events should make things smoother... I've started working on that.

**Comment by loki5100** [comment]
"Even for speed, you could have excluded="[data-parsley-nothing-to-see-here]" and mark your excluded fields with "data-parsley-nothing-to-see-here""

maybe, but i still think it's more natural to say data-parsley-excluded="true" on field level than your method :)

**Comment by marcandre** [comment]
> maybe, but i still think it's more natural to say data-parsley-excluded="true" on field level than your method :)

Both would be possible, even with the conflict between `excluded` being a selector for forms and a boolean for fields.

Also, now that I think about it, I think the only case where doing the test before the instantiation would be if a field is `excluded` according to the form's selector but would override the selector to not be excluded. I don't think that's a feature we want to support.

**Comment by marcandre** [comment]
Update: I hope to have better version this weekend. It removes jQuery events and improves original pubsub (avoiding globals like `$.emit`, won't leak memory if not unsubscribed and slightly faster)

**Comment by raDiesle** [comment]
having some fields and performing group-validation took me 7000s on modern machine & chrome

**Comment by marcandre** [comment]
@raDiesle which version are you using?

**Comment by raDiesle** [comment]
2.0.7 - built Sat Jan 24 2015 14:50:11
I needed to disable parsley.
possible performance problem: ~30 jquery sliders, so many DOM nodes,
but only 30 input fields .

I had to create my own selector for validation...
By the way, why is validate blocking the browser? Callback would be nice.

**Comment by marcandre** [comment]
30 input fields and 7000ms?? That's very odd.

Could you try with our latest release candidate [v2.1.0-rc10](https://github.com/guillaumepotier/Parsley.js/releases/tag/v2.1.0-rc10)? If it's still slow, I'd very much like if you could provide me access or email me the form.

**Comment by raDiesle** [comment]
Whooa it is blazing fast !

This is the form, atm it's the non parsley refactored version -.-
http://kommunikationswege.96.lt/index.html

Let's see to swich back again:D
Thanks

**Comment by raDiesle** [comment]
New version did not match all my expected fields!
in communication.js I configured

window.ParsleyConfig = {
    excluded: 'input[type=button], input[type=submit], input[type=reset]',
    inputs: 'input, textarea, select, input[type=hidden], :hidden',
};

I uploaded r10 parsley enabled version. If you click next, it will fire validate.
On Step-2 I am using hidden fields to store value.
run in console to validate current shown wizard step:

$('#sendForm').parsley().validate($("div.setup-content[style='display: block;']").attr('id'));

-> it should show required validation on hidden slider fields, works with older version, but not r10

**Comment by marcandre** [comment]
Oh, I think I have an idea why your things are so slow... You're trying to validate anything that's hidden! Even `<div>`s and such. Plus ':hidden' is a *really* slow selector. Just type `$(':hidden')` in your console, you'll see.

Your `inputs` should simply be `"input, textarea, select"`.

If you (still) have a problem with the latest release, please open a new issue and provide a working example (it's not clear if the link you gave is updated or not).

**Comment by raDiesle** [comment]
ya, you're right, copy-paste from stackoverflow,- my mistake

but still, r10 will ignore fields, where 2.0.7 work. 
Some bug. I will try to provide a small example and open ticket.
thx!

**Comment by cheneesam** [comment]
Hi,

I have also encountering slow, and unresponsive in chrome browser using `$('form').parsley().validate()`; in 800 - 1000 inputs. I have already upgrade to version 2.62. I am the only one encountering these? If these are not normal I will just move in `grouping` validation instead of `form` validation.

Sorry for my bad explanation. :) 

Thank you,
Chenee
