### ISSUE TITLE
Problem with angucomplete-alt

### ISSUE THREAD

**Issue by viebig** [guillaumepotier/Parsley.js#856]
When used in conjunction with [angucomplete-alt](https://github.com/ghiden/angucomplete-alt) parsley throws this error with an empty type, appending a data-parsley-id atribute automatically...  How do I prevent it from doing that?

```
around line 977..

          default:
            throw new Error('validator type `' + type + '` is not supported');
```

The generated code inside a parsley form that triggers this error:

```
<div angucomplete-alt="" placeholder="Buscar produto" pause="300" selected-object="selectedProduct" local-data="products" search-fields="name" title-field="name" description-field="description" image-field="pic" minlength="1" input-class="form-control form-control-small" match-class="highlight" clear-selected="true" class="ng-isolate-scope">
    <div class="angucomplete-holder" ng-class="{'angucomplete-dropdown-visible': showDropdown}">
        <input id="_value" ng-model="searchStr" ng-disabled="disableInput" type="" placeholder="Buscar produto" ng-focus="onFocusHandler()" class="form-control form-control-small ng-touched" ng-blur="hideResults($event)" autocapitalize="off" autocorrect="off" autocomplete="off" ng-change="inputChangeHandler(searchStr)" data-parsley-id="0287"><span class="help-block" id="parsley-id-0287"></span>
        <div id="_dropdown" class="angucomplete-dropdown ng-hide" ng-show="showDropdown">
            <div class="angucomplete-searching ng-binding ng-hide" ng-show="searching" ng-bind="textSearching">Searching...</div>
            <div class="angucomplete-searching ng-binding" ng-show="!searching &amp;&amp; (!results || results.length == 0)" ng-bind="textNoResults">No results found</div>
            <!-- ngRepeat: result in results -->
        </div>
    </div>
</div>
```

Thank you in advance

**Comment by marcandre** [comment]
AFAIK, `<input type="">` is simply not valid HTML.

> How do I prevent it from doing that?

Fix your HTML... or exclude that input (see `excluded` option`).

**Comment by viebig** [comment]
Thank you for your response, this is not my html, that's a angular plugin dynamic generated HTML which is outputting that. Also it seens that excluded option is not working in this case. My question is why does Parsley throws and error and not just a log warning when the type is not supported? Does that make any sense? Why does parsley not gracefully ignore it? I don't understand why this error needs to be triggered preventing all other scripts to run properly. Thank you for your review!

**Comment by marcandre** [comment]
I'm sorry, I was close-trigger-happy in this case, you are right, it shouldn't error. In particular, unrecognized types should be handled as `type="text"` I think.
In any case, the code wasn't the best, was allowing spaces, etc.
Fix, please try [2.1.0-rc6](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc6) and sorry again for closing this prematurely.

**Comment by marcandre** [comment]
Mmm, make that [2.1.0-rc7](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc7)

**Comment by viebig** [comment]
Thanks mate! Keep up the great work!
