### ISSUE TITLE
Why an empty field cannot be equal to another?

### ISSUE THREAD

**Issue by orlandoaleman** [guillaumepotier/Parsley.js#858]
I'm testing the validators and i've this case. I allow my users have an empty passwords.

**Comment by marcandre** [comment]
It would be much appreciated if you could read the [contributing guidelines](https://github.com/guillaumepotier/Parsley.js/blob/master/CONTRIBUTING.md).
With the little information you are providing, it's not even clear if this is a question of a bug report.
You'll note that in either case, a working example is requested. I trust it will be much more illuminating than your two phrases.
