### ISSUE TITLE
Possible error?

### ISSUE THREAD

**Issue by studiosi** [guillaumepotier/Parsley.js#860]
Hello, I have this:

    <input name="T" id="T" required type="text" data-parsley-pattern="([0-9]{9,10})" title="T" data-parsley-error-message="ERR" parsley-trigger="keyup">

The regexp should be working, the thing is like it only tests it once. I submit the form with 10 numbers in this field and errors in others. Then, I resubmit it with 11 numbers and it does not show up as an error.

Any clue?

**Comment by marcandre** [comment]
## Questions?

Please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)

**Comment by marcandre** [comment]
And ideally next time please read the contributing guidelines before opening an issue on any project...

**Comment by studiosi** [comment]
I'm not asking a question, this is obviously an error, anyways, you are not being helpful at all, so I am not going to be either. I provided an example of a form field that is not working with the current version of the library, I had to circumvent it with a silly workaround.

**Comment by marcandre** [comment]
Oh, I see your pattern is not anchored. `^[0-9]{9,10}$` should work. See also #764
