### ISSUE TITLE
Passing a parameter to a validation callback

### ISSUE THREAD

**Issue by jslegers** [guillaumepotier/Parsley.js#862]
### My use case :

I have a custom built multi-step JS form where submission takes place only after the last step of the form has been filled in, and each step needs to be validated before one can move on to the next.

--------------

### My code :

I created a validation callback like this :

````js
var $form2 = jQuery('#form').parsley().subscribe('parsley:form:validate', function(formInstance) {
    // if one of these blocks is not failing do not prevent submission
    if (!formInstance.isValid()) {
        if (typeof (formInstance.submitEvent) !== typeof (undefined)) {
            // else stop form submission
            formInstance.submitEvent.preventDefault();
        }
    }
    return;
});
````

I'm manually triggering the validation event by clicking a link :

````js
jQuery('.control').click(function(e) {
    if (!$form2.validate()) {
       e.preventDefault();
    }
});
````

--------------------------

### My problem :

I would like to be able to attach this validation function to multiple controls and pass a different parameter to the validate function, based on which control is being triggered.

So my click handler would be changed to something like this :

````js
jQuery('.control').click(function(e) {
    if (!$form2.validate($(e.target).data('validationgroup'))) {
       e.preventDefault();
    }
});
````

In the validation callback, I would then replace `formInstance.isValid()` with `formInstance.isValid(validationgroup)`, so each time the validation is triggered, it runs only for one specific validation group corresponding with the control that was pressed (which I can set dynamically by passing a parameter to the validation callback).

What I don't understand is whether it's possible to pass the `validationgroup` to the validate function and how I should do that in case it is possible.

**Comment by marcandre** [comment]
That's a question too, but the answer is that there might a missing feature, i.e. the form validation events should probably include the group being validated.

**Comment by jslegers** [comment]
@marcandre :

I'm currently using a workaround :

````js
jQuery('.control').click(function(e) {
    $form2.validationGroup = $(e.target).data("validationgroup");
    if (! $form2.validate()) {
        e.preventDefault();
    }
});

var $form2 = jQuery('#form').parsley().subscribe('parsley:form:validate', function(formInstance) {
    if (!formInstance.isValid(formInstance.validationGroup)) {
        if (typeof (formInstance.submitEvent) !== typeof (undefined)) {
            // else stop form submission
            formInstance.submitEvent.preventDefault();
        }
    }
    return;
});
````

This allows me to pass my validation group to the validation callback.

This still doesn't work as expected, though.

When running the validation for validation group `validationGroup`, I'm getting error messages for all validation groups, while I would expect to see only messages related to validation group `validationGroup`.

**Comment by marcandre** [comment]
You're calling `$form2.validate()`, when you should be calling `$form2.validate($form2.validationGroup)`, no?

**Comment by jslegers** [comment]
@marcandre :

While `$form2.validate($form2.validationGroup)` does fix the latter problem, being forced to access the custom property `validationGroup` to my instance just to get access to the name of the validation group feels like a dirty hack.

The validation group should be present in `formInstance` when `validate` is called with a parameter.
Also, for other use cases it makes sense to by able to pass custom parameters, to further refine the behavior of the validation callback.

The code I'm currently using :

````js
jQuery('.control').click(function(e) {
    $form2.validationGroup = $(e.target).data("validationgroup");
    if (! $form2.validate($form2.validationGroup)) {
        e.preventDefault();
    }
});

var $form2 = jQuery('#form').parsley().subscribe('parsley:form:validate', function(formInstance) {
    if (!formInstance.isValid(formInstance.validationGroup)) {
        if (typeof (formInstance.submitEvent) !== typeof (undefined)) {
            // else stop form submission
            formInstance.submitEvent.preventDefault();
        }
    }
    return;
});
````

**Comment by marcandre** [comment]
Latest version passes the parsleyInstance as last parameter. I believe this solves this issue :smile:
