### ISSUE TITLE
No event data available when manually triggering validation event

### ISSUE THREAD

**Issue by jslegers** [guillaumepotier/Parsley.js#863]
### My use case :

I have a custom built multi-step JS form where submission takes place only after the last step of the form has been filled in, and each step needs to be validated before one can move on to the next.

--------------

### My code :

I created a validation callback like this :

````js
var $form2 = jQuery('#form').parsley().subscribe('parsley:form:validate', function(formInstance) {
    // if one of these blocks is not failing do not prevent submission
    if (!formInstance.isValid()) {
        if (typeof (formInstance.submitEvent) !== typeof (undefined)) {
            // else stop form submission
            formInstance.submitEvent.preventDefault();
        }
    }
    return;
});
````

I'm manually triggering the validation event by clicking a link :

````js
jQuery('.control').click(function(e) {
    if (!$form2.validate()) {
       e.preventDefault();
    }
});
````

--------------------------

### My problem :

In my callback, `formInstance.submitEvent` is `undefined`.

In my callback, I do not have access the click event of my control.

I also do not seem to be able to pass theclick event of my control nor any other data to the validation callback (see also https://github.com/guillaumepotier/Parsley.js/issues/862).

Is there another way to pass whichever control was being pressed to my validation callback?

**Comment by marcandre** [comment]
From our `CONTRIBUTING` guide:

## Questions?

Please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)

**Comment by jslegers** [comment]
@marcandre: 

I'm not entirely sure, but I think this is a missing feature.
