### ISSUE TITLE
Isn't it better that addAsyncValidator could accept function as fourth parameters (options)

### ISSUE THREAD

**Issue by vannleonheart** [guillaumepotier/Parsley.js#865]
When add new async validator, isn't it better if it could accept function that return object as fourth parameter (options parameter). I think it will give us more capability when adding options especially if we need to match it with specific condition.

`app.find( ".parsleyForm" ).parsley()
.addAsyncValidator( "customValidator", function ( xhr ) {
  return 404 === xhr.status;
}, "http://mysite.com/api/users", function ( $instance ) {
  return {
    data: {
      filters: {
        email: $instance.$element.val()
      }
    }
  };
});`

**Comment by Flaburgan** [comment]
I support this one.

**Comment by marcandre** [comment]
It's now easy to customize options before an ajax call, so I'll close this one.
