### ISSUE TITLE
Submit your package to Packagist

### ISSUE THREAD

**Issue by Rambomst** [guillaumepotier/Parsley.js#866]
As the title says, you should submit this JS library to Packagist.

**Comment by marcandre** [comment]
Can't packagist use npm/bower dependencies?

**Comment by Rambomst** [comment]
Not a clue, all I know if when I searched for it this came up https://packagist.org/packages/parsleyjs/parsleyjs which isn't the correct library.... and its broken.

**Comment by marcandre** [comment]
Sorry, we won't support non JS package solutions.
