### ISSUE TITLE
min-check validation not working

### ISSUE THREAD

**Issue by maketimetodesign** [guillaumepotier/Parsley.js#870]
We appear to be having a problem with multiple checkboxes. We have the min-check data attribute and max-check (also tried various other configurations and also a custom validator), but the validation doesn't kick in until at least one is checked, despite the fact we have set a minimum check.

Has anyone else had this problem or can anyone explain why this is happening? 

We're using 2.0.7

Thanks!

**Comment by marcandre** [comment]
Not too sure, but I think that's as per spec. You need to state it's `required` too.

**Comment by maketimetodesign** [comment]
Thanks for the tip, one of those questions when you ask when you've had a long week!

**Comment by marcandre** [comment]
It's not so trivial, and I'll try to make the doc clearer when I get a chance.

**Comment by maketimetodesign** [comment]
Awesome. Yeah, what I got from the docs is that the min check would imply that the field is required, but makes sense! Thanks!
