### ISSUE TITLE
How about an example of parsley form validation working with JavaScript?

### ISSUE THREAD

**Issue by DaveC426913** [guillaumepotier/Parsley.js#871]
In your examples section I see a super-simple example of a form with no JavaScript. I find no examples of validation that will tie into my JavaScript.

My Save button will be disabled until the form is valid, so I need all those tie-ins to know what's valid and what isn't.

Am I looking in the wrong place??

**Comment by marcandre** [comment]
All three *other* examples have javascript code.

I agree the JS API could be more documented, but check the even section (ideally from one of the more recent release candidates, as this will change in 2.1).

Contributions welcome!
