### ISSUE TITLE
parsley.remote clears action from posted values on firefox/safari

### ISSUE THREAD

**Issue by lekoala** [guillaumepotier/Parsley.js#873]
Hello,

This is an issue I discovered recently. It seems that the way parsley.remote prevents the form submit while waiting for async validators to complete clears the submitted action from the posted values.

So if you have:

<input type="submit" name="myaction" value="click" />

"myaction=click" will never be sent. This only happens on Firefox and Safari (IE not tested). Everything works fine if I use parsley without remote.

I suspect the error lies around this bit of code

 // If user do not have prevented the event, re-submit form
        if (!that.submitEvent.isDefaultPrevented())
          that.$element.trigger($.extend($.Event('submit'), { parsley: true }));

Because the event's target is the submitted form, not a specific button.

**Comment by marcandre** [comment]
Indeed :-( Please check the identical #826.
I'll close this one so any feedback is centralized.
Thanks for reporting this.
