### ISSUE TITLE
Can not prevent form submission.

### ISSUE THREAD

**Issue by yspanchal** [guillaumepotier/Parsley.js#875]
i am not able to prevent form submission for an event "parsley:form:validate" 

$('#form').psly().subscribe('parsley:form:validate', function(formInstance) {
  formInstance.submitEvent.preventDefault();
});

showing error 'cannot read property preventDefault of undefined'

i am using Multi steps form.

**Comment by marcandre** [comment]
Not sure why, I'd have to check why.
In the meantime, you can listen for the `success` or `validated` events and set `this.validationResult` to false if you want.

**Comment by yspanchal** [comment]
@marcandre Thanks man it is working...

$('#form').parsley().subscribe('parsley:form:validated', function(formInstance) {
formInstance.validationResult = false;
});

**Comment by marcandre** [comment]
Let me keep this open, I'd like to check why `submitEvent` isn't defined.

**Comment by katywings** [comment]
Hello there :)

I am using 2.2.0-rc1 and have the same problem like @marcandre. His solution with `subscribe` produces a warning: i should use on/off. 

But when I use the on/off handlers in a manner like:
`...'form' ).parsley().on( 'form:validated', my_function );`

(Which is the documented way to use the events) 

, changing `validationResult` to false and calling `submitEvent.preventDefault();` in the `my_function` it will submit the form, nevertheless...

I tried about 15 different ways to make this working but didn't have any success...

Can someone please give me a hint? :heart: 

Thanks in advance ^^

**Comment by marcandre** [comment]
Thanks for chiming in, makes me realise that changing `validationResult` doesn't work anymore... Better change that.

In the meantime, here's the recommended way to stop submission:

```
$('#your-form').parsley().on('form:submit', function(formInstance) {
  return false;
});
```

**Comment by katywings** [comment]
Thanks a lot for your extremely fast answer, but that doesnt work either xD...

hmmm..... :thought_balloon:

**Comment by marcandre** [comment]
It should, [see here](http://jsfiddle.net/marcandre/9xbkbxpo/)

Did you replace the `#your-form` selector correctly?

**Comment by katywings** [comment]
I will check it tomorrow a second time when im inhouse again ^^

Have a nice evening

Von meinem Sony Xperia™-Smartphone gesendet

---- Marc-André Lafortune schrieb ----

**Comment by katywings** [comment]
Okay awesome news, its absolutely working with 

    $('#your-form').parsley().on('form:submit', function(formInstance) {
      return false;
    });

It wasn't the selector ^^, Yesterday Evening, I choosed to work on an other feature after writing my question, and therefore that other feature disabled proper code execution.

Thanks a lot for your help! :dancer:

**Comment by marcandre** [comment]
Changing `validationResult` works again in `master`.

**Comment by katywings** [comment]
Cool to hear! :)

**Comment by EficienciaDigital** [comment]
> Obrigado por participar, me faz perceber que mudar `validationResult`não funciona mais... É melhor mudar isso.
> 
> Enquanto isso, aqui está a maneira recomendada de interromper o envio:
> 
> ```
> $('#your-form').parsley().on('form:submit', function(formInstance) {
>   return false;
> });
> ```

obrigado.
