### ISSUE TITLE
iOS: would like page to scroll to first error on validation fail (works on desktop)

### ISSUE THREAD

**Issue by mkstix6** [guillaumepotier/Parsley.js#878]

**Comment by nodefortytwo** [comment]
I have observed that safari tries to scroll but fails leaving the whole page unresponsive. Currently looking to disable the scroll behaviour.

**Comment by guillaumepotier** [comment]
Have you [tried the `data-parsley-no-focus` option](http://parsleyjs.org/doc/index.html#psly-ui-for-field)?

I'll try to have a look to avoid that, but disabling focus on mobile could in the meantime help.

Best

**Comment by nodefortytwo** [comment]
In the end i disabled client side validation on i devices and did scrolling based on server validation. not ideal but it does the job for the moment.

feels like its a idevice bug rather than a parsely issue

**Comment by marcandre** [comment]
Closing in favor of #938
