### ISSUE TITLE
Syntax error, unrecognized expression on checkboxes

### ISSUE THREAD

**Issue by lewiswalsh** [guillaumepotier/Parsley.js#881]
I have a form with lots of checkboxes for users to indicate different types of damage. eg:
```html
<span>
	<input type="checkbox" class="damage" name="damage[unknown bios password]" id="damage[unknown bios password]">
  <label for='damage[unknown bios password]'>Unknown BIOS password</label>
</span>
```

However, parsley adds the following attribute to the input:
```
data-parsley-multiple="damageunknown bios password"
```

Which results in the following error:
```
Uncaught Error: Syntax error, unrecognized expression: [data-parsley-multiple=damageunknown bios password]
```

If I remove the 'name' attribute it's fine, but I get a console full of warnings from Parsley, not to mention removing 'name' destroys the form submission.

I have no need for these fields to be validated but can't seem to get Parsley to ignore them without generating this error.

**Comment by marcandre** [comment]
Sorry about this.
I should be able to fix that today.
You can exclude some fields with the `excluded` option, if you want.

**Comment by lewiswalsh** [comment]
I appreciate the prompt response. I tried the following, but still get the error:
```javascript
$('#form_laptop').parsley({
    excluded: 'input[type=checkbox]'
});
```

**Comment by marcandre** [comment]
Oh, you're right. We create an instance before checking for exclusion (and creating the instance bombs). You could restrict the `inputs` option instead, like `input[type=text], input[type=...], textarea, select`, but that's getting ridiculous. Let me fix this for you.

**Comment by marcandre** [comment]
Ok, please try [`2.1.0-rc5`](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc5), should be fixed now.

Thanks for reporting this!

**Comment by lewiswalsh** [comment]
Bingo! Thank you ever so much.
