### ISSUE TITLE
There is no NuGet package for VisualStudio for this library

### ISSUE THREAD

**Issue by SerhioVilares** [guillaumepotier/Parsley.js#882]
There is no NuGet package for VisualStudio for this library
![image](https://cloud.githubusercontent.com/assets/6714786/6965777/410e0fa6-d954-11e4-8edb-51fd8a568bc0.png)

**Comment by marcandre** [comment]
I think that publishing packages outside of the JS platform (which already has `npm` & `bower`) is left to whoever wants it and needs it.
Moreover, you probably should consider using the `NuGet` package called `bower` to handle your JS dependencies.
@guillaumepotier can reopen this if he disagrees.
