### ISSUE TITLE
Email Address Formatting

### ISSUE THREAD

**Issue by Miserlou** [guillaumepotier/Parsley.js#884]
I noticed that there are some valid email addresses that Parsley considers invalid. Particularly, those that have the name with the email address with angle brackets, ex:

     John Smith <john.smith@example.org>, Frank Andbeans <frank@andbeans.org>, Ru Paul <rupaul@logo.tv>

As I am using Parsley in a web-mail client, this is particularly annoying. It'd be nice if a) there was a way to have these be considered valid email addresses, and b) if there was a way to take multiple comma separated email addresses in this format.

Love the project! Comes in handy all the time.
Thanks!,
R

**Comment by marcandre** [comment]
HTML5 email validation does not accept `name <email@example.com>`, so I don't think we should either. Maybe build your own custom validator for that?

Parsley does not support the `multiple` attribute though, I've opened #885 for that.
