### ISSUE TITLE
The example of custom validators is partially wrong: 

### ISSUE THREAD

**Issue by serhioV** [guillaumepotier/Parsley.js#886]
The example of custom validators is partially wrong: 

See the issue here:  http://stackoverflow.com/q/29608694/185593
To fix, replace

    <input type="radio" name="question1" value="true" required /> Yes
    <input type="radio" name="question1" value="false" /> No

with 

    <input type="radio" name="question1" value="yes" required /> Yes
    <input type="radio" name="question1" value="no" /> No

**Comment by marcandre** [comment]
Indeed, thanks!

**Comment by marcandre** [comment]
Oups, wrote the wrong issue number in 0184ec75a03cdb0f142a8868597c9fbf6f900e0a
