### ISSUE TITLE
checkbox with the same name validate in different form

### ISSUE THREAD

**Issue by ChJJin** [guillaumepotier/Parsley.js#888]
Hi, 

I have two form on the same page. There are more than one checkbox with the same name in both of the forms. 

I have to validates the range of checked checkboxes in each form, with ```data-parsley-check```. But in fact, when I check different checkbox with same name in different form, it validates the numbers by adding the checked checkbox in the both form together !! And the error messages are only listed in the first form !!

It shows that the checkbox with the same name is validated on the whole page.

**Comment by marcandre** [comment]
Agreed, that's a bug. Shouldn't be too hard to fix. You want to try? :smile_cat:

**Comment by ChJJin** [comment]
I'd like to try, it's my pleasure, thx.  :smile_cat:

**Comment by marcandre** [comment]
Great, feel free to ask any question. Be careful that it is possible that some inputs might not be inside a `<form>`, in which case we need to consider the `<body>` as the "container"

**Comment by ChJJin** [comment]
Got it .
These situations does not come to my mind just now, thx. :+1:

**Comment by marcandre** [comment]
Good start btw.
Also, you will need to add some tests that fail before and work after your changes.

**Comment by marcandre** [comment]
I have a solution, currently in a branch.

**Comment by marcandre** [comment]
Merge and fixed a while ago. Thanks for reporting this.
