### ISSUE TITLE
Choosing a suggested value from Chrome doesn't trigger validation on that field

### ISSUE THREAD

**Issue by devonmather** [guillaumepotier/Parsley.js#892]
In Chrome on OSX the following error occurs after doing the user actions below.

- Scroll to bottom of form click Submit
- Form validates providing error feedback on incomplete fields
- Double click in field to obtain focus, this brings down values that have been used previously for this form
- Click the suggested value 
- The error on this field which has now been populated with valid data doesn't re-validate and doesn't remove the error

Is this a bug or is there a simple fix?

**Comment by marcandre** [comment]
It's a bug. We're listening for `keyup`, but really we should be listening to the (lesser known) `input` event. I think it would be better for `<select>` to listen to `input` also. @guillaumepotier any reason not to change this that I don't know about?

**Comment by guillaumepotier** [comment]
@marcandre did not know this event. That [seems more handsome and more reliable than a keypress](http://stackoverflow.com/a/17384264/404581)! Totally agree to use that instead of `keyup` is tests pass :)

**Comment by marcandre** [comment]
Should be fixed in the latest release, let me know if that's not the case :smile:
