### ISSUE TITLE
browserify_bundle

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#895]
Not sure what this is all about, but browserify_bundle.js is way out of date.

Can we get rid of it? I often do global greps and it's in the way.

Or else it should be automatically update.

**Comment by guillaumepotier** [comment]
Hum,

In the past I was not as skilled as I am now for tests and dependencies. Browserify appears to have weird API and behaviour, and this test was here to ensure all was right.

What we could do is to ignore this file, and update .travis.yml to fetch it through bower for example and run an additional test suite only for that. That way it won't go in your way in your project, only on CI.

What do you think?

**Comment by marcandre** [comment]
Sure, anything really, I just wanted to mention it's not testing much *today* the way it is setup... Not a biggie of course.
