### ISSUE TITLE
Allow removal/overriding complete data array in custom remote Validator

### ISSUE THREAD

**Issue by fgerards** [guillaumepotier/Parsley.js#898]
Hi,

imho it should be possible to override the COMPLETE data array in an ajax call via a data-parsley-remote-validator (customValidator) and not only extend it. By default, the pair "parsleyField[name]=ParsleyField[value]" is added as the last param in the data array. 
This might lead to some confusion if you validate e.g. a registration form to a different API which might misinterpretate the default data-array branches and lead to a faulty response.

This seems to be done in the parsley.remote.js around:

 if ('undefined' !== typeof this._remote && 'undefined' !== typeof this._remote[csr])
      promise = this._remote[csr] ? deferred.resolveWith(that) : deferred.rejectWith(that);
    else {
      data[that.$element.attr('name') || that.$element.attr('id')] = value;
 }

Thx 4 feedback

**Comment by marcandre** [comment]
Can you check that #894 would satisfy your request?

**Comment by fgerards** [comment]
Hi,
thx - the new emit completely solves this issue. Hope it will be merged soon, I created a custom parsley.remote.js.
Thx 4 the hint !

**Comment by marcandre** [comment]
The `ajaxoptions` event is now merged in `master`. There's also a simpler way to use the input value in the URL
