### ISSUE TITLE
Masks & patterns auto-fill?

### ISSUE THREAD

**Issue by LoaiBassam** [guillaumepotier/Parsley.js#904]
Is there a way to make inputs with a pre-set regex or pattern to auto-fill as the user is filling in? 

For example. If the regex is set to 00/00/00 - the input will have a placeholder of 00/00/00 and when the user start typing in the numbers, it will simply get filled in like 10/00/00 --> 12/00/00 --> 12/30/00 and so on... so the pattern definers are pre-filled... 

This example should clear things up: http://robinherbots.github.io/jquery.inputmask/

I hope that made any scene.

Thanks

**Comment by marcandre** [comment]
No, there's no way to do this. Moreover that would be next to impossible, would require parsing regex, etc... More importantly, I'm afraid this is out of scope of parsley.
