### ISSUE TITLE
Multiple asynchronous validation checks

### ISSUE THREAD

**Issue by Flaburgan** [guillaumepotier/Parsley.js#905]
Hi everyone.

I'd like to validate that an email is correct when the user registers. For that, I need to:
1. Check that the email is valid (regex but also lookup on the domain to see if there is an MX, so this has to be done server side)
2. Check that the email is available, that means it is not already in my database

So I had a look at [parsley remote](http://parsleyjs.org/doc/index.html#remote) and didn't like the Parsley way to check the xhr status with 200 or 404. My API is here, it should never respond with 404. So I checked  how to write a custom validator. I have two things to check, but `data-parsley-remote-validator='my-custom'` allows me to define only one API call (and also one error message).

It looks like the easiest way to deal with this problem would be to implement https://github.com/guillaumepotier/Parsley.js/issues/560 == to allow to get an error message from the server instead of a simple boolean. That way, I could answer "Email invalid", "Email unavailable", or "" which would mean no error. But honestly, that feels kind of a hack. So my question is, why can't we go with `data-parsley-my-custom=''` (or `data-parsley-remote-my-custom=''`) instead of `data-parsley-remote-validator='my-custom'`? This syntax would be similar that for other personalized (synchronous) validators. Is there any reason this has not be done that way?

**Comment by marcandre** [comment]
I'd write two separate validators. For one thing, the options for the domain name should only contain the domain name so it gets cached clientside.

Not a direct answer, but there are other acceptable status codes beside 404, in particular [403 "Forbidden"](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4) which I feel would be quite meaningful in the context of a parsley remote validation.

**Comment by marcandre** [comment]
Please check the latest release.

In addition to the classic `remote` validator, it's now easy to write your own validator returning a promise
