### ISSUE TITLE
Parsley & Chosen dropdwon

### ISSUE THREAD

**Issue by loaibassam** [guillaumepotier/Parsley.js#906]
I am using Chosen dropdowns (http://harvesthq.github.io/chosen) with Parsley.js and have set up a live test here: http://loai.directory/test/test/blank.php

Parsley position the .parsley-errors-list inside the multi select dropown menus and between checkboxes and radios.  

Is there a way to change the location of which the .parsley-errors-list is created? 

Below is the structure of my form elements. 

`<fieldset>
   <p>Custom validation message</p>
    <div>
        <input name="" required="" data-parsley-required-message="Custom Error Message" data-parsley-id="3125" class="parsley-success">
FROM HERE ul class="parsley-errors-list" id="parsley-id-3125"></ul>
    < /div>
TO HERE ul class="parsley-errors-list" id="parsley-id-3125"></ul>
</fieldset>`

How can I move it from under the input to just before the closing </fieldset> and apply the classes .parsley-error and .parsley-success to the containing <fieldset> instead of the validated inputs? 

Thank you

**Comment by marcandre** [comment]
This question fell through the cracks, sorry about that. Use `errorsContainer` option. Any other questions: ask on StackOverflow
