### ISSUE TITLE
51 fields = too much recursion?

### ISSUE THREAD

**Issue by KrunchMuffin** [guillaumepotier/Parsley.js#907]
I am getting the firefox "too much recursion" error when parsley instantiates form with 51 fields. 
I can't post a fiddle. I can give you a link and login, but not publicly. I will try eliminating fields one at a time to see when it stops. If that is actually what the issue is.

Derek

**Comment by KrunchMuffin** [comment]
I don't get it. I dropped it down to one field and still get the error.
I know it's breaking at a jq line, but when I remove the parsley() for the form, everything is fine.

using version 2.0.7

too much recursion
jquery-2.1.3.min.js
Line 177 jQuery.extend = jQuery.fn.extend = function() {

**Comment by marcandre** [comment]
Sure, email me a link.

You can also try [2.1.0rc8](https://github.com/guillaumepotier/Parsley.js/releases/tag/2.1.0-rc8), although we're still finalizing the API for the event handling.

**Comment by KrunchMuffin** [comment]
tried rc8, still says rc7 in file btw, still same issue. I emailed you. Thanks for looking into it.
