### ISSUE TITLE
Bug in example on website: "yay!" when mincheck=2 and nothing selected, same for message

### ISSUE THREAD

**Issue by SonOfLilit** [guillaumepotier/Parsley.js#910]
![image](https://cloud.githubusercontent.com/assets/14973/7572543/9f1c00c0-f827-11e4-8678-d1e076bea94d.png)

It seems to work when there is at least one selected hobby (or one character in the message), but not when there are zero.

**Comment by marcandre** [comment]
Right, the label should probably say (optional, but 2 minimum required if specified) or else `required` should be added.

**Comment by marcandre** [comment]
Example's label tweaked a while back. Thanks!
