### ISSUE TITLE
Non-Validation of checkbox  Parsley v2.1.0

### ISSUE THREAD

**Issue by mohdasif2294** [guillaumepotier/Parsley.js#915]
Hey!
Thanks a lot for providing this simple js !!!!  Its been very useful.<br>
But lately I am having issue with upgradation  parsley js the from 1.x to 2.1.0 .<br> But I am having problem with checkbox validation (data-parsley-mincheck="N" ) on submitting the form , checkbox validation doesnot happen. 
<b>They  are not triggered until you make any changes to input {checkbox} otherwise no validation happen for these input.</b>

For example :
http://parsleyjs.org/doc/examples/simple.html  <br>In this example also checkbox validation does not happen on clicking <i><b>validate</b></i> button.  But If you select any checkbox then validation happens correctly. 
Please let me know is this problem is with my browser or anyone else is having the same problem. And how to overcome this issue.

<i>PS: I checked Stackoverflow but nothing could work with my code.</i>

**Comment by guillaumepotier** [comment]
Hi there,

`mincheck`, `maxcheck` or `check` don't work as `required` validator. You could have some optional mincheck options, like it is the case in the sample form (checkboxes are **not** mandatory)

You'll have to add `required` constraint too to have the desired required behavior.

Thx

**Comment by eformx** [comment]
in 2.6 parsley mincheck and required has no affect, as per the demo on the parsley home page. Is there a fix?
