### ISSUE TITLE
Bug: Error messages from parsley.remote removed when client-side validation succeeds.

### ISSUE THREAD

**Issue by pcuriel** [guillaumepotier/Parsley.js#916]
Hi everyone.

I have experienced issues with fields that have both client-side validation and server-side validation with parsley.remote.js. 

With this example the error can be reproduced: http://jsfiddle.net/pcuriel/816438wa/

1) Trigger validation without modifying the "Email" field. This way, client-side validation should succeed but the remote one should not.
2) Trigger validation once more and without modifying anything again. This second validation should be triggered having the focus on the "Email" field and pressing the "Enter" button to reproduce the error, because when validation is triggered pressing the "Submit" button everything works as expected.
Now the remote validation fails again, but both the error message and the error style appears briefly and then disappears.
3) Steps 1 and 2 can be repeated with a different email (all emails beginning with "a@" are considered invalid) with a similar result: in the first attempt the error message/status will correctly appear and the second will not.

I haven't had time to look more carefully into the source code for the cause of the error. But taking into account that the error is shown the first time a given value is tested, I have tried clearing the remote validation cache (check this example http://jsfiddle.net/pcuriel/o31mttdc/, where source code of parsley.remote.js is modified to do so -lines 230 to 232-) and the problem is solved.

When remote validation uses cached results, are this results "computed" before the client-side validation? If so, could it be that client-side validation clears this errors when it succeeds?

**Comment by pcuriel** [comment]
Answering to my own question, the problem is not cached remote validation results being hidden by client-side ones. I have found out that when a second validation is triggered with the "Enter" button, actually two validations are run, but the second does not seem to fire the remote validation.

This can be observed in the following screenshot of the JS Console (where it says "Line X" it means that the log trace has been generated from Line "X" of parsley.remote.js).

![parsleybug](https://cloud.githubusercontent.com/assets/1854183/7813805/3496f96a-03be-11e5-8132-42b1116d4410.png)

- The traces in (1) have been generated after triggering the first validation in the form.
- The traces in (2) have been generated after triggering a second validation in the form using the "Enter" button. It can be observed that a second validation is run but without async validation being called, and thus validation result is success and the error message added in the first validation is removed.
- The traces in (3) have been generated after triggering a third validation but clicking in the "Submit" button. In this case no second validation is run and thus the error message is not removed.

Testing different configurations, I have found out that setting the "trigger" property of the field to "keyup" (i.e., data-parsley-trigger="keyup") seems to solve the issue. The reason is that with this trigger config, the second validation in case (2) also triggers the async validation.

And this has led me to notice which can be the true reason of the problem. No matter which value is set for the "trigger" property, after a validation is triggered, the client-side validations are run each time the value of the field changes. This happens even if both the form and the field have trigger=submit.
However, the remote validation does not seem to work that way. The latter seems to more or less respect the value set for "trigger". And I say more or less because if trigger=keyup or trigger=focusout it seems to run the validation when it should. However, if I'm not wrong setting trigger=change should run the validation when the value of the field changes, which does not happen.

**Comment by JanezStupar** [comment]
I have run into the same issue. It seems to me that this is a race condition in validators.

The root cause of this issue can be found in method 'manageFailingFieldTrigger()' of parsley.remote.js

What 'manageFailingFieldTrigger' does is that upon first error it binds local validation to keyup in an attempt to improve UX by validating after every keystroke once a validation of an uninterrupted value has failed.

The core problem is that when for instance local email validator passes (because email syntax is right) but remote validator fails (because email already exists) - local validator results overrides the remote validator and thus causes the error to be removed.

This seems as an architectural issue. What needs to be done is to:
  1. ensure that local validator is applied before remote validator.
  2. validation result needs to be inferred by using boolean multiplication. Because a value cannot be valid and invalid at the same time.

How to acheve that I haven't been able to figure out yet.

**Comment by JanezStupar** [comment]
I have submitted a PR that sidesteps this issue. The fix itself is a kludge (surpress keyup events triggered by Enter) and the issue itself is an architectural in itself.

https://github.com/guillaumepotier/Parsley.js/pull/921

**Comment by tyan4g** [comment]
So Is there any solution for this?
I run into the same problem too.
I need to validate the email input both on client side to ensure it's a valid email
also I need to validate the email is not used by other users yet.

so I guess what i need is a validation chain .when it's a valid email then to check it's not used on server side...

**Comment by pcuriel** [comment]
Yes, the newer releases do not suffer from this problem. I don't remember exactly in which version it was fixed (maybe 2.2?), but at least in 2.4 it is working for me.

**Comment by marcandre** [comment]
@tyan4g for you validation "chain", the priority is the way to handle that.
