### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#919]
Looks like 96bf2dd2d0f6e8533, once released in `dist/`, created the problem.

Assigning to @guillaumepotier, in hope you can figure out what's going on. I tried my best but not familiar enough with the plethora of js environments to fix.

I thought maybe cfa623c607671d031fb965ad80fad0a561b7cbff would be good, it solves the loading issue but then I think there are two different jQuery loaded, and only one has `$.fn.parsley` so tests fail.

**Comment by guillaumepotier** [comment]
I fought and tried my best, but Travis is really weird. There is something wrong with the browserify environment that works on my computer™ but not there.

After wasting too much time on that, I commented it and if someone travis/browserify skilled decide to help there it would be great. Meanwhile, we do not need it to go forward.

Best
