### ISSUE TITLE
Documentation is gone

### ISSUE THREAD

**Issue by JeroenReumkens** [guillaumepotier/Parsley.js#927]
Hi,

I was trying to view the documentation page: http://parsleyjs.org/. But it seems that it is broken? Hope you can fix ik :)

Thanks,
Jeroen.

**Comment by guillaumepotier** [comment]
Yes indeed.

Little mixup with @marcandre and 2.1.0 release :) Doc is up again, still a small problem with form examples, we are investigating it.

Thanks

**Comment by marcandre** [comment]
Oups :bomb: sorry!
Should be all good now
