### ISSUE TITLE
window.ParsleyUI.getErrorsMessages(parsleyInstance) does not return an error of errors

### ISSUE THREAD

**Issue by JonForest** [guillaumepotier/Parsley.js#928]
I may be misunderstanding the docs here, but it seems to be I should pass a Parsley form instance into this method to retrieve an array of all the errors on the form.
However, whenever I do this, I receive an empty array.

Example:
https://jsfiddle.net/58vnaqur/4/

Looking at the code it appears to expect a field instance, which may be the issue.

**Comment by JonForest** [comment]
From looking at the code it seems the best thing might be just to update the docs to indicate a Field instance.  I can take a look at that if you like?

**Comment by marcandre** [comment]
Yeah, this method is only valid for a field instance. The latest release actually makes this a method of the field instances.
You could loop on the fields of a form to get the full list (or propose a new method?)

**Comment by marcandre** [comment]
I'm closing this, since this is kind of resolved, you will now get an error if calling on a form instance.
