### ISSUE TITLE
The multi steps snippit for more than one form

### ISSUE THREAD

**Issue by LoaiBassam** [guillaumepotier/Parsley.js#929]
I am trying to set-up the multi steps form validation. I followed the documentation here: "http://parsleyjs.org/doc/examples/multisteps.html" - but the only problem is I am going to have few forms that will have multi steps across the site and on some pages there will be more than one. 

Is there a way to tweak the snippet so it automatically detect if the form has more than one step and apply the appropriate behavior/settings accordingly? Rather having to duplicate that snippet over and over for each form... 

Thank you for any help

**Comment by guillaumepotier** [comment]
Sure it should be possible. But this is not Parsley's job but yours to create a script that deals with both mutli steps and Parsley validation (parsley only does validation, not steps)

Feel free to ask your question on stackoverflow though.

Best
