### ISSUE TITLE
Animating Errors

### ISSUE THREAD

**Issue by devmondo** [guillaumepotier/Parsley.js#93]
hi, 
would kindly please tell us how we can animate errors when they appear and disappear?

thanks in advanced.

**Comment by JCMais** [comment]
@guillaumepotier I see that animate was removed, and it's not mentioned in the docs, can you let me know how is the way to animate errors now? Use ``$.listen``?

**Comment by marcandre** [comment]
I'd try with pure CSS solutions, otherwise listening to `error` events...

**Comment by Madeon08** [comment]
Hi Guys,

I'm trying to add animations on alert messages, I managed to apply a fadeIn effect but just having an issue with the fadeOut.

How could I add a SetTimeOut function on the following rule:

`_removeError: function _removeError(name) {
      this._ui.$errorClassHandler.removeAttr('aria-describedby');

      this._ui.$errorsWrapper.removeClass('filled').find('.parsley-' + name).remove();
    },`

To get that:

`_removeError: function _removeError(name) {
      this._ui.$errorClassHandler.removeAttr('aria-describedby');

      this._ui.$errorsWrapper.fadeOut(500);

      setTimeout(function(){
      	this._ui.$errorsWrapper.removeClass('filled').find('.parsley-' + name).remove();
      },3400);
    },`
