### ISSUE TITLE
IE8 and IE9 don't support console.warn.apply

### ISSUE THREAD

**Issue by pangolingo** [guillaumepotier/Parsley.js#932]
IE8 and 9 fail on the warn method only when the Developer Tools are open. This is because window.console.warn.apply is undefined in those browsers. 

Link to line: https://github.com/guillaumepotier/Parsley.js/blob/e9fce9bd48a4b9e82785918d46100d23b47b6d1c/src/parsley/utils.js#L85

This issue should be visible with this JSFiddle example http://jsfiddle.net/zn42w619/ however my Windows XP VM won't load it without crashing.

I'm fixing it by polyfilling the console, as described here: http://stackoverflow.com/a/5539378

**Comment by marcandre** [comment]
Thanks for reporting this.

This is very personal, but I have no tolerance for these kinds of issues, so I simply turned it off to avoid the bug. Developers unlucky enough to work on IE8/9 can use polyfills if they want warnings.

**Comment by pangolingo** [comment]
Works for me.

**Comment by jpalomar** [comment]
@marcandre could a new patch version be built to include this conditional statement?  Even including popular console polyfills won't resolve the IE issues.  For instance, console.warn is supported in both IE8 and IE9 in basic terms: https://developer.mozilla.org/en-US/docs/Web/API/Console/warn

So console.warn is defined within the console namespace and does not return undefined.  It is not a Function in IE but an Object so the console.warn.apply() method will cause a runtime error.  Most polyfills just check if the .warn method is defined but does not discern its data type.
