### ISSUE TITLE
Parsley validation source with Google ID

### ISSUE THREAD

**Issue by toplisek** [guillaumepotier/Parsley.js#933]
I have tested many times before publishing.

Is seems source code needs many modifications to work like demo version.

As I have checked it includes also Google code and ID inside link: Examples.
How to remove Google code to work simple.html as it is all the time ID even I have removed it.
It shows all the time:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37229467-1']);
      _gaq.push(['_trackPageview']);
Need help.

**Comment by guillaumepotier** [comment]
Hi @toplisek,

- code inside `src/` indeed works with `require.js` and used that way is only development internal. Please use versions shipped into `dist/` directory

- Examples is only for online documentation and yes ships a google tracker ID to help improving the doc. Feel free to do what you want on your machine and remove it **for your projects only (do not make a PR removing it** if you want to use this page as a working base. But IMO it would be better to go from scratch from a blank html page

- Finally, if you experience difficulties working with Parsley, please look at stackoverflow.com or ask your questions there.

Best

**Comment by toplisek** [comment]
There is an issue as I have to see the same results as example and you track examples with Google. I understand you posted dist folder and it includes files.

But due to lack of information, I can only guess. Example: you have posted languages with the solution but example is not there which is crucial. Stackoverflow.com blocks user as the use computer not heads...
