### ISSUE TITLE
data-parsley-min doesn't seem to correctly work..

### ISSUE THREAD

**Issue by nickgofly** [guillaumepotier/Parsley.js#937]
I don't think that the data-parsley-min validator is working correctly.
Sometimes it doesn't register at all and lists the field as being successful while sometimes it shows the field as wrong even when the length of the input satisfies the condition. 

![parsley-being-odd](https://cloud.githubusercontent.com/assets/3395888/8680811/d5ea5962-2a31-11e5-92dd-f506283b53c6.png)

My input element looks like this:
<input required data-parsley-trigger="change" type="text" data-parsley-min="10" placeholder="First Name">

**Comment by guillaumepotier** [comment]
`data-parsley-min` is intended to validate **numbers**. Use `data-parsley-minlength` to validate strings.

Best
