### ISSUE TITLE
Form is always valid.

### ISSUE THREAD

**Issue by Eschon** [guillaumepotier/Parsley.js#940]
I can't manage to get parsley to work. When I try to submit my form it is always valid, even when I enter values that are clearly wrong. At first I thought this might be because I'm using Bootstrap but it also happens on a minimal test case like [this](http://jsfiddle.net/Eschon/3u537hb3/)

**Comment by marcandre** [comment]
`type="number"` has some [strange issues with it](https://github.com/guillaumepotier/Parsley.js/issues/874) because we can't get invalid values

**Comment by marcandre** [comment]
I tried to update the doc about this.
