### ISSUE TITLE
Textarea is not being validated.

### ISSUE THREAD

**Issue by paroxp** [guillaumepotier/Parsley.js#944]
Hi there!

Just'd like to point out the bug, where textarea is not being validated even with your example:
http://parsleyjs.org/doc/examples/simple.html

Probably something as simple, as:
$.each('input, select', func);

Didn't have time to check just yet. :(

**Edit**
Or maybe it's rather: [data-parsley-minlength] not working, as textarea[required] works just fine.

Thanks!

**Comment by guillaumepotier** [comment]
Hi there,

Textarea in the example is correctly validated. It is just an optional field that means that it is not an error to leave it empty. But if not empty, it should be valid.

**Comment by this-adarsh** [comment]
Hi @guillaumepotier,
Hope you are well and thanks for maintaing this awesome Lib,
i am tring to add a required validation on text area but its somehow not working I have tried `data-parsley-required="true" ` and `requied="true"` attributes.

Note Some other fields are validated fine.
Looking forward a help from you.
Regards 
Adarsh...
