### ISSUE TITLE
type="tel" causing error when including bracket characters

### ISSUE THREAD

**Issue by mkstix6** [guillaumepotier/Parsley.js#945]
We have a type="tel" field.
Standard .parsely() on the form.

These numbers validate:
02087777777
+442087777777

These will not:
(44)2087777777
+44(5)087777777

We assume it is the open/close bracket characters that are the problem.

As I understand it a HTML tel field isn't tested for any character pattern as countries have vastly different phone number systems. I'm not sure why parsley bothers to test it.

The parsley-error class is added and form submission is blocked but no error message is created.
*Regardless* of whether brackets are valid in HTML phone numbers there should be an error message to accompany the error class.

**Comment by marcandre** [comment]
Agreed (except that these are called parentheses, not brackets :smile: )

**Comment by mkstix6** [comment]
Sure, thanks. Can't seem to edit on my phone but perhaps can do later.

**Comment by marcandre** [comment]
Mmm, checking the code, looks like Parsley does not recognize `type=tel`... so I'm not sure what exactly you are doing to get a validation error?

**Comment by marcandre** [comment]
From what I can read, there's no accepted pattern for it anyways.

**Comment by mkstix6** [comment]
Ok, thanks. Ye there isn't a pattern for it. Just stumped as to why the parentheses seem to break the validation in our case. Ideally, parsley would ignore the whole tel input.

If you can't reproduce the problem with a tel input we can assume it's something I've broken, I guess.

**Comment by marcandre** [comment]
No problem. Let us know if we can help.
