### ISSUE TITLE
Custom error message for alphanum field does not work

### ISSUE THREAD

**Issue by hellocosmin** [guillaumepotier/Parsley.js#946]
HTML:

    <input type="text" id="username" value="" required data-parsley-type="alphanum" data-parsley-trigger="change input" data-parsley-alphanum-message="Only letters and numbers are allowed." data-parsley-required-message="Username is mandatory.">

This doesn't work, it still uses the default error message for alphanum fields.
I've also tried using `data-parsley-type-alphanum-message` instead of `data-parsley-alphanum-message` but it does the same thing, it shows the default error message.

EDIT: Parsleyjs version 2.1.3

**Comment by marcandre** [comment]
I realize it's not intuitive, but for now you have to use `data-parsley-type-message`.
