### ISSUE TITLE
Not equal comparison code is wrong

### ISSUE THREAD

**Issue by ozanmuyes** [guillaumepotier/Parsley.js#950]
Hi @marcandre, @mvpotter and @vsn4ik,

The comparison code located in here https://github.com/guillaumepotier/Parsley.js/blob/master/src/extra/validator/comparison.js#L45-L51, is just a copy-paste of "Less than or equal to validator".

FYI. Have a good weekend.

**Comment by vsn4ik** [comment]
After merge #968 (416afc5a6426175999ee1d8a4a56aaedd6a8f0b4) can be closed.
