### ISSUE TITLE
Is it possible to add a custom html5 type validator?

### ISSUE THREAD

**Issue by Hacktivista** [guillaumepotier/Parsley.js#954]
I want to add the [native](http://www.w3.org/TR/html-markup/input.date.html) "date" html5 type as a validator for my forms on my own implementation, is this possible to do with parsley?

Here's the current implementation, but not working as native html5 type

```
// Add date validator
window.ParsleyValidator.addValidator('date', function (value) {
    if (/^(?:[0-3]\d)\/(?:0\d|1[0-2])\/(?:\d{4})$/.test( value ))
        return true;
    else
        return false;
}, 32);
```

**Comment by marcandre** [comment]
Sorry for not responding before.

No, you can't customize how Parsley translates HTML5 attributes to validations.

PR accepted for missing HTML5 validations though...
