### ISSUE TITLE
Validation event handlers are called more often than expected

### ISSUE THREAD

**Issue by hypeJunction** [guillaumepotier/Parsley.js#955]
Can't get down the bottom of it, but it seems that data-parsley-trigger events are bubbling on an input.

**Comment by marcandre** [comment]
Sorry, it's not clear (to me) what the issue is...

**Comment by hypeJunction** [comment]
Sorry. Here is my problem.
My plan was to implement a custom validator using remote.js. I am using requireJS, and there seems to be race condition somewhere, so I couldn't get it to work. Not enough energy at the moment to try and debug. So, I am implementing a custom validation rule that is making an ajax request to validate a username against the database. 
I am using JS binding `$('.form').parsley()` and `data-parsley-trigger="change"` attribute on a text input. What I am seeing is that for each change event, the number of ajax calls multiplies. It seems that the handler is being bound to an input multiple times.

Here are some snippets:

```js
    require(['forms/validation'], function () {
		$('.elgg-form-register').parsley({
			errorsMessagesDisabled: true,
		}).on('field:validated', function () {
			var messages = window.ParsleyUI.getErrorsMessages(this);
			var $row = this.$element.closest('.elgg-form-row') || [];
			if (this.validationResult === true) {
				$row.removeClass('elgg-state-invalid').addClass('elgg-state-valid');
			} else {
				$row.addClass('elgg-state-invalid').removeClass('elgg-state-valid');
				$row.find('.elgg-form-error').text(messages.join('; '));
			}
		});
	});
```

```js

// forms/validation AMD module
// parsley is a shim for parsley.min.js
define(['elgg', 'jquery', 'parsley'], function (elgg, $) {

	window.Parsley
			.addValidator('username', function (value, requirement) {
				var response = false;
				elgg.action('account/validate_username', {
					data: {
						username: value,
						requirement: requirement,
					},
					async: false,
					success: function (data) {
						if (data.status >= 0 && data.output) {
							window.Parsley.addCatalog('en', {'username': data.output.message}, true);
							response = data.output.valid;
						}
					}
				});

				return response;
			}, 32);

});
```

`elgg.action` is just a wrapper for `$.ajax`. So, when, I first type a username, I see one ajax call. If I focus in again, and start typing, I get 4-6 simultaneous ajax calls. If I focusout and focus in again, I start loosing track of them - there are too many to count.

**Comment by hypeJunction** [comment]
I don't think this matters, but here is the HTML:

```html

<div class="elgg-form-row">
				<label>Choose username</label>
				<div class="elgg-form-input">
					<input type="text" name="username" required="required" data-parsley-username="data-parsley-username" data-parsley-trigger="change" autocomplete="off" class="elgg-input-text">				</div>
				<div class="elgg-form-status">
					<div class="elgg-form-message"><span class="elgg-icon-done"></span></div>
					<div class="elgg-form-error"></div>
				</div>
			</div>
```

**Comment by marcandre** [comment]
Mmm, from what I gather, instead of using the parsley code that handles asynch validations, you are doing some other kind of black magic to do it yourself and then that doesn't work and you'd like that to be fixed?

I'd recommend you fix your race condition (there shouldn't be any), and if you want to do anything aynch with Parsley, either use the built-in `remote` validator, or use the 2.2.0rc1 release and return a promise from your custom validator. Anything else is just asking for major problems.

If I've misunderstood something, let me know and I'll reopen.

**Comment by hypeJunction** [comment]
Man, seriously, don't treat me like a complete noob.

AJAX and remote has nothing to do with the issue. I just posted my code for illustration. I have just replaced all ajax calls with `console.log(value)` to be sure, and I am telling you there is an issue with event bidning.

On first pass, `change` event fires as expected. However, when you go back to edit the field value, it fires on each `keydown`. 

This is what is logged:

```
validation.js:6 1234567890
validation.js:6 1
validation.js:6 12
validation.js:6 123
validation.js:6 1234
validation.js:6 12345
validation.js:6 123456
validation.js:6 1234567
validation.js:6 12345678
validation.js:6 123456789
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1
validation.js:6 12
validation.js:6 123
validation.js:6 1234
validation.js:6 12345
validation.js:6 123456
validation.js:6 1234567
validation.js:6 12345678
validation.js:6 123456789
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
validation.js:6 1234567890
```

**Comment by marcandre** [comment]
Man, seriously, I didn't mean to treat you like a complete noob. Please realize that it can be difficult to understand what your are saying when your title, your original post, and your first paragraph and most of your code is either unrelated or incorrect (or I'm missing something and it actually has something to do with bubbling per say).

That being said, it's very possible that `trigger` is incorrect, although I don't know what you're trying to achieve with `trigger=change`, since that's the default (albeit incorrect, it should be `input`).

In your console, I don't know if you're calling `validate` or submitting at any point, or when you're focusing in and out. If you are, the `Parsley` handles things differently and tries to validate often to remove that failing message as soon as the input is corrected (`manageFailingFieldTrigger` binds `change.ParsleyFailedOnce`). Is that what is happening?

**Comment by hypeJunction** [comment]
Sorry for all the confusion. I was reporting this at 1am after a 15-hour work day. I am on a tight schedule and chose Parsley as I thought it would simplify client-side validation. Unfortunately, I don't have time to dig into the source code to understand all the internals, and the documentation lacks some real-life examples of "correct" usage. I have baked up a solution based on examples I have found online. I am building a prototype, and I am not yet concerned with performance or code quality - I just need a working example. I am not even sure, I will use Parsley in the end. Perhaps I will opt for a simpler custom solution - I only have a few forms to validate.

What's happening is:
- I type in a full word, when I focus out, the field is validated.
- I then remove the word and start typing again - validation callback is triggered on each key down, plus the whole word is validated again when I focusout
- I then remove the word and start typing again - validation callback is triggered on each key down, plus multiple times when I focus out

I hope this clarifies things.

**Comment by hypeJunction** [comment]
FYI, I have tried including remote both as AMD module and using <script> and I get all the same: Uncaught TypeError: Cannot read property 'addValidator' of undefined. Not sure what I am doing wrong, but I think I have exhausted the amount of time, I am willing to spend on this.

**Comment by hypeJunction** [comment]
With 2.1.3 I get: parsley.remote.js:2498 Uncaught TypeError: Cannot read property 'on' of undefined

**Comment by marcandre** [comment]
Thanks @hypeJunction I'll see what I can figure out. "multiple times when I focus out" seems like a clear bug.

If easy for you, the full stack trace would be helpful for the error.

**Comment by hypeJunction** [comment]
Will do when I am back online. Have to run now.

**Comment by hypeJunction** [comment]
Re: why add 'data-parsley-trigger'. If not set, the fields are only validated when submit button is clicked. I have now rewritten the code to return a promise, and with form only validated on submit, there is a slight delay, which might be a bit confusing for the user. I will need to add some preloader.

**Comment by hypeJunction** [comment]
The root cause seems to be 'keyup' binding on lines 931-932 of compiled js (2.2.0-rc1). Setting those to 'change' fixes the multiple validation events being fired, not sure if it affects other functionality - you probably know the reasoning behind it.

**Comment by hypeJunction** [comment]
I am all set with promises, multiple validators that return promises work like a charm. The only thing you may want to mention in the docs is that requests with an empty response body do not resolve and get rejected.

**Comment by marcandre** [comment]
Haven't had time tonight to check multi binding, sorry, but wanted to comment about the empty response body. I never realized this and have opened [#956] that relates to this. I think an empty response body could be rejected, but only depending on the content type the server sends out. Can you check which your ajax request is receiving? In particular, `""` is not valid JSON, but is valid text.

**Comment by hypeJunction** [comment]
Ah, you are right, I was sending an empty string with an `application/json` content type header.

**Comment by marcandre** [comment]
Should have been fixed a while back
