### ISSUE TITLE
Should remote rely on xhr state or status?

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#956]
I got really confused about some jQuery's `xhr` ajax request having `status == 200` and `state == rejected`. Not obvious at all, but if a server answers with something that jquery's Ajax "Intelligent guess" dislikes, even though status code is 200, the promise gets `rejected`.

I was [testing in JSfiddle](http://jsfiddle.net/marcandre/ke8ebpcp/) with `/echo/js/?js=hello%20world!`, but since `hello world!` is not valid javascript, I was in that situation. Using `/echo/js/?js='hello%20world!'` (notice the quotes!) returns valid javascript, so then you have state and status agreeing.

Another example is an empty response. It's valid if the content type is 'text/plain', but not if 'json'.

The question is then: should the `remote` validator rely on `state`, or `status`? It's been relying on `state` for now. In either case, we need a caveat in the doc.

@guillaumepotier opinion?

**Comment by guillaumepotier** [comment]
I think `state` have more edge cases than `status` which is "dumber" (2xx/the rest).

Maybe we should rely on `status` only and update the doc accordingly for default validator.

But as often people do not really have a hand on the API, it should be still possible to define a custom validator that could check response content to perform custom check and do not rely on a buggy `status`  for example (let's say a 200 response code with empty content that should lead to a reject validation)

WDYT?

**Comment by marcandre** [comment]
Exactly my thoughts :smile:

**Comment by marcandre** [comment]
Tweaked
