### ISSUE TITLE
Trying to use Promise in Custom Validator

### ISSUE THREAD

**Issue by rtmalone** [guillaumepotier/Parsley.js#958]
Cool. Ok, so I've got a custom validator working in the strictest sense when `validateString` returns either `true` or `false`. I've noticed in the current docs that validating functions "can instead return a promise that will be resolved if the value is valid, or be rejected otherwise". That is what I need to happen, but am having difficulty implementing it. I'm using the native JS Promises like so:

```
validateString: function(){
    var promise = new Promise(function(resolve, reject){

          confirmEmailAjax(function(boolean){
              if (boolean) {
                  resolve('Yay');
              } else {
                  reject('sad face');
              }
          });

     });

    return promise;
},
```

`confirmEmailAjax` is returning either `true` or `false`. @marcandre can you shed some light on this? Is the promise referenced in the docs utilized differently? If I need to open a thread on this some where else, I'll happily do so. Let me know.

**Comment by marcandre** [comment]
Mmm, we are expecting a jQuery promise, actually. Can you try that?
On my end I can look and see if we could be compatible with both at little cost.

**Comment by marcandre** [comment]
So... your code will work fine, but only with jQuery 3.0+. Sadly, the current alpha will probably not work because of [a bug](https://github.com/jquery/jquery/issues/2546).

In the meantime, please use jQuery promises. I've updated the doc to make that more clear.

I'll close this, but let me know if that doesn't work and we reopen.

**Comment by rtmalone** [comment]
Yep, this works well. Gonna leave this here to help others:

    validateString: function(){
        var deferred = new $.Deferred(function(){

            confirmEmailAjax(function(boolean){
                if (boolean) {
                    deferred.resolve(boolean);
                } else {
                    deferred.reject(boolean);
                }
            });
        });

        return deferred.promise();

**Comment by janwidmer** [comment]
Hey @rtmalone,
I had a similiar case also including an ajax call in my validator. The solution you described gave me an deferred is undefined error.

I could only make it work like this:

```
window.Parsley.addValidator('pregnancyDate', (value, requirement) => {
	const def = new $.Deferred();
	const timestamp = Date.parse(moment(value, requirement));

	if (!isNaN(timestamp)) {
		$.ajax({
			url: this.myProfileUrlPregnancyValidate,
			dataType: 'json',
			type: 'post',
			data: {
				date: value,
			},
			async: false,
			success: (response) => {
				if (response.valid) {
					def.resolve();
				} else {
					def.reject(response.error);
				}
			},
			error: () => {
				def.reject();
			},
		});
	} else {
		def.reject();
	}

	return def.promise();
});
```

@marcandre it would be great if the docs could be extended by an example of a custom validator containing an ajax call and a promise. I needed quite a long time to figure out that this is a great alternative to the remote validator, specially when you need to return e special error message based on the server's answer.

**Comment by marcandre** [comment]
I've meant to write an example with promises / Ajax forever. Let me see if I can put one together

**Comment by marcandre** [comment]
I added [an example](http://parsleyjs.org/doc/examples/ajax.html) which I hope can be instructive. Let me know

**Comment by janwidmer** [comment]
Perfect, thanks, that should fill the gap between custom validatior and remote validator. Thanks a lot.
