### ISSUE TITLE
With Custom Validator, Form is Not Submitting As Expected

### ISSUE THREAD

**Issue by rtmalone** [guillaumepotier/Parsley.js#963]
I'm using two custom validators which fire AJAX calls within a jQuery promise. Both of those work great. When the form is valid (that is, when Parsley has not applied any errors) a click on a button to submit the form just fires the validations again;  I can see the AJAX calls being made, but the form does not submit. A following second click on the button, will fire the validators again **and** submit the form. Obviously, this is not ideal to a user. Not sure what part of my code you may want to see, but I'll gladly provide what you'l like to see. Thanks!

**Comment by marcandre** [comment]
Thanks for reporting this. Are you using the latest 2.2.0rc1 version?

**Comment by rtmalone** [comment]
yes I am.

**Comment by marcandre** [comment]
I'd be glad to check it out. Ideally access to the site, otherwise the parsley related JS and markup. You can email me if you need it to remain private.

**Comment by rtmalone** [comment]
cool, thanks. sent you an email to the address listed on github

**Comment by rtmalone** [comment]
Here is another clue. Within the custom validator, when I wrap the code inside the Promise with a conditional. The form will never submit on a btn click. 

```window.Parsley
      .addValidator('emaillookup', {
        requirementType: 'string',
        validateString: function(){
          var deferred = new $.Deferred(function(){

            if ( // some conditional ! true ) {
              confirmEmailAjax(function(boolean){
                if (boolean) {
                  deferred.resolve(boolean);
                } else {
                  deferred.reject(boolean);
                }
              });
            }
          });

          return deferred.promise();

        },
        messages:{
          en: 'This email is already used in another Organization',
          de: 'Diese eMail addresse wird schon in einer anderen Organisation verwendet' // because we have Rene!
        }
      }
    )```

**Comment by marcandre** [comment]
Haven't looked at it yet, but if your promise is stuck as `pending` forever, then so is the validation... that's what's happening with your conditional

**Comment by rtmalone** [comment]
huh…that does make sense.  Well I think, with cautious optimism, I’ve got a working solution combining manually validating the form in a couple places and then using the promise returned from whenValidate(). My JS is not as DRY as is probably could be, but I just had a coworker sit and try to break the form or experience any unexpected validation behavior. And it was successful. I’ll probably take the rest of the day to clean things up and then I’ll try to explain/show more of my solution here to help out.

**Comment by jplaza** [comment]
Not using a custom validator and using rc4 but form is not submitting at all. `isValid()` returns true

**Comment by marcandre** [comment]
Did you ever fix your code?

**Comment by rtmalone** [comment]
Yes, I did. Thanks so much!
