### ISSUE TITLE
Documentation code for custom validation has errors

### ISSUE THREAD

**Issue by micahblu** [guillaumepotier/Parsley.js#969]
The current code snippet @ http://parsleyjs.org/doc/index.html#psly-custom-intro calls on window.Parsley instead of window.ParsleyValidator, also there is a missing '}' before the closing ')'; Below is a corrected version of the snippet
```js
window.ParsleyValidator // was window.Parsley
  .addValidator('multipleof', {
    requirementType: 'integer',
    validateNumber: function(value, requirement) {
      return 0 === value % requirement;
    },
    messages: {
      en: 'This value should be a multiple of %s',
      fr: 'Cette valeur doit être un multiple de %s'
    }
  }); // was missing '}'
```

**Comment by marcandre** [comment]
The documentation refers to the latest version 2.2.0rc1, which changed the API (although the previous API is still supported).

**Comment by micahblu** [comment]
Exactly I have the 2.2 latest version and it is the docs for that version which appear to be an error. Unless I'm missing something here. I have the latest version and the current code snippet for 2.2 docs does not work.

**Comment by micahblu** [comment]
Thanks that appears to work

**Comment by micahblu** [comment]
p.s the missing '}' is still an issue

**Comment by marcandre** [comment]
:+1: fixed, thanks :smile:
