### ISSUE TITLE
Issue adding custom validators using requirejs

### ISSUE THREAD

**Issue by micahblu** [guillaumepotier/Parsley.js#970]
Is there a way to add custom validators in define blocks?

I have the following:
```js
define(function (require) {

	var $ = require('jquery'),
		    parsley = require('parsley');
		
	window.ParsleyValidator.addValidator('validateTracknum', {
		requirementType: 'string',
		validateString: function(value, requirement) {
			console.log('testing', value, requirement);
			return false;
		}
	});

	$('#track-transaction-form').parsley();
});
```
and for the html:
```html
 <input autofocus tabindex="1" type="text" autofocus="" id="tracking-number" class="tracking-input" placeholder="Tracking #" required data-parsley-validateTracknum>
```

The validateString function never runs? Thanks for any help.

**Comment by marcandre** [comment]
As specified in the documentation, you should use the attribute `data-parsley-validate-tracknum`, this will be camelcased by Parsley.
Does it fix the issue?

**Comment by micahblu** [comment]
Unfortunately not, with the same code as above but the updated html attribute `data-parsley-validate-tracknum` I now receive an error: Uncaught Error: Callback must be instanciated with a function - parsley.js line 598

**Comment by marcandre** [comment]
Please use the latest version.

**Comment by micahblu** [comment]
That does the trick, I'm sorry I thought bower would have pulled the latest but it pulled 2.1.*. Thanks for the help
