### ISSUE TITLE
Submit after validate and ajax success ?

### ISSUE THREAD

**Issue by hellodeloo** [guillaumepotier/Parsley.js#971]
Hello,

I'm trying to validate a form and send it only if the ajax response is a success. 
For that I have to stop submit with preventDefault() but I do not know how, finally restart the submit if the ajax answer is a success.

Below my js code

	form = $('.form-don');
	form.parsley();

	form.on('submit', function(e) {
		f = $(this);
		f.parsley().validate();

		don = {
			action: 'addlog',
			name: $('#don_last_name').val(),
			firstname: $('#don_first_name').val(),
			city: $('#don_city').val(),
			amount: $('#don_amount').val(),
			date: new Date()
		}

		if (f.parsley().isValid()) {
			$.ajax({
				type: "POST",
				url: './log/log.php',
				dataType: 'json',
				data: don,
				success: function() {
					return f;
				}
			});
		}
		e.preventDefault();
	});

**Comment by fastfrwrd** [comment]
Has nothing to do with Parsley, but you should move `ev.preventDefault()` out of the isValid conditional. That needs to be called to prevent the default browser behavior of POSTing to your form's action. The cleanest way it's usually done is to call `ev.preventDefault()` first thing in your submit handler.

**Comment by fastfrwrd** [comment]
Actually, i just misread your code due to the indentation. Still, a good first step would be to move that to the beginning of the method so JS errors or other shenanigans can't cause the page to refresh.

**Comment by marcandre** [comment]
@hellodeloo Why don't you use parsley to do this for you? Say you add a custom validation that posts the Ajax request and returns that (latest release accepts promises/xhr) and parsley will take care of the submit thing.

Otherwise check how we do it, but it's tricky.

Finally, please follow our guidelines and post questions on StackOverflow. Thanks
