### ISSUE TITLE
Don't trigger validation on certain buttons

### ISSUE THREAD

**Issue by torotil** [guillaumepotier/Parsley.js#972]
I have a form with to submit-buttons. One is labelled "submit" the other "cancel". Now I want to trigger the parsley validation on every submit except when the "cancel" button triggered the submit.

Is there a way to achieve this?

I think there should be a config+markup only way to achieve this, but looking at the source code I haven't found one.

**Comment by marcandre** [comment]
But you want the 'cancel' button to nevertheless submit the form?

I imagine that in the 'cancel' case, you don't actually want the content of the inputs, so couldn't you put that button in a separate `<form>`?

**Comment by torotil** [comment]
Yes I could. I still would need to "link" those forms on the server-side, which makes that more complex/fragile: Two forms manipulating the same "form state" …

Having non-validating submit-buttons is something that is so common that there even is a HTML5 attribute for that: http://www.w3schools.com/tags/att_input_formnovalidate.asp . That alone is a reason to support it.

**Comment by marcandre** [comment]
Great, thanks for pointing out `formnovalidate`. I guess the best thing would be to support it, at least for the submit buttons...

**Comment by marcandre** [comment]
Fixed in `master`, thanks again :smile:

**Comment by xavianaxw** [comment]
Super useful when validating with a CMS like Shopify. 
https://help.shopify.com/themes/development/templates/customers-activate-account

Using `formnovalidate` here on 'Decline Invitation' should do the trick ;)

Thanks again @marcandre
