### ISSUE TITLE
maxlength validator does not work is field value is NULL

### ISSUE THREAD

**Issue by oliverhunt** [guillaumepotier/Parsley.js#974]
It produces this error:

"Lenth assert must be instanciated with a { min: x, max: y } object"

**Comment by marcandre** [comment]
`length`, or `maxlength`?
"field value is null" means?
Please read [this](https://github.com/guillaumepotier/Parsley.js/blob/master/CONTRIBUTING.md)

**Comment by oliverhunt** [comment]
When the value of an input is === NULL

**Comment by marcandre** [comment]
Please read [this](https://github.com/guillaumepotier/Parsley.js/blob/master/CONTRIBUTING.md)
