### ISSUE TITLE
How to add Async Validator before Parsley loads?

### ISSUE THREAD

**Issue by fantapop** [guillaumepotier/Parsley.js#975]
In older versions of parsley I created a global ParsleyExtend object which included the async validator definition like this:

```
window.ParsleyExtend = {
    asyncValidators: {
        myValidator: {
            fn: function (xhr) {
                 // doing stuff
            }
        }
    }
};
```

In the latest version 2.2.0-rc1, the async validator specified here does not end up in the final array of async validators.

**Comment by fantapop** [comment]
I see that I'm having the same issue with customized messages.  I need a way to customize the messages before the parsley object loads.  The reason for this is that we're also using garlicjs.  Our inputs may contain values on page load.  Since we're using parsley data-attributes to define customizations, these all run before we can access the Parsley object.

**Comment by marcandre** [comment]
Haven't had the chance to look into it, but there is no valid reason to do anything before `parsley` loads. Ever. It's a "feature" I really disagree with :imp: but I thought I had maintained compatiblity.

The binding of `parsley` happens on document ready (i.e. `jQuery(function() {...})`) . So load `parsley`, customize it, and you should be fine. Let me know if I'm missing something.

**Comment by fantapop** [comment]
Okay, I've been configuring Parsley on load event.  It the data-attribute triggers don't fire right away, it should work to execute a script after loading parsley.  I'll give it a shot.  Thanks!

**Comment by fantapop** [comment]
So that did work.  The only thing I can suggest is to make that a little clearer in the docs. Thank you again!

**Comment by marcandre** [comment]
Sure. Would you care to make a PR with some changes?

**Comment by fantapop** [comment]
I'll look a little closer at the docs and see if there's a good place to add it in.  Its somewhat difficult because there are so many docs.
