### ISSUE TITLE
TypeError: window.Parsley.addAsyncValidator is not a function

### ISSUE THREAD

**Issue by janimattiellonen** [guillaumepotier/Parsley.js#980]
I get "TypeError: window.Parsley.addAsyncValidator is not a function" with the following code:

<script type="text/javascript">
    $('#user-registration-form').parsley(); 

    window.Parsley.addAsyncValidator('mycustom', function (xhr) {
        console.log(this.$element); // jQuery Object[ input[name="q"] ]

        return 404 === xhr.status;
    }, 'http://example.com/');

</script>

In the head element I have the following (both scripts' urls are correct - I have checked that):

    <script type="text/javascript" src="/lib/parsleyjs/dist/parsley.remote.js"></script>
    <script type="text/javascript" src="/lib/parsleyjs/dist/parsley.js"></script>

The actual code above I have placed inside the body element. I'm using version 2.2.0-rc1

**Comment by marcandre** [comment]
Please load one or the other, but not both. In your case you need the `remote` version.

Sorry about the confusion. We plan on merging those versions in the (hopefully) near future.

**Comment by janimattiellonen** [comment]
This text in docs is a bit confusing to me then:

"To use this plugin, either load parsley.remote.js before loading parsley.js, or directly load parsley.remote.js. "

**Comment by marcandre** [comment]
Sorry about that. I had updated the doc, but not pushed to `gh-pages`. Should be good now.

**Comment by janimattiellonen** [comment]
Same issue here:

http://parsleyjs.org/doc/index.html#psly-installation-localization

See section "Custom remote validators".

The example has both of these:

<script href="parsley.remote.js"></script>
<script href="parsley.js"></script>

**Comment by marcandre** [comment]
Oh my! Fixed, thanks :smiling_imp:
