### ISSUE TITLE
dependency on validator.js ?

### ISSUE THREAD

**Issue by Sinewyk** [guillaumepotier/Parsley.js#981]
Does this library depend on https://github.com/guillaumepotier/validator.js in any way ?

I don't see it in the package.json but I can't help but see tons of similarities and I'm wondering whether to contribute on validator.js or Parsley.js with my validation needs.

**Comment by guillaumepotier** [comment]
Hi @Sinewyk,

Originally Parsley 2.0 have been built on top of validator.js as validation mechanism. Recently we decided with @marcandre to implement validation directly into Parsley and stop relying on validator.js as it moves in its own object-server-oriented way and were too heavy for not so much here on Parsley.

So, you'll need to work directly now inside Parsley if you want to contribute in any way with validators :)

Hope that helps

Best

**Comment by marcandre** [comment]
You'll find the current validators in `src/parsley/validator_registry.js` @Sinewyk :smile:

**Comment by Sinewyk** [comment]
Yep, it does help. Thanks =).
