### ISSUE TITLE
radio and checkbox inputs: wrong error container placement 

### ISSUE THREAD

**Issue by wujekbogdan** [guillaumepotier/Parsley.js#982]
Parsley  v2.2.0-rc1

For all the inputs in case of error **the input** gets _.parsley-error_ class and _.parsley-errors-list_ list container is appended right after the input. This is a normal, expected behaviour.

For radios and checkboxes **the closest parent** gets _.parsley-error_ class and _.parsley-errors-list_ is appended right after the closes parent.

Example: http://jsfiddle.net/58vnaqur/7/

PS
I'm not sure is it a bug or a feature. But if it's a feature it can generate invalid markup if we're using a list to create a form markup (which is a common practice). Take a look: http://jsfiddle.net/58vnaqur/6/
In case of error `<ul class="parsley-errors-list">` element is appended directly inside `<ul>` which is not a valid markup. I know I can wrap checkbox/radio input in additional tag (let's say `span`), but it's just a workaround.

**Comment by marcandre** [comment]
Yeah, it's a "feature", not a great one though. Suggestions welcome. In the meantime, you probably want to play with `classHandler` to get something that works for you
