### ISSUE TITLE
How to validate the input is a valid date format?

### ISSUE THREAD

**Issue by sl5310** [guillaumepotier/Parsley.js#983]
How to validate the input is a valid date format?

**Comment by Jogai** [comment]
[Craft your own](http://parsleyjs.org/doc/index.html#custom) with [moment js validation](http://momentjs.com/docs/#/parsing/is-valid/) for example.

I did it for another validation library, but it comes down to returning this:
```javascript
                return moment(value, dateFormat).isValid();
```

**Comment by marcandre** [comment]
Hope that helped. For further questions, please use StackOverflow as requested in our Contributing guidelines.
