### ISSUE TITLE
Problems when optimizing with r.js

### ISSUE THREAD

**Issue by crebuh** [guillaumepotier/Parsley.js#984]
Hi,
after updating to version 2.2.0rc1 (to be able to use the promise behaviour of whenValid method) we've got a problem when optimizing our project with r.js

We have written several custom validator for our project. e.g.

				window.ParsleyValidator.addValidator('iban', {
						requirementType: 'string',
						validateString: function(value, requirement) {
							return IBAN.isValid(value);
						},
						messages: {
							en: Labels.validation.iban,
							de: Labels.validation.iban
						}
					});

Before optimizing/minifying everything works fine, but after the r.js process the following error is thrown:

     Uncaught TypeError: Cannot read property 'addValidator' of undefined

Seems that the ParsleyValidator object is not present?

Does anybody has the same problem? In the meanwhile we switched back to 2.0.5

**Comment by marcandre** [comment]
It looks like your minimizer is changing the name `ParsleyValidator` to something else. There's probably a list of exception you can add?

Does is do the same for `window.Parsley`? Because you should use `window.Parsley.addValidator` anyways...

**Comment by crebuh** [comment]
@marcandre 

I guess you are right, but I cant find any hint, how to exclude certain variables during the optimizing process. 

Here are some options:
https://github.com/mishoo/UglifyJS2#compressor-options
https://github.com/mishoo/UglifyJS2#beautifier-options

as well as the r.js optimizer config example

https://github.com/jrburke/r.js/blob/master/build/example.build.js

**Comment by marcandre** [comment]
Any way to see the error for myself?
Is `window.Parsley` defined?

**Comment by marcandre** [comment]
Closing this, let me know if it's still an issue.
