### ISSUE TITLE
Parsley.js with “use strict” breaks some functionality

### ISSUE THREAD

**Issue by davekobrenski** [guillaumepotier/Parsley.js#987]
Just an FYI, in case its been plaguing anyone else: be careful if concatenating parsley.js with other files where `use strict` is used, as this will break some of parsley’s functionality.

Any chance this will be addressed in future versions of parsley?

Thanks!

**Comment by marcandre** [comment]
Yeah, for sure. I'm surprised it doesn't, tbh. We want to move to ES6 & babel, so the resulting "standard" javascript would be "use strict" compatible for sure.

Not too sure if I'll have the time to fix that beforehand, but if you can come up with a PR, I'd be happy to merge it

**Comment by davekobrenski** [comment]
cool, I’ll take a look and see what I can do...might not have time right away either, but this would help clean up a project I’m working on and I think its just a matter of some variables that were undeclared (in my quick tests, the only part of parsley that didn’t seem to work with “use strict” was the UI stuff, automatically adding classes etc...didn’t actually throw any errors)

**Comment by marcandre** [comment]
Latest release is `use strict` itself. Thanks for raising the issue.
