### ISSUE TITLE
Custom validation rules: Default message is displayed in case of dash separated data attributes

### ISSUE THREAD

**Issue by wujekbogdan** [guillaumepotier/Parsley.js#990]
I tried to register a custom validator: `data-parsley-my-custom-rule', so I did:

``` javascript
window.Parsley
    .addValidator('myCustomRule', {
        requirementType: 'string',
        validateString: function (value, requirement) {
            // validation rules rules
        },
        messages: {
            en: 'My custom message'
        }
    });
```

Validator worked fine, but instead of `"My custom message"` the default `"This value seems to be invalid."` text was displayed.

I've found that my custom message exists in the `window.ParsleyConfig.i18n.en` object, but instead of: `myCustomRule` the property is named `mycustomrule`.

That's why the default message was displayed.

The problem is here. Object property name is converted to lower case.
``` javascript
// From parsley source
addMessage: function (locale, name, message) {
      if ('undefined' === typeof this.catalog[locale])
        this.catalog[locale] = {};
      this.catalog[locale][name.toLowerCase()] = message; // Object property name is converted to lower case.
      return this;
    }
```

The workaround is simple. Instead of  `data-parsley-my-custom-rule` I use `data-parsley-mycustomrule`.

I'm not sure is it a bug or a feature, but it definitely should be documented.

**Comment by marcandre** [comment]
Agreed, that's a bug!
Should definitely work, sorry about that.

**Comment by marcandre** [comment]
Fixed in `master`. Thanks for reporting this!
