### ISSUE TITLE
"`constraint`-message" should override "error-message"

### ISSUE THREAD

**Issue by obourne** [guillaumepotier/Parsley.js#994]
If you set a general error message for a field (e.g. data-parsley-error-message="my error") it overrides any more specific error messages (e.g data-parsley-required-message="my specific error"). It would be more useful to allow the more specific message to override the less specific. 

If you have 3 different validation constraints but 2 require the same error you need to duplicate the message rather than have it as the default message.

This seems to be a simple change, as far as I can see the code is at 722 on the dist file.

**Comment by marcandre** [comment]
I agree that it would be best, but not sure it's as simple as you think it is.

Closing this as I don't think I will work on this, but would accept a PR.
