### ISSUE TITLE
parsley.remote via require js: Cannot read property 'addValidator' of undefined

### ISSUE THREAD

**Issue by jdieckmannelm** [guillaumepotier/Parsley.js#996]
I am getting this error when trying to load the parsley.remote.js as AMD via requirejs using Chrome:

```javascript
Uncaught TypeError: Cannot read property 'addValidator' of undefined
```

Here is a simplified jsfiddle example: http://jsfiddle.net/y72eusdy/7/
It's using the latest rc-build of parsley.

I don't know if it is related to this issue https://github.com/guillaumepotier/Parsley.js/issues/985 in any kind, which only occurs with the minified version of parsley. At least this is what the user pointed out. In his example i cannot reproduce his "...'on' of undefined" error but i also get the "...'addValidator' of undefined" error.

I couldn't find any existing issue which fits exactly mine.

Any help would be appreciated.

**Comment by SebT** [comment]
When using browserify, you must use `ParsleyValidator.addValidator` instead of `Parsley.addValidator`. It may be the same with AMD.

**Comment by jdieckmannelm** [comment]
Thx for the suggestion! Unfortunately i get this error by just requiring the parsley.remote.js without doing anything with it :-(

The parsley initialization tries to call the "addValidator" method of the not existing Parsley object itself. Must be a timing issue and might have something to do with packaging order within the parsley.remote.js but i am not 100% sure.

**Comment by SebT** [comment]
See if this helps : https://github.com/guillaumepotier/Parsley.js/issues/985#issuecomment-148453494

**Comment by jdieckmannelm** [comment]
@SebT Thank you very much for the hint! The described problem with parsley when loading via requirejs seems to be the same so i look forward to seeing the es6 branch merged. As soon as this is the case i will test it out.

I'll close my ticket for now. Thx!
