### ISSUE TITLE
Accessing the method `addCatalog` through ParsleyValidator is deprecated.

### ISSUE THREAD

**Issue by almogdesign** [guillaumepotier/Parsley.js#997]
Getting the following messages with the latest version 

parsley.js:93Accessing the method `addCatalog` through ParsleyValidator is deprecated. Simply call `window.Parsley.addCatalog(...)`
parsley.remote.js:93 Accessing the method `addCatalog` through ParsleyValidator is deprecated. Simply call `window.Parsley.addCatalog(...)`

**Comment by marcandre** [comment]
The bundled locale files need to be updated, in which case you can ignore this message. Or maybe you are calling `ParsleyValidator.addCatalog` yourself?

**Comment by almogdesign** [comment]
I updated the local files from latest rc version, are you sure they are updated on the release branch

**Comment by marcandre** [comment]
Sorry, I wasn't clear, the bundled local files *that we provide right now* need to be updated *by us*, sorry. In the meantime, you can ignore the message.

**Comment by almogdesign** [comment]
I see can you keep this up and update the issue when they have been update. I will update the parsley.js meteor package, by the way glad to get your support and make my package the meteor package I will maintain it - https://atmospherejs.com/almogdesign/parsley.js
