### ISSUE TITLE
Is there a way to trigger an error directly?

### ISSUE THREAD

**Issue by nilssolanki** [guillaumepotier/Parsley.js#999]
I have seen the possibility to add errors via `window.ParsleyUI.addError`, but there I always have to specify an error name and message. Otherwise, my search has been pretty fruitless. Is it possible to trigger an error I have already set up on my input field?

Example:

    <input type="text" name="fullname id="fullname" class="form-input" data-parsley-trigger="focusout" data-parsley-error-message="Please enter your name." required="required" />

I would like to be able to trigger the error on that field with the predefined variable.

*Or even better:*

Can I directly render that parsley error in my html so that parsley will recognize it as its own and remove it, once the field has been filled:

    <input type="text" name="fullname id="fullname" class="form-input" data-parsley-trigger="focusout" data-parsley-error-message="Please enter your name." required="required" />
    <ul id="parsley-id-46" class="parsley-errors-list filled">
        <li class="parsley-custom-error-message">Please enter your name.</li>
    </ul>

Thank you in advance, and sorry if I'm asking an obvious question.

**Comment by marcandre** [comment]
IIC, you'd like to that the form behaves like if the user had already submitted? Why don't you simply do `$('form').submit()` after your form is loaded?

**Comment by nilssolanki** [comment]
Not quite. I'm doing server-side validation (but not via ajax, so as far as I can see, parsley.remote is not an option). The server then rerenders the page (either with an error attribute only on the input fields that erred, the error html rendered directly next to the fields or the fields that erred in a JS object in a script tag).

Is there a way to do that?

**Comment by marcandre** [comment]
Sorry, but I'm not completely sure I understand.

If you call `$('your-input').validate()`, that will force validation on that particular input. If it's required and has no value, the error message will display. Is that what you're looking for?

**Comment by nilssolanki** [comment]
Sorry, I hope one more attempt can help to clear it up:
I want to validate the form in the backend (using validators that don't exist in the frontend). If the field has been deemed wrong, I want to show an error in the frontend. Ideally the backend could just post parsleys error-list into the html.

Then parsley should be able to recognize the list. When the user changes something, and it is okay by *parsley's* rules, it should remove the message.

Now that I write it down like this, it does sound awfully complicated...

**Comment by marcandre** [comment]
Re-reading the whole thing, I don't get why this is not resolved using an ajax request to validate the field. Please ask a question on StackOverflow if I'm still missing something.
Thanks, sorry I couldn't help.

**Comment by joerick** [comment]
I've want something similar - my solution was this:

```js
var parsleyForm = $('#signup-form').parsley();
parsleyForm.on('form:validate', function () {
    $('.backend-error-list').remove()
});
```

This will remove any errors that are in the server response when parsely validates.
